import { expect, type ElectronApplication, type Page, type TestInfo } from '@playwright/test';
import { savePart } from './scriptsFlow.js';
import { reopenPart } from './reopenPart.js';

/** The same real input, non-unique rejection, and file round trip in every supported host. */
export async function mathLinearFlow(page: Page, info: TestInfo, app?: ElectronApplication): Promise<void> {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByRole('tab', { name: 'パラメータ', exact: true }).click();
  await page.getByRole('button', { name: '名前を付けた数値を足します', exact: true }).click();
  const row = page.locator('.pcad-parameter').last(), dialog = page.locator('.pcad-math-dialog');
  const name = row.locator('.pcad-field').nth(0).locator('input');
  await name.fill('連立式の解'); await name.press('Enter');
  await row.getByRole('button', { name: '数式で入力', exact: true }).click();
  const apply = dialog.getByRole('button', { name: 'この式を使う', exact: true });
  await expect(dialog.locator('textarea')).toBeFocused();
  await dialog.locator('textarea').fill('linearsolve([[1,2],[2,4]],[1,2])');
  await expect(dialog.locator('[role="status"]')).toContainText('解が一つに決まりません');
  await expect(apply).toBeDisabled();
  const source = 'component(linearsolve([[2,1],[1,-1]],[5,1]),1)';
  await dialog.locator('textarea').fill(source);
  await expect(dialog.locator('[role="status"]')).toHaveText('= 2');
  await dialog.getByRole('button', { name: '構造入力', exact: true }).click();
  await expect(dialog.locator('math-field')).toBeFocused();
  await dialog.locator('summary').filter({ hasText: '記号と演算を探す' }).click();
  const category = dialog.getByLabel('数学の分野', { exact: true });
  await expect(category).toHaveAccessibleName('数学の分野');
  await category.selectOption({ label: '線形代数' });
  const search = dialog.getByRole('searchbox', { name: '名前・記号で検索', exact: true });
  await search.fill('連立');
  await expect(dialog.getByRole('button', { name: /連立一次式の一意な解/u })).toBeVisible();
  await expect(dialog.getByRole('button', { name: /連立一次式の全ての解/u })).toBeVisible();
  await category.selectOption({ label: '統計' });
  await expect(category).toHaveAccessibleName('数学の分野');
  await expect(dialog.getByText('一致する項目がありません。', { exact: true })).toBeVisible();
  await category.selectOption({ label: '全ての分野' });
  await expect(dialog.getByRole('button', { name: /連立一次式の一意な解/u })).toBeVisible();
  await page.screenshot({ path: info.outputPath('math-linear-equations.png'), fullPage: true });
  await dialog.getByRole('button', { name: 'テキスト入力', exact: true }).click();
  await expect(dialog.locator('textarea')).toHaveValue(source);
  await apply.click(); await expect(dialog).toHaveCount(0);
  await expect(row.locator('.pcad-field').nth(1).locator('.pcad-field__message')).toHaveText('= 2');
  const saved = await savePart(page, info, 'math-linear-solution.pcad', app);
  expect(saved.parameters.find(parameter => parameter.name === '連立式の解')?.value).toMatchObject({ value: 2, source });
  await reopenPart(page, info, 'math-linear-solution.pcad', app);
  await page.getByRole('tab', { name: 'パラメータ', exact: true }).click();
  await row.getByRole('button', { name: '数式で入力', exact: true }).click();
  await expect(dialog.locator('textarea')).toHaveValue(source);
  await expect(dialog.locator('textarea')).toBeFocused();
  await page.keyboard.press('F1');
  await expect(page.locator('.pcad-help__article')).toContainText('連立一次式と行列から値を求める');
  await page.keyboard.press('Escape');
  await dialog.getByRole('button', { name: '取消', exact: true }).click();

  await page.getByRole('button', { name: '名前を付けた数値を足します', exact: true }).click();
  const factorRow = page.locator('.pcad-parameter').last();
  await factorRow.locator('.pcad-field').nth(0).locator('input').fill('直交方向の成分');
  await factorRow.locator('.pcad-field').nth(0).locator('input').press('Enter');
  await factorRow.getByRole('button', { name: '数式で入力', exact: true }).click();
  const factorSource = 'component(qrq([[3,0],[4,5]]),1,1)';
  await dialog.locator('textarea').fill(factorSource);
  await expect(dialog.locator('[role="status"]')).toHaveText('= 0.6');
  await dialog.getByRole('button', { name: '構造入力', exact: true }).click();
  await expect(dialog.locator('math-field')).toBeFocused();
  await dialog.locator('summary').filter({ hasText: '記号と演算を探す' }).click();
  await category.selectOption({ label: '線形代数' });
  await search.fill('QR分解');
  await expect(dialog.getByRole('button', { name: /QR分解の直交行列Q/u })).toBeVisible();
  await expect(dialog.getByRole('button', { name: /QR分解の上三角行列R/u })).toBeVisible();
  await page.screenshot({ path: info.outputPath('math-qr-component.png'), fullPage: true });
  await dialog.getByRole('button', { name: 'テキスト入力', exact: true }).click();
  await expect(dialog.locator('textarea')).toHaveValue(factorSource);
  await apply.click(); await expect(dialog).toHaveCount(0);
  await expect(factorRow.locator('.pcad-field').nth(1).locator('.pcad-field__message')).toHaveText('= 0.6');
  const factorFile = await savePart(page, info, 'math-qr-component.pcad', app);
  expect(factorFile.parameters.find(parameter => parameter.name === '直交方向の成分')?.value).toMatchObject({ value: 0.6, source: factorSource });
  await reopenPart(page, info, 'math-qr-component.pcad', app);
  await page.getByRole('tab', { name: 'パラメータ', exact: true }).click();
  await factorRow.getByRole('button', { name: '数式で入力', exact: true }).click();
  await expect(dialog.locator('textarea')).toHaveValue(factorSource);
  await expect(dialog.locator('textarea')).toBeFocused();
  await page.keyboard.press('F1');
  await expect(page.locator('.pcad-help__article')).toContainText('行列をQR分解する');
  await page.keyboard.press('Escape');
  await dialog.getByRole('button', { name: '取消', exact: true }).click();
}
