import { expect, type ElectronApplication, type Page, type TestInfo } from '@playwright/test';
import { savePart } from './scriptsFlow.js';
import { reopenPart } from './reopenPart.js';
import { waitForMathEditorText } from './mathEditorReady.js';
import { readRecomputeStats } from './recompute.js';
import { captureManualDetail } from './captureManualDetail.js';

export async function mathUnresolvedProblemFlow(page: Page, info: TestInfo, app?: ElectronApplication): Promise<void> {
  await page.setViewportSize({width:1440,height:1100});
  await page.getByRole('tab',{name:'パラメータ',exact:true}).click();
  const panel=page.getByRole('region',{name:'未解決の式',exact:true}), dialog=page.locator('.pcad-math-dialog');
  const source='pde([diff(u,t)=diff(u,x,x)],[x,t],[u],[[u,[0,t],3]])', changed=source.replace('[0,t],3','[0,t],7');
  const initial=await savePart(page,info,'unresolved-before.pcad',app);
  const before=await readRecomputeStats(page);
  await panel.getByRole('button',{name:'未解決の式を追加',exact:true}).click();
  await waitForMathEditorText(dialog);
  const input=dialog.locator('textarea'), apply=dialog.getByRole('button',{name:'式と条件を保存',exact:true});
  const result=dialog.locator('.pcad-math-editor__result[role="status"]');
  const complete=expect.configure({timeout:225_000});
  await input.fill('0'); await complete(result).toHaveText('= 0'); await expect(apply).toBeDisabled();
  await input.fill(source); await complete(apply).toBeEnabled();
  await expect(result).toContainText('値を決めるための条件や計算結果がまだ揃っていません。');
  await dialog.getByRole('button',{name:'構造入力',exact:true}).click();
  await expect(dialog.locator('math-field')).toBeFocused();
  await dialog.getByRole('button',{name:'テキスト入力',exact:true}).click();
  await expect(input).toHaveValue(source); await complete(apply).toBeEnabled();
  await captureManualDetail(page,info,{name:'math-unresolved-problem',dialog,script:new URL(import.meta.url),
    fixture:{source,expectedStatus:'unresolved',numericValue:null}});
  await apply.click(); await expect(dialog).toHaveCount(0);
  await expect(panel).toContainText(source); await expect(panel).toContainText('解はまだ得られていません。');
  expect((await readRecomputeStats(page)).requestedGeneration).toBe(before.requestedGeneration);
  const saved=await savePart(page,info,'unresolved-problem.pcad',app);
  expect(saved.unresolvedMathProblems).toHaveLength(1);
  expect(saved.unresolvedMathProblems?.[0]).toMatchObject({status:'unresolved',definition:{source}});
  expect(saved.parameters).toEqual(initial.parameters); expect(saved.sketches).toEqual(initial.sketches);
  expect(saved.solids).toEqual(initial.solids);
  await reopenPart(page,info,'unresolved-problem.pcad',app);
  await page.getByRole('tab',{name:'パラメータ',exact:true}).click();
  await expect(panel).toContainText(source);
  await panel.getByRole('button',{name:'式と条件を編集',exact:true}).click();
  await waitForMathEditorText(dialog); await expect(input).toHaveValue(source); await complete(apply).toBeEnabled();
  await page.keyboard.press('F1'); await expect(page.locator('.pcad-help__article')).toContainText('解けていない式と条件を保存する');
  await page.keyboard.press('Escape');
  await input.fill(changed); await complete(apply).toBeEnabled();
  await apply.click(); await expect(dialog).toHaveCount(0); await expect(panel).toContainText(changed);
  const edited=await savePart(page,info,'unresolved-edited.pcad',app);
  expect(edited.unresolvedMathProblems?.[0].definition.source).toBe(changed);
  await page.locator('canvas.pcad-viewport__canvas').focus(); await page.keyboard.press('Control+z');
  await expect(panel).toContainText(source);
  const undone=await savePart(page,info,'unresolved-undone.pcad',app);
  expect(undone.unresolvedMathProblems).toEqual(saved.unresolvedMathProblems);
  await panel.getByRole('button',{name:'式と条件を編集',exact:true}).click();
  await waitForMathEditorText(dialog); await input.fill('0'); await complete(result).toHaveText('= 0');
  await expect(apply).toBeDisabled(); await dialog.getByRole('button',{name:'取消',exact:true}).click();
  await expect(dialog).toHaveCount(0); await expect(panel).toContainText(source);
  await panel.getByRole('button',{name:'この式を削除',exact:true}).click();
  await expect(panel.locator('li')).toHaveCount(0);
  await page.locator('canvas.pcad-viewport__canvas').focus(); await page.keyboard.press('Control+z');
  await expect(panel).toContainText(source);
  const restored=await savePart(page,info,'unresolved-restored.pcad',app);
  expect(restored.unresolvedMathProblems).toEqual(saved.unresolvedMathProblems);
  expect(restored.parameters).toEqual(initial.parameters); expect(restored.sketches).toEqual(initial.sketches);
}
