import { expect, test, type Page } from '@playwright/test';
import { readFile, stat } from 'node:fs/promises';
import { readPcadFile } from '../../packages/io/src/index.js';
import { sheetFlatDrawingFlow } from './sheetDrawingFlow.js';
import { sheetExportFlow, verifySheetStepFiles } from './sheetExportFlow.js';
import { sheetHelpFlow } from './sheetHelpFlow.js';

import { tree, command, chooseSheet, volume, rectangleFace } from './sheetUiFlow.js';

const fileAction = (page: Page, name: string) => page.getByRole('group', { name: 'ファイル', exact: true }).getByRole('button', { name, exact: true });

test('P10 板金の指定線曲げを作成・取消・再展開・保存往復し、式編集とUndoを通す', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.addInitScript(() => {
    Object.defineProperty(globalThis, 'showSaveFilePicker', { configurable: true, value: undefined });
    Object.defineProperty(globalThis, 'showOpenFilePicker', { configurable: true, value: undefined });
  });
  await page.goto('/'); await rectangleFace(page);
  await tree(page, '面1').click(); await chooseSheet(page, '板金基板');
  const base = page.getByRole('form', { name: '板金基板', exact: true });
  await base.getByRole('textbox', { name: /^板厚/ }).fill('2');
  await base.getByRole('textbox', { name: /^内半径/ }).fill('3');
  await base.getByRole('button', { name: '作成', exact: true }).click();
  await expect(tree(page, '板金基板1')).toBeVisible(); await tree(page, '板金基板1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(3000, 5);
  await command(page, 'L'); await command(page, '0,15'); await command(page, '@50,0');
  await page.locator('.pcad-popover input.pcad-field__input').first().press('Escape');
  await expect(tree(page, '線分1')).toBeVisible(); await tree(page, '線分1').click();
  await chooseSheet(page, '指定線で曲げる');
  const form = page.getByRole('form', { name: '指定線で曲げる', exact: true });
  await form.getByRole('textbox', { name: /^曲げ角/ }).fill('180');
  await form.getByRole('button', { name: '作成', exact: true }).click();
  await expect(form.getByRole('textbox', { name: /^曲げ角/ })).toHaveAttribute('aria-invalid', 'true');
  await form.getByRole('textbox', { name: /^曲げ角/ }).fill('-45*2');
  await form.getByRole('combobox', { name: '固定する側', exact: true }).selectOption('left');
  await sheetHelpFlow(page, '指定線で板を曲げる・曲げリリーフを作る', testInfo, 'sheet-line-help.png');
  await form.getByRole('button', { name: 'プレビュー', exact: true }).click();
  await expect(form.getByRole('status')).toContainText('体積:', { timeout: 60_000 });
  await page.screenshot({ path: testInfo.outputPath('sheet-line-preview.png') });
  await expect(tree(page, '指定線で曲げる1')).toHaveCount(0);
  await form.getByRole('button', { name: '取消', exact: true }).click();
  await tree(page, '板金基板1').click(); await expect.poll(() => volume(page)).toBeCloseTo(3000, 5);
  await chooseSheet(page, '指定線で曲げる');
  await form.getByRole('textbox', { name: /^曲げ角/ }).fill('-45*2');
  await form.getByRole('combobox', { name: '固定する側', exact: true }).selectOption('left');
  await form.getByRole('button', { name: '作成', exact: true }).click();
  await expect(tree(page, '指定線で曲げる1')).toBeVisible(); await tree(page, '指定線で曲げる1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(3000 + 10 * Math.PI, 4);
  await page.screenshot({ path: testInfo.outputPath('sheet-line-created.png') });
  await chooseSheet(page, '板金の展開');
  const unfold = page.getByRole('form', { name: '板金の展開', exact: true });
  await unfold.getByRole('combobox', { name: '固定面', exact: true }).selectOption({ label: 'パネル 2' });
  await unfold.getByRole('button', { name: '展開を表示', exact: true }).click();
  await expect(unfold.getByRole('status')).toContainText('展開を表示中', { timeout: 60_000 });
  expect(Number((await unfold.getByRole('status').textContent())?.match(/体積: ([\d.]+)/u)?.[1])).toBeCloseTo(3000, 4);
  await page.screenshot({ path: testInfo.outputPath('sheet-line-flat.png') });
  const downloaded = page.waitForEvent('download'); await fileAction(page, '保存').click();
  const savedPath = testInfo.outputPath('sheet-line.pcad'); await (await downloaded).saveAs(savedPath);
  const decoded = readPcadFile(await readFile(savedPath)); if (!decoded.ok) throw new Error(decoded.error.message);
  expect(decoded.document.solids[1]).toMatchObject({ kind: 'sheetBend', fixedSide: 'left', angle: { source: '-45*2', value: -90 } });
  await fileAction(page, '新規').click();
  const chooser = page.waitForEvent('filechooser'); await fileAction(page, '開く').click(); await (await chooser).setFiles(savedPath);
  await expect(tree(page, '指定線で曲げる1')).toBeVisible(); await tree(page, '指定線で曲げる1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(3000 + 10 * Math.PI, 4);
  const angle = page.locator('.pcad-panel--right .pcad-field').filter({ has: page.locator('.pcad-field__label', { hasText: /^曲げ角$/ }) }).locator('input');
  await expect(angle).toHaveValue('-45*2'); await angle.fill('-45'); await angle.press('Tab');
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(3000 + 5 * Math.PI, 4);
  await page.locator('canvas.pcad-viewport__canvas').press('Control+z'); await expect(angle).toHaveValue('-45*2');
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(3000 + 10 * Math.PI, 4);
  expect(errors).toEqual([]);
});

test('P10 板金基板とフランジを画面で作り、保存往復・式編集・Undoを通す', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  // ダウンロードとinput[type=file]の経路を明示する。ネイティブpickerはElectronの別検査で通す。
  await page.addInitScript(() => {
    Object.defineProperty(globalThis, 'showSaveFilePicker', { configurable: true, value: undefined });
    Object.defineProperty(globalThis, 'showOpenFilePicker', { configurable: true, value: undefined });
  });
  await page.goto('/'); await rectangleFace(page);
  await tree(page, '面1').click(); await chooseSheet(page, '板金基板');
  const base = page.getByRole('form', { name: '板金基板', exact: true });
  await base.getByRole('textbox', { name: /^板厚/ }).fill('2mm');
  await base.getByRole('textbox', { name: /^内半径/ }).fill('3mm');
  await base.getByRole('textbox', { name: /^K係数/ }).fill('0.4');
  // 説明書には操作可能な状態を撮る。初回OCCT読込中の画面を採用しない。
  await expect(base.getByRole('button', { name: '作成', exact: true })).toBeEnabled({ timeout: 60_000 });
  await page.screenshot({ path: testInfo.outputPath('sheet-base-input.png') });
  await sheetHelpFlow(page, '板金の基板と曲げ条件を作る', testInfo, 'sheet-base-help.png');
  await base.getByRole('button', { name: '作成', exact: true }).click();
  await expect(tree(page, '板金基板1')).toBeVisible(); await tree(page, '板金基板1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(3000, 5);
  await chooseSheet(page, 'フランジ');
  const flange = page.getByRole('form', { name: 'フランジ', exact: true });
  await flange.getByRole('checkbox', { name: 'パネル 1 / 縁 1', exact: true }).check();
  await flange.getByRole('textbox', { name: /^フランジの長さ/ }).fill('0');
  await flange.getByRole('button', { name: '作成', exact: true }).click();
  await expect(flange.getByRole('textbox', { name: /^フランジの長さ/ })).toHaveAttribute('aria-invalid', 'true');
  await expect(tree(page, 'フランジ1')).toHaveCount(0);
  await flange.getByRole('textbox', { name: /^フランジの長さ/ }).fill('10*2');
  const converted = flange.locator('dl[aria-label="曲げ寸法の換算"]');
  const straight = converted.locator('dt').filter({ hasText: /^接線からの直線長$/ }).locator('xpath=following-sibling::dd[1]');
  await expect(converted).toContainText('5.96902604182 mm');
  await flange.getByRole('combobox', { name: '長さの基準', exact: true }).selectOption('outer');
  await expect(straight).toHaveText('15 mm');
  await flange.getByRole('combobox', { name: '長さの基準', exact: true }).selectOption('inner');
  await expect(straight).toHaveText('17 mm');
  await flange.getByRole('combobox', { name: '長さの基準', exact: true }).selectOption('tangent');
  await expect(straight).toHaveText('20 mm');
  await sheetHelpFlow(page, '板金の縁からフランジを作る', testInfo, 'sheet-flange-help.png');
  await flange.getByRole('button', { name: 'プレビュー', exact: true }).click();
  await expect(flange.getByRole('status')).toContainText('体積:', { timeout: 60_000 });
  await expect(tree(page, 'フランジ1')).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath('sheet-flange-preview.png') });
  await flange.getByRole('button', { name: '作成', exact: true }).click();
  await expect(tree(page, 'フランジ1')).toBeVisible(); await tree(page, 'フランジ1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(5000 + 200 * Math.PI, 4);
  await page.screenshot({ path: testInfo.outputPath('sheet-flange-created.png') });

  await chooseSheet(page, '板金の展開');
  const unfold = page.getByRole('form', { name: '板金の展開', exact: true });
  await unfold.getByRole('combobox', { name: '固定面', exact: true }).selectOption({ label: 'パネル 2' });
  const fixedPanelId = await unfold.getByRole('combobox', { name: '固定面', exact: true }).inputValue();
  await unfold.getByRole('button', { name: '展開を表示', exact: true }).click();
  await expect(unfold.getByRole('status')).toContainText('展開を表示中', { timeout: 60_000 });
  const flatVolume = Number((await unfold.getByRole('status').textContent())?.match(/体積: ([\d.]+)/u)?.[1]);
  expect(flatVolume).toBeCloseTo(5000 + 190 * Math.PI, 4);
  await page.screenshot({ path: testInfo.outputPath('sheet-unfold.png') });
  await unfold.getByRole('button', { name: '折曲げを表示', exact: true }).click();
  await expect(unfold.getByRole('status')).toHaveCount(0);
  await unfold.getByRole('button', { name: '展開を表示', exact: true }).click();
  await expect(unfold.getByRole('status')).toContainText('展開を表示中', { timeout: 60_000 });

  const downloaded = page.waitForEvent('download'); await fileAction(page, '保存').click();
  const savedPath = testInfo.outputPath('sheet-flange.pcad'); await (await downloaded).saveAs(savedPath);
  // 一時通知はhover案内で変わるため、保存した実ファイルと後続の読込結果を検査する。
  expect((await stat(savedPath)).size).toBeGreaterThan(0);
  const decoded = readPcadFile(await readFile(savedPath)); if (!decoded.ok) throw new Error(decoded.error.message);
  expect(decoded.document.sheetUnfolds).toEqual([{ sourceFeatureId: decoded.document.solids[1].id, fixedPanelId, seamConnectionIds: [] }]);
  expect(JSON.stringify(decoded.document.sheetUnfolds)).not.toMatch(/mesh|displayMode|flatCoordinates/u);
  await fileAction(page, '新規').click(); await expect(tree(page, 'フランジ1')).toHaveCount(0);
  const chooser = page.waitForEvent('filechooser'); await fileAction(page, '開く').click(); await (await chooser).setFiles(savedPath);
  await expect(tree(page, 'フランジ1')).toBeVisible(); await tree(page, 'フランジ1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(5000 + 200 * Math.PI, 4);
  await chooseSheet(page, '板金の展開');
  await expect(unfold.getByRole('combobox', { name: '固定面', exact: true })).toHaveValue(fixedPanelId);
  await expect(unfold.getByRole('status')).toHaveCount(0);
  await unfold.getByRole('button', { name: '閉じる', exact: true }).click();
  await tree(page, 'フランジ1').click();
  const length = page.locator('.pcad-panel--right .pcad-field').filter({ has: page.locator('.pcad-field__label', { hasText: /^フランジの長さ$/ }) }).locator('input');
  await expect(length).toHaveValue('10*2'); await length.fill('25'); await length.press('Tab');
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(5500 + 200 * Math.PI, 4);
  await page.locator('canvas.pcad-viewport__canvas').press('Control+z');
  await expect(length).toHaveValue('10*2');
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(5000 + 200 * Math.PI, 4);
  expect(errors).toEqual([]);
});

test('P10 板金の曲げ帯をまたぐ長穴リリーフを作成し、展開・保存・再編集・Undoする', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.addInitScript(() => {
    Object.defineProperty(globalThis, 'showSaveFilePicker', { configurable: true, value: undefined });
    Object.defineProperty(globalThis, 'showOpenFilePicker', { configurable: true, value: undefined });
  });
  await page.goto('/'); await rectangleFace(page);
  await tree(page, '面1').click(); await chooseSheet(page, '板金基板');
  const base = page.getByRole('form', { name: '板金基板', exact: true });
  await base.getByRole('textbox', { name: /^板厚/ }).fill('2');
  await base.getByRole('textbox', { name: /^内半径/ }).fill('3');
  await base.getByRole('button', { name: '作成', exact: true }).click();
  await expect(tree(page, '板金基板1')).toBeVisible(); await tree(page, '板金基板1').click();
  await chooseSheet(page, 'フランジ');
  const flange = page.getByRole('form', { name: 'フランジ', exact: true });
  await flange.getByRole('checkbox', { name: 'パネル 1 / 縁 1', exact: true }).check();
  await flange.getByRole('button', { name: '作成', exact: true }).click();
  await expect(tree(page, 'フランジ1')).toBeVisible(); await tree(page, 'フランジ1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(5000 + 200 * Math.PI, 4);
  await chooseSheet(page, '曲げリリーフ');
  const relief = page.getByRole('form', { name: '曲げリリーフ', exact: true });
  await relief.getByRole('combobox', { name: '切欠きの入口の縁', exact: true }).selectOption({ label: 'パネル 1 / 縁 1' });
  await relief.getByRole('combobox', { name: '切欠きの形', exact: true }).selectOption('slot');
  await relief.getByRole('textbox', { name: /^切欠きの幅/ }).fill('2*2');
  await relief.getByRole('textbox', { name: /^切欠きの深さ/ }).fill('1');
  await relief.getByRole('button', { name: '作成', exact: true }).click();
  await expect(relief.getByRole('alert')).toContainText('幅の半分');
  await expect(tree(page, '曲げリリーフ1')).toHaveCount(0);
  await relief.getByRole('textbox', { name: /^切欠きの深さ/ }).fill('5');
  await relief.getByRole('button', { name: 'プレビュー', exact: true }).click();
  await expect(relief.getByRole('status')).toContainText('体積:', { timeout: 60_000 });
  await page.screenshot({ path: testInfo.outputPath('sheet-relief-preview.png') });
  await relief.getByRole('button', { name: '作成', exact: true }).click();
  await expect(tree(page, '曲げリリーフ1')).toBeVisible(); await tree(page, '曲げリリーフ1').click();
  const foldedVolume = 5000 + 200 * Math.PI - 78 * (6 + Math.PI) / 19;
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(foldedVolume, 4);
  await page.screenshot({ path: testInfo.outputPath('sheet-relief-created.png') });
  await chooseSheet(page, '板金の展開');
  const unfold = page.getByRole('form', { name: '板金の展開', exact: true });
  await unfold.getByRole('combobox', { name: '固定面', exact: true }).selectOption({ label: 'パネル 2' });
  await unfold.getByRole('button', { name: '展開を表示', exact: true }).click();
  await expect(unfold.getByRole('status')).toContainText('展開を表示中', { timeout: 60_000 });
  expect(Number((await unfold.getByRole('status').textContent())?.match(/体積: ([\d.]+)/u)?.[1])).toBeCloseTo(4976 + 186 * Math.PI, 4);
  await page.screenshot({ path: testInfo.outputPath('sheet-relief-flat.png') });
  const downloaded = page.waitForEvent('download'); await fileAction(page, '保存').click();
  const savedPath = testInfo.outputPath('sheet-relief.pcad'); await (await downloaded).saveAs(savedPath);
  const decoded = readPcadFile(await readFile(savedPath)); if (!decoded.ok) throw new Error(decoded.error.message);
  expect(decoded.document.solids[2]).toMatchObject({ kind: 'sheetRelief', shape: 'slot', position: { value: 0 }, width: { source: '2*2', value: 4 }, depth: { value: 5 } });
  await fileAction(page, '新規').click();
  const chooser = page.waitForEvent('filechooser'); await fileAction(page, '開く').click(); await (await chooser).setFiles(savedPath);
  await expect(tree(page, '曲げリリーフ1')).toBeVisible(); await tree(page, '曲げリリーフ1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(foldedVolume, 4);
  const depth = page.locator('.pcad-panel--right .pcad-field').filter({ has: page.locator('.pcad-field__label', { hasText: /^切欠きの深さ$/ }) }).locator('input');
  await expect(depth).toHaveValue('5'); await depth.fill('6'); await depth.press('Tab');
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(foldedVolume - 312 / 38, 4);
  await page.locator('canvas.pcad-viewport__canvas').press('Control+z'); await expect(depth).toHaveValue('5');
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(foldedVolume, 4);
  // 元のフランジはリリーフへ消費されている。編集は元IDのまま後続まで再計算する。
  const editButton = page.locator('.pcad-panel--right').getByRole('button', { name: '板金の参照と条件を編集', exact: true });
  await tree(page, 'フランジ1').click(); await editButton.click();
  const editingFlange = page.getByRole('form', { name: 'フランジ', exact: true });
  await expect(editingFlange.getByRole('checkbox', { name: 'パネル 1 / 縁 1', exact: true })).toBeChecked();
  await editingFlange.getByRole('checkbox', { name: 'この曲げの内半径を指定', exact: true }).check();
  await editingFlange.getByRole('checkbox', { name: 'この曲げのK係数を指定', exact: true }).check();
  await editingFlange.getByRole('textbox', { name: /^内半径/ }).fill('4');
  await editingFlange.getByRole('textbox', { name: /^K係数/ }).fill('0.3');
  await editingFlange.getByRole('button', { name: 'プレビュー', exact: true }).click();
  await expect(editingFlange.getByRole('status')).toContainText('合計体積:', { timeout: 60_000 });
  await page.screenshot({ path: testInfo.outputPath('sheet-edit-flange-preview.png') });
  await editingFlange.getByRole('button', { name: '変更を適用', exact: true }).click();
  await expect(editingFlange).toHaveCount(0); await tree(page, '曲げリリーフ1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(5000 + 250 * Math.PI - 96 * (6 + Math.PI) / 23, 4);
  await expect(tree(page, 'フランジ2')).toHaveCount(0); await expect(tree(page, '曲げリリーフ2')).toHaveCount(0);
  await tree(page, 'フランジ1').click(); await editButton.click();
  await expect(editingFlange.getByRole('textbox', { name: /^内半径/ })).toHaveValue('4');
  await editingFlange.getByRole('checkbox', { name: 'この曲げの内半径を指定', exact: true }).uncheck();
  await editingFlange.getByRole('checkbox', { name: 'この曲げのK係数を指定', exact: true }).uncheck();
  await expect(editingFlange.getByRole('textbox', { name: /^内半径/ })).toHaveCount(0);
  await editingFlange.getByRole('button', { name: '変更を適用', exact: true }).click();
  await expect(editingFlange).toHaveCount(0); await tree(page, '曲げリリーフ1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(foldedVolume, 4);
  await tree(page, 'フランジ1').click(); await editButton.click();
  await editingFlange.getByRole('checkbox', { name: 'パネル 1 / 縁 1', exact: true }).uncheck();
  await editingFlange.getByRole('checkbox', { name: 'パネル 1 / 縁 3', exact: true }).check();
  await editingFlange.getByRole('button', { name: '変更を適用', exact: true }).click();
  await expect(editingFlange).toHaveCount(0); await tree(page, '曲げリリーフ1').click();
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(4988 + 198 * Math.PI, 4);
  await page.screenshot({ path: testInfo.outputPath('sheet-edit-reference.png') });
  await page.locator('canvas.pcad-viewport__canvas').press('Control+z');
  await expect.poll(() => volume(page), { timeout: 60_000 }).toBeCloseTo(foldedVolume, 4);
  await chooseSheet(page, '板金の展開');
  await unfold.getByRole('button', { name: '展開を表示', exact: true }).click();
  await expect(unfold.getByRole('status')).toContainText('展開を表示中', { timeout: 60_000 });
  const exports = await sheetExportFlow(page, testInfo);
  await sheetFlatDrawingFlow(page, testInfo, savedPath);
  await verifySheetStepFiles(page, savedPath, exports);

  expect(errors).toEqual([]);
});
