import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';
import { readDrawingBundle } from '../../packages/io/src/index.js';
import { sheetHolePartFile } from './sheetHoleFixture.js';
import { sheetDrawingVectorFlow } from './sheetDrawingExportFlow.js';
import { sheetHelpFlow } from './sheetHelpFlow.js';
import { openSheetPart } from './sheetPartFlow.js';

test('P10 板金の展開穴表が固定面の座標を使い、基準点・元の穴編集・保存往復に追従する', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.addInitScript(() => {
    for (const name of ['showOpenFilePicker', 'showSaveFilePicker']) Object.defineProperty(globalThis, name, { configurable: true, value: undefined });
  });
  await page.goto('/');
  await openSheetPart(page, '二つの穴.pcad', sheetHolePartFile());
  const tree = page.locator('.pcad-panel--left').getByRole('button', { name: 'フランジ1', exact: true });
  await expect(tree).toBeVisible({ timeout: 60_000 }); await tree.click();
  await page.locator('.pcad-toolbar').getByRole('button', { name: /^板金/ }).first().click();
  await page.locator('.pcad-menu__panel[aria-label="板金"]').getByRole('button', { name: '板金の展開', exact: true }).click();
  const unfold = page.getByRole('form', { name: '板金の展開', exact: true });
  await unfold.getByRole('combobox', { name: '固定面', exact: true }).selectOption({ label: 'パネル 2' });
  await unfold.getByRole('button', { name: '展開を表示', exact: true }).click();
  await expect(unfold.getByRole('status')).toContainText('展開を表示中', { timeout: 60_000 });
  expect(Number((await unfold.getByRole('status').textContent())?.match(/体積: ([\d.]+)/u)?.[1])).toBeCloseTo(5000 + 174 * Math.PI, 4);
  await unfold.getByRole('button', { name: '展開から図面を作成', exact: true }).click();
  await expect(page.locator('.pcad-drawing-svg [aria-label="上 90° R3"]')).toHaveCount(1, { timeout: 60_000 });
  const section = page.locator('.pcad-drawing-property-section[data-property-kind="table"]');
  if (await section.getAttribute('open') === null) await section.locator(':scope > summary').click();
  const editor = page.locator('.pcad-drawing-table-editor');
  await editor.getByLabel('表と部品番号', { exact: true }).selectOption('hole');
  await editor.getByLabel('穴の座標を測る図', { exact: true }).selectOption('view-1');
  const datumX = editor.getByLabel('穴座標の基準点（展開面のmm） X', { exact: true });
  await expect(datumX).toHaveValue('0');
  await datumX.focus();
  await sheetHelpFlow(page, '板金を展開し、穴表・図面・加工用ファイルを作る', testInfo, 'sheet-flat-help.png');
  await editor.getByRole('button', { name: '表を配置', exact: true }).click();
  const table = page.locator('.pcad-drawing-svg [data-owner-id="table-1"]');
  for (const symbol of ['A1','A2']) await expect(table.locator(`[aria-label="${symbol}"]`)).toHaveCount(2, { timeout: 60_000 });
  // フランジを固定するとXは50-X、Yは-(元のY+BA)。折曲げの10/8や35/12を流用しない。
  for (const text of ['15','40','-17.969','-13.969']) await expect(table.locator(`[aria-label="${text}"]`)).toHaveCount(1);
  await expect(table.locator('[aria-label="φ4"]')).toHaveCount(2);
  await datumX.fill('5'); await editor.getByRole('button', { name: '表を更新', exact: true }).click();
  for (const text of ['10','35']) await expect(table.locator(`[aria-label="${text}"]`)).toHaveCount(1);
  await page.getByRole('button', { name: '元に戻す', exact: true }).click(); await expect(table.locator('[aria-label="40"]')).toHaveCount(1);
  await page.getByRole('button', { name: 'やり直す', exact: true }).click(); await expect(table.locator('[aria-label="35"]')).toHaveCount(1);
  await page.screenshot({ path: testInfo.outputPath('sheet-flat-hole-table.png') });
  await page.locator('.pcad-toolbar').getByRole('button', { name: /^ファイル/ }).first().click();
  const refreshing = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: '元の部品・組立を取り込み直す', exact: true }).click();
  await (await refreshing).setFiles({ name: '穴位置変更.pcad', mimeType: 'application/zip', buffer: Buffer.from(sheetHolePartFile(12)) });
  await expect(table.locator('[aria-label="33"]')).toHaveCount(1, { timeout: 60_000 });
  await expect(table.locator('[aria-label="35"]')).toHaveCount(0);
  const saving = page.waitForEvent('download'); await page.keyboard.press('Control+s');
  const path = testInfo.outputPath('sheet-hole-table.pcadd'); await (await saving).saveAs(path);
  const saved = await readDrawingBundle(await readFile(path)); if (!saved.ok) throw new Error(saved.error.message);
  expect(saved.document.tables[0]).toMatchObject({ kind: 'hole', options: { datumX: 5, viewId: 'view-1' } });
  await page.reload(); const reopening = page.waitForEvent('filechooser'); await page.getByRole('button', { name: '開く', exact: true }).click();
  await (await reopening).setFiles(path);
  await expect(table.locator('[aria-label="33"]')).toHaveCount(1, { timeout: 60_000 });
  await expect(table.locator('[aria-label="10"]')).toHaveCount(1);
  await expect(table.locator('[aria-label="A2"]')).toHaveCount(2);
  await page.screenshot({ path: testInfo.outputPath('sheet-flat-hole-table-reopened.png') });
  await sheetDrawingVectorFlow(page, testInfo);
  const svg = await readFile(testInfo.outputPath('sheet-bend-instructions.svg'), 'utf8');
  expect(svg).toContain('aria-label="33"'); expect(svg).toContain('aria-label="φ4"');
  expect(errors).toEqual([]);
});
