import { expect, type Page, type TestInfo } from '@playwright/test';
import { beginRecompute, readRecomputeStats, waitForRecompute } from './recompute.js';
import { chooseToolMenuItem } from './assemblyTestSupport.js';
import { sheetHelpFlow } from './sheetHelpFlow.js';

async function openStrength(page: Page): Promise<void> {
  await page.getByRole('button', { name: /^見た目/u }).click();
  await page.getByRole('group', { name: '見た目', exact: true }).getByRole('button', { name: '簡易強度計算', exact: true }).click();
}
export async function strengthFlow(page: Page, info: TestInfo): Promise<void> {
  await page.setViewportSize({ width: 1440, height: 900 });
  await expect(page.getByRole('button', { name: '開く', exact: true })).toBeVisible();
  await expect.poll(() => page.evaluate(() => typeof window.pcadRecomputeStats)).toBe('function');
  const before = await readRecomputeStats(page);
  await openStrength(page);
  const panel = page.getByRole('form', { name: '簡易強度計算', exact: true });
  const result = (name: string) => panel.locator(`[data-strength-result="${name}"]`);
  await expect(panel.getByLabel('幅 b', { exact: true })).toHaveValue('10mm');
  await page.screenshot({ path: info.outputPath('strength-beam-input.png') });
  await panel.getByRole('button', { name: '計算する', exact: true }).click();
  await expect(result('stress')).toHaveText('6');
  await expect(result('deflection')).toHaveText('0.0195121951');
  await expect(result('actualSafetyFactor')).toHaveText('40.8333333');
  await expect(result('reserveFactor')).toHaveText('13.6111111');
  await result('reserveFactor').scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('strength-beam-results.png') });
  await panel.getByText('公式と数値の代入（N・mm・MPa・rad）', { exact: true }).click();
  await expect(panel.getByText('σ = 6*M/(b*h^2)', { exact: false })).toContainText('6*(1000)/((10)*(10)^2) = 6');
  await panel.getByLabel('力 F（N）', { exact: true }).fill('1kN');
  await expect(result('stress')).toHaveText('6');
  await expect(panel.getByText(/^前回の計算結果です/u)).toBeVisible();
  await panel.getByRole('button', { name: '計算し直す', exact: true }).click();
  await expect(result('stress')).toHaveText('600');
  await expect(panel.getByText(/^指定安全率に達していません/u)).toBeVisible();
  await panel.getByLabel('支え方と荷重位置', { exact: true }).selectOption('simply-supported');
  await panel.getByLabel('力 F（N）', { exact: true }).fill('10N');
  await panel.getByRole('button', { name: '計算し直す', exact: true }).click();
  await expect(result('stress')).toHaveText('1.5');
  await panel.getByLabel('素材の板厚（断面高さとは別）', { exact: true }).fill('20mm');
  await expect(panel.getByRole('button', { name: '計算し直す', exact: true })).toBeDisabled();
  await expect(panel.getByRole('alert')).toContainText('適用範囲外');
  await panel.getByLabel('材料と製品条件', { exact: true }).selectOption('ss400-plate-16-40');
  await expect(panel.getByLabel('降伏点・0.2%耐力 σy（MPa）', { exact: true })).toHaveValue('235');
  await panel.getByLabel('計算の種類', { exact: true }).selectOption('shaft');
  await panel.getByLabel('材料と製品条件', { exact: true }).selectOption('sus304-solution-cold-rolled');
  await expect(panel.getByLabel('横弾性係数 G（MPa）', { exact: true })).toHaveValue('');
  await expect(panel.getByRole('button', { name: '計算し直す', exact: true })).toBeDisabled();
  await panel.getByLabel('横弾性係数 G（MPa）', { exact: true }).fill('70000');
  await panel.getByRole('button', { name: '計算し直す', exact: true }).click();
  await expect.poll(async () => Number(await result('shearStress').textContent())).toBeCloseTo(100000 / (Math.PI * 20 ** 3 / 16), 6);
  await expect(panel.getByText(/^判定: ミーゼス相当応力/u)).toBeVisible();
  await result('twist').scrollIntoViewIfNeeded(); await page.screenshot({ path: info.outputPath('strength-shaft-results.png') });
  await panel.getByLabel('計算の種類', { exact: true }).selectOption('bolt');
  await expect(panel.getByText('有効断面積 As（mm²）: 58', { exact: true })).toBeVisible();
  await panel.getByLabel('力 F（N）', { exact: true }).fill('10kN');
  await panel.getByRole('button', { name: '計算し直す', exact: true }).click();
  await expect.poll(async () => Number(await result('stress').textContent())).toBeCloseTo(10000 / 58, 6);
  await panel.getByLabel('ねじの呼び', { exact: true }).selectOption('M52');
  await panel.getByLabel('ピッチの系列', { exact: true }).selectOption('fine');
  await expect(panel.getByRole('button', { name: '計算し直す', exact: true })).toBeDisabled();
  await expect(panel.getByRole('alert')).toContainText('公称断面積は未確認');
  await panel.getByLabel('有効断面積の求め方', { exact: true }).selectOption('approximation');
  await panel.getByRole('button', { name: '計算し直す', exact: true }).click();
  await expect.poll(async () => Number(await result('stress').textContent())).toBeCloseTo(10000 / (Math.PI / 4 * (52 - 0.9382 * 3) ** 2), 7);
  await panel.getByLabel('有効断面積の求め方', { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('strength-bolt-input.png') });
  await panel.getByLabel('力 F（N）', { exact: true }).fill('1/0');
  await expect(panel.getByLabel('力 F（N）', { exact: true })).toHaveAttribute('aria-invalid', 'true');
  await expect(panel.getByRole('button', { name: '計算し直す', exact: true })).toBeDisabled();
  await panel.getByLabel('力 F（N）', { exact: true }).focus();
  await sheetHelpFlow(page, '梁・軸・ボルトの簡易強度計算', info, 'strength-help.png');
  await panel.getByLabel('力 F（N）', { exact: true }).press('Escape'); await expect(panel).toHaveCount(0);
  expect(await readRecomputeStats(page)).toEqual(before);
  await openStrength(page); await expect(result('stress')).toHaveCount(0);
  await panel.getByRole('button', { name: '計算する', exact: true }).click(); await expect(result('stress')).toHaveText('6');
  await page.getByRole('group', { name: 'ファイル', exact: true }).getByRole('button', { name: '新規', exact: true }).click();
  await expect(panel).toHaveCount(0);
  const assemblyToken = await beginRecompute(page);
  await chooseToolMenuItem(page, 'ファイルのほかの操作', '新しいアセンブリ');
  await waitForRecompute(page, assemblyToken);
  await expect(page.locator('.pcad-shell')).toHaveAttribute('data-document-kind', 'assembly');
  const assemblyBefore = await readRecomputeStats(page);
  await openStrength(page);
  await expect(panel.getByLabel('幅 b', { exact: true })).toHaveValue('10mm');
  await panel.getByLabel('力 F（N）', { exact: true }).fill('30N');
  await panel.getByRole('button', { name: '計算する', exact: true }).click();
  await expect(result('stress')).toHaveText('18');
  expect(await readRecomputeStats(page)).toEqual(assemblyBefore);
  await panel.getByRole('button', { name: '計算を閉じる', exact: true }).click();
  await expect(panel).toHaveCount(0);
  await expect(page.locator('.pcad-shell')).toHaveAttribute('data-document-kind', 'assembly');
}
