import type { MathPaletteExample } from './mathPaletteGroups.js';

/**
 * mathPaletteSetsLogic.ts の項目の実例（公開パレットの受入）。selection は #0、slots は #? へ出現順に入れる。
 * mathPaletteExamples.test.ts が構造入力と同じ経路で実計算し、期待した数値・型と目録の欄を照合する。
 * 表示順は mathPaletteExamples.ts の MATH_PALETTE_DISPLAY_ORDER（新しい項目は既存の項目の後ろ）。
 */
export const MATH_PALETTE_SETS_LOGIC_EXAMPLES: readonly MathPaletteExample[] = [
  { id: 'mapping', selection: '2x+1', slots: ['x', String.raw`\mathbb{R}`, String.raw`\mathbb{R}`], expected: 'function', exact: true },
  { id: 'mapping-value', selection: String.raw`\operatorname{mapping}(2x+1,x,\mathbb{R},\mathbb{R})`, slots: ['4'], expected: 9, exact: true },
  { id: 'mapping-compose', selection: String.raw`\operatorname{mapping}(x+1,x,\mathbb{R},\mathbb{R})`, slots: [String.raw`\operatorname{mapping}(2x,x,\mathbb{R},\mathbb{R})`], expected: 'function', exact: true },
  { id: 'mapping-inverse', selection: String.raw`\operatorname{mapping}(2x+1,x,\mathbb{R},\mathbb{R})`, slots: [], expected: 'function', exact: true },
  { id: 'mapping-image', selection: String.raw`\operatorname{mapping}(x^2,x,\mathbb{R},\mathbb{R})`, slots: [String.raw`\operatorname{set}(-2,3)`], expected: 'set', exact: true },
  { id: 'mapping-preimage', selection: String.raw`\operatorname{mapping}(x^2,x,\mathbb{R},\mathbb{R})`, slots: [String.raw`\operatorname{set}(4)`], expected: 'set', exact: true },
  { id: 'set-supremum', selection: String.raw`\operatorname{interval}(\operatorname{open}(0),\operatorname{open}(1))`, slots: [], expected: 1, exact: true },
  { id: 'set-infimum', selection: String.raw`\operatorname{interval}(\operatorname{open}(0),\operatorname{open}(1))`, slots: [], expected: 0, exact: true },
  { id: 'set-maximum', selection: String.raw`\operatorname{set}(1,3,2)`, slots: [], expected: 3, exact: true },
  { id: 'set-minimum', selection: String.raw`\operatorname{set}(1,3,2)`, slots: [], expected: 1, exact: true },
  { id: 'solve-ode', selection: '[\\operatorname{diff}(y,x)=2]', slots: ['x', '[y]', '[[y,0,3]]'], expected: 'ode-solutions', exact: true },
  { id: 'ode-value', selection: '\\operatorname{odesolve}([\\operatorname{diff}(y,x)=2],x,[y],[[y,0,3]])', slots: ['1', '[]', '4'], expected: 'vector', exact: true },
  { id: 'numerical-roots', selection: 'x^2-2', slots: ['x', '-2', '2', '0.000001'], expected: 'root-intervals' },
  { id: 'root-interval', selection: '\\operatorname{numericroots}(x^2-2,x,0,2,0.000001)', slots: ['1'], expected: 'vector' },
  { id: 'solve-system', selection: '[x+y=2,x-y=0]', slots: ['[x,y]', '\\mathbb{R}'], expected: 'equation-system', exact: true },
  { id: 'system-solution', selection: '\\operatorname{solvesystem}([x+y=2],[x,y],\\mathbb{R})', slots: ['1', '[3]'], expected: 'vector', exact: true },
  { id: 'solve-equation', selection: 'x^2=1', slots: ['x', String.raw`\mathbb{R}`], expected: 'set', exact: true },
  { id: 'polynomial-roots', selection: '(x-1)^2*(x+2)', slots: ['x', String.raw`\mathbb{C}`], expected: 'matrix', exact: true },
  { id: 'solution-value', selection: String.raw`\operatorname{solve}\left(x^2=4,x,\mathbb{R}\right)`, slots: ['2'], expected: 2, exact: true },
  { id: "fourier-transform", selection: String.raw`\exp\left(-x^2\right)`, slots: ["x", "k"], expected: 'transform', exact: true },
  { id: "inverse-fourier-transform", selection: String.raw`\exp\left(-\pi x^2\right)`, slots: ["x", "t"], expected: 'transform', exact: true },
  { id: "laplace-transform", selection: String.raw`\exp\left(-x\right)`, slots: ["x", "s"], expected: 'transform', exact: true },
  { id: "inverse-laplace-transform", selection: "1/(x+1)", slots: ["x", "t"], expected: 'transform', exact: true },
  { id: "z-transform", selection: "(1/2)^n", slots: ["n", "z"], expected: 'transform', exact: true },
  { id: "transform-value", selection: String.raw`\operatorname{laplace}\left(\exp\left(-x\right),x,s\right)`, slots: ["1"], expected: 0.5, exact: true },
  {"id": "event-probability", "selection": "x>0", "slots": ["[x]", "\\operatorname{normaldistribution}(0,1)"], "expected": 0.5, "exact": true},
  {"id": "given-probability", "selection": "x>2", "slots": ["x>1", "[x]", "\\operatorname{uniformdistribution}(0,4)"], "expected": 0.6666666666666666, "exact": true},
  {"id": "random-expectation", "selection": "x", "slots": ["[x]", "\\operatorname{normaldistribution}(3,2)"], "expected": 3, "exact": true},
  {"id": "random-variance", "selection": "x", "slots": ["[x]", "\\operatorname{normaldistribution}(3,2)"], "expected": 4, "exact": true},
  {"id": "random-covariance", "selection": "x", "slots": ["2*x", "[x]", "\\operatorname{normaldistribution}(1,3)"], "expected": 18, "exact": true},
  {"id": "random-correlation", "selection": "x", "slots": ["-2*x", "[x]", "\\operatorname{uniformdistribution}(-1,1)"], "expected": -1, "exact": true},
  {"id": "independent-events", "selection": "x>1", "slots": ["x<3", "[x]", "\\operatorname{uniformdistribution}(0,4)"], "expected": "boolean", "exact": true},
  {"id": "independent-variables", "selection": "x", "slots": ["y", "[x,y]", "\\operatorname{independentdistributions}([\\operatorname{normaldistribution}(0,1),\\operatorname{normaldistribution}(0,1)])"], "expected": "boolean", "exact": true},
  {"id": "chi-square-pdf", "selection": "2", "slots": ["2"], "expected": 0.18393972058572117},
  {"id": "chi-square-cdf", "selection": "2", "slots": ["2"], "expected": 0.6321205588285577},
  {"id": "chi-square-quantile", "selection": "2", "slots": ["1/2"], "expected": 1.3862943611198906},
  {"id": "t-pdf", "selection": "1", "slots": ["0"], "expected": 0.3183098861837907},
  {"id": "t-cdf", "selection": "1", "slots": ["1"], "expected": 0.75},
  {"id": "t-quantile", "selection": "1", "slots": ["3/4"], "expected": 1},
  {"id": "f-pdf", "selection": "2", "slots": ["2", "1"], "expected": 0.25},
  {"id": "f-cdf", "selection": "2", "slots": ["2", "1"], "expected": 0.5},
  {"id": "f-quantile", "selection": "2", "slots": ["2", "3/4"], "expected": 3},
  {"id": "gamma-pdf", "selection": "2", "slots": ["1", "1"], "expected": 0.36787944117144233},
  {"id": "gamma-cdf", "selection": "2", "slots": ["1", "1"], "expected": 0.26424111765711533},
  {"id": "gamma-quantile", "selection": "1", "slots": ["2", "0.5"], "expected": 1.3862943611198906},
  {"id": "beta-pdf", "selection": "2", "slots": ["2", "0.5"], "expected": 1.5},
  {"id": "beta-cdf", "selection": "2", "slots": ["3", "0.5"], "expected": 0.6875},
  {"id": "beta-quantile", "selection": "2", "slots": ["2", "0.5"], "expected": 0.5},
  {"id": "normal-pdf", "selection": "0", "slots": ["1", "0"], "expected": 0.3989422804014327},
  {"id": "normal-cdf", "selection": "0", "slots": ["1", "0"], "expected": 0.5},
  {"id": "normal-quantile", "selection": "3", "slots": ["2", "1/2"], "expected": 3},
  {"id": "expectation", "selection": "[0,4]", "slots": ["[1/4,3/4]"], "expected": 3},
  {"id": "probability-variance", "selection": "[0,4]", "slots": ["[1/4,3/4]"], "expected": 3},
  {"id": "conditional-probability", "selection": "1/4", "slots": ["1/2"], "expected": 0.5},
  {"id": "uniform-pdf", "selection": "2", "slots": ["6", "3"], "expected": 0.25},
  {"id": "uniform-cdf", "selection": "2", "slots": ["6", "3"], "expected": 0.25},
  {"id": "uniform-quantile", "selection": "2", "slots": ["6", "1/4"], "expected": 3},
  {"id": "exponential-pdf", "selection": "2", "slots": ["1"], "expected": 0.2706705664732254},
  {"id": "exponential-cdf", "selection": "2", "slots": ["1"], "expected": 0.8646647167633873},
  {"id": "exponential-quantile", "selection": "2", "slots": ["3/4"], "expected": 0.6931471805599453},
  {id:'binomial-quantile',selection:'4',slots:['1/2','11/16'],expected:2},
  {id:'poisson-quantile',selection:'2',slots:['3/4'],expected:3},
  {"id": "poisson-pmf", "selection": "2", "slots": ["3"], "expected": 0.1804470443154836},
  {"id": "poisson-cdf", "selection": "2", "slots": ["2"], "expected": 0.6766764161830635},
  {"id": "divides", "selection": "4", "slots": ["20"], "expected": "boolean"},
  {"id": "congruent-modulo", "selection": "-1", "slots": ["5", "3"], "expected": "boolean"},
  {"id": "is-prime", "selection": "13", "slots": [], "expected": "boolean"},
  { id: 'binomial-pmf', selection: '4', slots: ['1/2', '2'], expected: 0.375 },
  { id: 'binomial-cdf', selection: '4', slots: ['1/2', '2'], expected: 0.6875 },
  {"id": "mean", "selection": "[1,2,6]", "slots": [], "expected": 3},
  {"id": "median", "selection": "[9,1,3,5]", "slots": [], "expected": 4},
  {"id": "modes", "selection": "[1,1,2,2,3]", "slots": [], "expected": "vector"},
  {"id": "quantile", "selection": "[0,10,20,30]", "slots": ["0.25"], "expected": 7.5},
  {"id": "population-variance", "selection": "[1,2,3]", "slots": [], "expected": 0.6666666666666666},
  {"id": "sample-variance", "selection": "[1,2,3]", "slots": [], "expected": 1},
  {"id": "population-standard-deviation", "selection": "[1,3]", "slots": [], "expected": 1},
  {"id": "sample-standard-deviation", "selection": "[1,3]", "slots": [], "expected": 1.4142135623730951},
  {"id": "population-covariance", "selection": "[1,2,3]", "slots": ["[2,4,6]"], "expected": 1.3333333333333333},
  {"id": "sample-covariance", "selection": "[1,2,3]", "slots": ["[2,4,6]"], "expected": 2},
  {"id": "correlation", "selection": "[1,2,3]", "slots": ["[6,4,2]"], "expected": -1},
  {"id": "regression-slope", "selection": "[1,2,3]", "slots": ["[3,5,7]"], "expected": 2},
  {"id": "regression-intercept", "selection": "[1,2,3]", "slots": ["[3,5,7]"], "expected": 1},
  {"id": "r-squared", "selection": "[1,2,3]", "slots": ["[3,5,7]"], "expected": 1},
  // 24-08・25-11・26-09（math-add-coverage.md §7.2 MC-02c）: 下書きのみの4項目(union/intersection/cases/equal)の実例と、
  // 比較・論理10件、集合8件、分布宣言13件の新規実例。分布宣言は math-input.md「分布を宣言して事象と確率変数を計算する」の
  // 実例（randomexpectation(x,[x],normaldistribution(3,2))=3 等）と同じ形で、宣言した分布の期待値を確認する。
  { id: 'union', selection: String.raw`\operatorname{set}(1,2)`, slots: [String.raw`\operatorname{set}(2,3)`], expected: 'set', exact: true },
  { id: 'intersection', selection: String.raw`\operatorname{set}(1,2,3)`, slots: [String.raw`\operatorname{set}(2,3,4)`], expected: 'set', exact: true },
  { id: 'cases', selection: '', slots: ['10', '1>5', '20', '1<5'], expected: 20 },
  { id: 'equal', selection: '3', slots: ['3'], expected: 'boolean' },
  { id: 'not-equal', selection: '3', slots: ['4'], expected: 'boolean' },
  { id: 'less', selection: '2', slots: ['3'], expected: 'boolean' },
  { id: 'less-equal', selection: '3', slots: ['3'], expected: 'boolean' },
  { id: 'greater', selection: '5', slots: ['2'], expected: 'boolean' },
  { id: 'greater-equal', selection: '5', slots: ['5'], expected: 'boolean' },
  { id: 'and', selection: '3>1', slots: ['5<10'], expected: 'boolean' },
  { id: 'or', selection: '3>10', slots: ['5<10'], expected: 'boolean' },
  { id: 'not', selection: '3>10', slots: [], expected: 'boolean' },
  { id: 'implies', selection: '3>10', slots: ['5<10'], expected: 'boolean' },
  { id: 'equivalent', selection: '3>1', slots: ['5<10'], expected: 'boolean' },
  { id: 'empty-set', selection: '', slots: [], expected: 'set' },
  { id: 'natural-numbers', selection: '', slots: [], expected: 'set' },
  { id: 'integer-numbers', selection: '', slots: [], expected: 'set' },
  { id: 'rational-numbers', selection: '', slots: [], expected: 'set' },
  { id: 'real-numbers', selection: '', slots: [], expected: 'set' },
  { id: 'complex-numbers', selection: '', slots: [], expected: 'set' },
  { id: 'element', selection: '3', slots: [String.raw`\operatorname{set}(1,2,3)`], expected: 'boolean', exact: true },
  { id: 'set-minus', selection: String.raw`\operatorname{set}(1,2,3)`, slots: [String.raw`\operatorname{set}(2,3)`], expected: 'set', exact: true },
  { id: 'normal-distribution', selection: '3', slots: ['2'], expected: 3, exact: true },
  { id: 'uniform-distribution', selection: '0', slots: ['4'], expected: 2, exact: true },
  { id: 'exponential-distribution', selection: '2', slots: [], expected: 0.5, exact: true },
  { id: 'gamma-distribution', selection: '2', slots: ['3'], expected: 6, exact: true },
  { id: 'beta-distribution', selection: '2', slots: ['3'], expected: 0.4, exact: true },
  { id: 'chisquare-distribution', selection: '4', slots: [], expected: 4, exact: true },
  { id: 't-distribution', selection: '4', slots: [], expected: 0, exact: true },
  { id: 'f-distribution', selection: '3', slots: ['6'], expected: 1.5, exact: true },
  { id: 'binomial-distribution', selection: '4', slots: ['1/2'], expected: 2, exact: true },
  { id: 'poisson-distribution', selection: '3', slots: [], expected: 3, exact: true },
  { id: 'finite-distribution', selection: '[2,8]', slots: ['[1/4,3/4]'], expected: 6.5, exact: true },
  { id: 'joint-finite-distribution', selection: '[[0,0],[2,2]]', slots: ['[1/4,3/4]'], expected: 3, exact: true },
  { id: 'independent-distributions', selection: String.raw`[\operatorname{normaldistribution}(0,1),\operatorname{normaldistribution}(3,2)]`, slots: [], expected: 3, exact: true },
  // Declaration-only acceptance: source, dependent variables and conditions survive without a fabricated solution.
  { id: 'partial-equations', selection: String.raw`[\operatorname{diff}(u,t)=\operatorname{diff}(u,x,x)]`,
    slots: ['[x,t]', '[u]', '[[u,[0,t],3]]'], expected: 'unevaluated', exact: true },
  // MC-02d (MC-23): set relations, confirmed by cx-mc23-setrelations (setRelations.test.ts).
  { id: 'not-element', selection: '3', slots: [String.raw`\operatorname{set}(1,2)`], expected: 'boolean', exact: true },
  { id: 'subset', selection: String.raw`\operatorname{set}(1)`, slots: [String.raw`\operatorname{set}(1,2)`], expected: 'boolean', exact: true },
  { id: 'subset-equal', selection: String.raw`\operatorname{set}(2,1)`, slots: [String.raw`\operatorname{set}(1,2)`], expected: 'boolean', exact: true },
  { id: 'superset', selection: String.raw`\operatorname{set}(1,2)`, slots: [String.raw`\operatorname{set}(1)`], expected: 'boolean', exact: true },
  { id: 'superset-equal', selection: String.raw`\operatorname{set}(1)`, slots: [String.raw`\operatorname{set}(1)`], expected: 'boolean', exact: true },
  { id: 'complement', selection: String.raw`\operatorname{set}(2)`, slots: [String.raw`\operatorname{set}(1,2,3)`], expected: 'set', exact: true },
  { id: 'cartesian-product', selection: String.raw`\operatorname{set}(1,2)`, slots: [String.raw`\operatorname{set}(3)`], expected: 'set', exact: true },
  // MC-02d (MC-24): explicit absolute tolerance, confirmed by cx-mc24-logic (logicExtended.test.ts).
  { id: 'approximately-equal', selection: '0.3', slots: ['0.2', '0.1'], expected: 'boolean', exact: true },
  // MC-02d (MC-12): finite set cardinality, confirmed by cardinality.test.ts.
  { id: 'cardinality', selection: String.raw`\{1,2,3\}`, slots: [], expected: 3, exact: true },
  // MC-02d (MC-04 gap): boolean literal constants.
  { id: 'true', selection: '', slots: [], expected: 'boolean' },
  { id: 'false', selection: '', slots: [], expected: 'boolean' },
  // MC-02e (MC-24): finite quantifiers, confirmed by cx-mc24-logic (logicExtended.test.ts) and
  // math-input.md's own worked examples (forall(x,{1,2,3},x>0)=true, exists(x,{0,1,3},x^2==4)=false).
  { id: 'for-all', selection: '', slots: ['x', String.raw`\{1,2,3\}`, 'x>0'], expected: 'boolean', exact: true },
  { id: 'exists', selection: '', slots: ['x', String.raw`\{0,1,3\}`, 'x^2=4'], expected: 'boolean', exact: true },
];
