import type { MathPaletteExample } from './mathPaletteGroups.js';

/**
 * mathPaletteBasic.ts の項目の実例（公開パレットの受入）。selection は #0、slots は #? へ出現順に入れる。
 * mathPaletteExamples.test.ts が構造入力と同じ経路で実計算し、期待した数値・型と目録の欄を照合する。
 * 表示順は mathPaletteExamples.ts の MATH_PALETTE_DISPLAY_ORDER（新しい項目は既存の項目の後ろ）。
 */
export const MATH_PALETTE_BASIC_EXAMPLES: readonly MathPaletteExample[] = [
  { id: 'dft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'idft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'fft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'ifft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'zeta', selection: '2', slots: [], expected: Math.PI**2/6 },
  { id: 'zetaderivative', selection: '1', slots: ['2'], expected: Number('-0.9375482543158437537') },
  { id: 'elliptick', selection: '0', slots: [], expected: Math.PI/2 },
  { id: 'elliptice', selection: '1', slots: [], expected: 1 },
  { id: 'ellipticf', selection: '90', slots: ["0"], expected: Math.PI/2 },
  { id: 'ellipticeinc', selection: '90', slots: ["1"], expected: 1 },
  { id: 'ellipticpi', selection: '0', slots: ["0"], expected: Math.PI/2 },
  { id: 'ellipticpiinc', selection: '0', slots: ["90", "0"], expected: Math.PI/2 },
  { id: 'airyai', selection: '1', slots: [], expected: Number('0.13529241631288141') },
  { id: 'airybi', selection: '1', slots: [], expected: Number('1.2074235949528713') },
  { id: 'airyaiprime', selection: '1', slots: [], expected: Number('-0.1591474412967932') },
  { id: 'airybiprime', selection: '1', slots: [], expected: Number('0.9324359333927756') },
  { id: 'lambertw', selection: '0', slots: ['1'], expected: Number('0.5671432904097838') },
  { id: 'besselj', selection: '0', slots: ['1'], expected: 0.7651976865579666 },
  { id: 'bessely', selection: '0', slots: ['1'], expected: 0.08825696421567696 },
  { id: 'besseli', selection: '0', slots: ['1'], expected: Number('1.2660658777520083') },
  { id: 'besselk', selection: '0', slots: ['1'], expected: Number('0.42102443824070833') },
  { id: 'beta', selection: '2', slots: ['3'], expected: 1/12 },
  { id: 'gamma', selection: '5', slots: [], expected: 24 },
  { id: 'polygamma', selection: '1', slots: ['1'], expected: 1.6449340668482264 },
  { id: 'erf', selection: '1', slots: [], expected: 0.8427007929497149 },
  { id: 'erfc', selection: '1', slots: [], expected: 0.15729920705028513 },
  { id: 'legendre', selection: '4', slots: ['0'], expected: 0.375 },
  {"id": "integer-quotient", "selection": "-7", "slots": ["3"], "expected": -3},
  {"id": "integer-remainder", "selection": "-7", "slots": ["-3"], "expected": 2},
  {"id": "next-prime", "selection": "97", "slots": [], "expected": 101},
  {"id": "prime-factors", "selection": "360", "slots": [], "expected": "matrix"},
  {"id": "divisors", "selection": "36", "slots": [], "expected": "vector"},
  {"id": "euler-totient", "selection": "36", "slots": [], "expected": 12},
  { id: 'reciprocal', selection: '4', slots: [], expected: 0.25 },
  { id: 'double-factorial', selection: '5', slots: [], expected: 15 },
  { id: 'permutations', selection: '5', slots: ['3'], expected: 60 },
  { id: 'clamp', selection: '8', slots: ['1', '5'], expected: 5 },
  { id: 'arccot', selection: '-1', slots: [], expected: 135 },
  { id: 'arcsec', selection: '2', slots: [], expected: 60 },
  { id: 'arccsc', selection: '2', slots: [], expected: 30 },
  { id: 'atan2', selection: '1', slots: ['-1'], expected: 135 },
  { id: 'coth', selection: String.raw`\ln(3)`, slots: [], expected: 1.25 },
  { id: 'sech', selection: '0', slots: [], expected: 1 },
  { id: 'csch', selection: String.raw`\ln(3)`, slots: [], expected: 0.75 },
  { id: 'arcoth', selection: '2', slots: [], expected: Math.log(3)/2 },
  { id: 'arsech', selection: '1', slots: [], expected: 0 },
  { id: 'arcsch', selection: '1', slots: [], expected: Math.log(1+Math.sqrt(2)) },
  { id: 'fraction', selection: '3', slots: ['2'], expected: 1.5 },
  { id: 'power', selection: '2', slots: ['3'], expected: 8 },
  { id: 'square-root', selection: '9', slots: [], expected: 3 },
  { id: 'nth-root', selection: '8', slots: ['3'], expected: 2 },
  { id: 'factorial', selection: '5', slots: [], expected: 120 },
  { id: 'absolute', selection: '-3', slots: [], expected: 3 },
  { id: 'sin', selection: '30', slots: [], expected: 0.5 },
  { id: 'cos', selection: '60', slots: [], expected: 0.5 },
  { id: 'tan', selection: '45', slots: [], expected: 1 },
  { id: 'arcsin', selection: '0.5', slots: [], expected: 30 },
  { id: 'log-natural', selection: '\\exponentialE', slots: [], expected: 1 },
  { id: 'log-ten', selection: '100', slots: [], expected: 2 },
  { id: 'log-base', selection: '8', slots: ['2'], expected: 3 },
  { id: 'sinh', selection: '0', slots: [], expected: 0 },
  { id: 'pi', selection: '', slots: [], expected: Math.PI },
  { id: 'imaginary-unit', selection: '', slots: [], expected: 'complex' },
  // MC-02a: 初等・整数・複素の追加27件（下書きだったreal-part・imaginary-part・conjugateの実例化を含む）。
  { id: 'arccos', selection: '0.5', slots: [], expected: 60 },
  { id: 'arctan', selection: '1', slots: [], expected: 45 },
  { id: 'cot', selection: '45', slots: [], expected: 1 },
  { id: 'sec', selection: '60', slots: [], expected: 2 },
  { id: 'csc', selection: '30', slots: [], expected: 2 },
  { id: 'cosh', selection: '0', slots: [], expected: 1 },
  { id: 'tanh', selection: String.raw`\ln(3)`, slots: [], expected: 0.8 },
  { id: 'arsinh', selection: '0', slots: [], expected: 0 },
  { id: 'arcosh', selection: '1', slots: [], expected: 0 },
  { id: 'artanh', selection: '0.8', slots: [], expected: Math.log(3) },
  { id: 'exponential', selection: '1', slots: [], expected: Math.E },
  { id: 'log-two', selection: '8', slots: [], expected: 3 },
  { id: 'floor', selection: '2.7', slots: [], expected: 2 },
  { id: 'ceiling', selection: '2.1', slots: [], expected: 3 },
  { id: 'round', selection: '2.6', slots: [], expected: 3 },
  { id: 'sign', selection: '-5', slots: [], expected: -1 },
  { id: 'minimum', selection: '3', slots: ['5'], expected: 3 },
  { id: 'maximum', selection: '3', slots: ['5'], expected: 5 },
  { id: 'binomial', selection: '5', slots: ['2'], expected: 10 },
  { id: 'gcd', selection: '24', slots: ['18'], expected: 6 },
  { id: 'lcm', selection: '4', slots: ['6'], expected: 12 },
  { id: 'modulo', selection: '7', slots: ['3'], expected: 1 },
  { id: 'argument', selection: String.raw`\operatorname{complex}\left(1,1\right)`, slots: [], expected: 45 },
  { id: 'cis', selection: '90', slots: [], expected: 'complex' },
  { id: 'real-part', selection: String.raw`\operatorname{complex}\left(3,4\right)`, slots: [], expected: 3 },
  { id: 'imaginary-part', selection: String.raw`\operatorname{complex}\left(3,4\right)`, slots: [], expected: 4 },
  { id: 'conjugate', selection: String.raw`\operatorname{complex}\left(3,4\right)`, slots: [], expected: 'complex' },
  // MC-02d (MC-04 gap): hard-to-type constant. ∞ was tried and dropped (see mathPaletteBasic.ts's comment).
  { id: 'e', selection: '', slots: [], expected: Math.E },
  // MC-02e (MC-11): confirmed by plusMinus.test.ts ('1±2'→[3,-1], '1∓2'→[-1,3]); order matches the
  // candidates array exactly (first operand plus, then minus), never collapsed to one value.
  { id: 'plus-minus', selection: '1', slots: ['2'], expected: { candidates: [3, -1] } },
  { id: 'minus-plus', selection: '1', slots: ['2'], expected: { candidates: [-1, 3] } },
];
