import { t } from '../i18n/t.js';
import { mathPaletteItem as item, type MathPaletteCatalogItem } from './mathPaletteGroups.js';

/**
 * 数学の目録の分野別ファイル: 基本（数と演算・初等関数・特殊関数・複素数・定数）。
 * 分野（group）が basic・functions・complex・symbols の項目を置く。文言は i18n/ja/mathPaletteBasic.json、
 * 公開パレットの実例は mathPaletteBasicExamples.ts にある（実例と受入IDが揃った項目だけを公開する）。
 * 各項目は名前・記号・ひな形・必要な演算・意味・検索語と、引数型・結果型・計算方式・関数作図での利用・
 * 説明の節（mathPaletteGroups.ts の MathPaletteFields）を持つ。欄の正しさは mathPaletteExamples.test.ts が実計算で照合する。
 */
/** 説明「構造化した数式と係数を入力する」の見出し（この分野の項目が参照する節）。 */
const HELP = {
  complex: t('math.paletteHelp.basic.complex'),
  zeta: t('math.paletteHelp.basic.zeta'),
  elliptic: t('math.paletteHelp.basic.elliptic'),
  airy: t('math.paletteHelp.basic.airy'),
  lambertW: t('math.paletteHelp.basic.lambertW'),
  bessel: t('math.paletteHelp.basic.bessel'),
  inputUnits: t('math.paletteHelp.basic.inputUnits'),
  paletteArguments: t('math.paletteHelp.basic.paletteArguments'),
  integers: t('math.paletteHelp.basic.integers'),
  legendre: t('math.paletteHelp.basic.legendre'),
  gamma: t('math.paletteHelp.basic.gamma'),
  errorFunction: t('math.paletteHelp.basic.errorFunction'),
  beta: t('math.paletteHelp.basic.beta'),
  dft: t('math.paletteHelp.basic.dft'),
  symbols: t('math.paletteHelp.basic.symbols'),
  plusMinus: t('math.paletteHelp.basic.plusMinus'),
} as const;

export const MATH_PALETTE_BASIC: readonly MathPaletteCatalogItem[] = [
  item('dft', 'functions', t('math.palette.dft.label'), 'DFT', String.raw`\operatorname{dft}\left(#0\right)`, ['dft'], t('math.palette.dft.meaning'), [],
    { domain: t('math.paletteDomain.basic.dft'), argumentTypes: ['vector'], resultType: 'vector', method: 'exact-runtime', functionUse: false, help: HELP.dft }),
  item('idft', 'functions', t('math.palette.idft.label'), 'IDFT', String.raw`\operatorname{idft}\left(#0\right)`, ['idft'], t('math.palette.idft.meaning'), [],
    { domain: t('math.paletteDomain.basic.idft'), argumentTypes: ['vector'], resultType: 'vector', method: 'exact-runtime', functionUse: false, help: HELP.dft }),
  item('fft', 'functions', t('math.palette.fft.label'), 'FFT', String.raw`\operatorname{fft}\left(#0\right)`, ['fft'], t('math.palette.fft.meaning'), [],
    { domain: t('math.paletteDomain.basic.fft'), argumentTypes: ['vector'], resultType: 'vector', method: 'exact-runtime', functionUse: false, help: HELP.dft }),
  item('ifft', 'functions', t('math.palette.ifft.label'), 'IFFT', String.raw`\operatorname{ifft}\left(#0\right)`, ['ifft'], t('math.palette.ifft.meaning'), [],
    { domain: t('math.paletteDomain.basic.ifft'), argumentTypes: ['vector'], resultType: 'vector', method: 'exact-runtime', functionUse: false, help: HELP.dft }),
  item('zeta', 'functions', t('math.palette.zeta.label'), 'ζ', String.raw`\operatorname{zeta}\left(#0\right)`, ['zeta'], t('math.palette.zeta.meaning'), [],
    { domain: t('math.paletteDomain.basic.zeta'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.zeta }),
  item('zetaderivative', 'functions', t('math.palette.zetaderivative.label'), 'ζ⁽ⁿ⁾', String.raw`\operatorname{zetaderivative}\left(#0,#?\right)`, ['zetaderivative'], t('math.palette.zetaderivative.meaning'), [],
    { domain: t('math.paletteDomain.basic.zetaderivative'), argumentTypes: ['natural', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.zeta }),
  item('elliptick', 'functions', t('math.palette.elliptick.label'), 'K', String.raw`\operatorname{elliptick}\left(#0\right)`, ['elliptick'], t('math.palette.elliptick.meaning'), [],
    { domain: t('math.paletteDomain.basic.elliptick'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.elliptic }),
  item('elliptice', 'functions', t('math.palette.elliptice.label'), 'E', String.raw`\operatorname{elliptice}\left(#0\right)`, ['elliptice'], t('math.palette.elliptice.meaning'), [],
    { domain: t('math.paletteDomain.basic.elliptice'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.elliptic }),
  item('ellipticf', 'functions', t('math.palette.ellipticf.label'), 'F', String.raw`\operatorname{ellipticf}\left(#0,#?\right)`, ['ellipticf'], t('math.palette.ellipticf.meaning'), [],
    { domain: t('math.paletteDomain.basic.ellipticf'), argumentTypes: ['angle', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.elliptic }),
  item('ellipticeinc', 'functions', t('math.palette.ellipticeinc.label'), 'Einc', String.raw`\operatorname{ellipticeinc}\left(#0,#?\right)`, ['ellipticeinc'], t('math.palette.ellipticeinc.meaning'), [],
    { domain: t('math.paletteDomain.basic.ellipticeinc'), argumentTypes: ['angle', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.elliptic }),
  item('ellipticpi', 'functions', t('math.palette.ellipticpi.label'), 'Pi', String.raw`\operatorname{ellipticpi}\left(#0,#?\right)`, ['ellipticpi'], t('math.palette.ellipticpi.meaning'), [],
    { domain: t('math.paletteDomain.basic.ellipticpi'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.elliptic }),
  item('ellipticpiinc', 'functions', t('math.palette.ellipticpiinc.label'), 'Piinc', String.raw`\operatorname{ellipticpiinc}\left(#0,#?,#?\right)`, ['ellipticpiinc'], t('math.palette.ellipticpiinc.meaning'), [],
    { domain: t('math.paletteDomain.basic.ellipticpiinc'), argumentTypes: ['real', 'angle', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.elliptic }),
  item('airyai', 'functions', t('math.palette.airyai.label'), 'Airy Ai', String.raw`\operatorname{airyai}\left(#0\right)`, ['airyai'], t('math.palette.airyai.meaning'), [],
    { domain: t('math.paletteDomain.basic.airyai'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.airy }),
  item('airybi', 'functions', t('math.palette.airybi.label'), 'Airy Bi', String.raw`\operatorname{airybi}\left(#0\right)`, ['airybi'], t('math.palette.airybi.meaning'), [],
    { domain: t('math.paletteDomain.basic.airybi'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.airy }),
  item('airyaiprime', 'functions', t('math.palette.airyaiprime.label'), 'Airy Ai′', String.raw`\operatorname{airyaiprime}\left(#0\right)`, ['airyaiprime'], t('math.palette.airyaiprime.meaning'), [],
    { domain: t('math.paletteDomain.basic.airyaiprime'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.airy }),
  item('airybiprime', 'functions', t('math.palette.airybiprime.label'), 'Airy Bi′', String.raw`\operatorname{airybiprime}\left(#0\right)`, ['airybiprime'], t('math.palette.airybiprime.meaning'), [],
    { domain: t('math.paletteDomain.basic.airybiprime'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.airy }),
  item('lambertw', 'functions', t('math.palette.lambertw.label'), 'Lambert W', String.raw`\operatorname{lambertw}\left(#0,#?\right)`, ['lambertw'], t('math.palette.lambertw.meaning'), [],
    { domain: t('math.paletteDomain.basic.lambertw'), argumentTypes: ['integer', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.lambertW }),
  item('besselj', 'functions', t('math.palette.besselj.label'), 'Bessel J', String.raw`\operatorname{besselj}\left(#0,#?\right)`, ['besselj'], t('math.palette.besselj.meaning'), [],
    { domain: t('math.paletteDomain.basic.besselj'), argumentTypes: ['integer', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.bessel }),
  item('bessely', 'functions', t('math.palette.bessely.label'), 'Bessel Y', String.raw`\operatorname{bessely}\left(#0,#?\right)`, ['bessely'], t('math.palette.bessely.meaning'), [],
    { domain: t('math.paletteDomain.basic.bessely'), argumentTypes: ['integer', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.bessel }),
  item('besseli', 'functions', t('math.palette.besseli.label'), 'Bessel I', String.raw`\operatorname{besseli}\left(#0,#?\right)`, ['besseli'], t('math.palette.besseli.meaning'), [],
    { domain: t('math.paletteDomain.basic.besseli'), argumentTypes: ['integer', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.bessel }),
  item('besselk', 'functions', t('math.palette.besselk.label'), 'Bessel K', String.raw`\operatorname{besselk}\left(#0,#?\right)`, ['besselk'], t('math.palette.besselk.meaning'), [],
    { domain: t('math.paletteDomain.basic.besselk'), argumentTypes: ['integer', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.bessel }),
  item('beta', 'functions', t('math.palette.beta.label'), 'Beta', String.raw`\operatorname{beta}\left(#0,#?\right)`, ['beta'], t('math.palette.beta.meaning'), [],
    { domain: t('math.paletteDomain.basic.beta'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.beta }),
  item('gamma', 'functions', t('math.palette.gamma.label'), 'Gamma', String.raw`\operatorname{gamma}\left(#0\right)`, ['gamma'], t('math.palette.gamma.meaning'), [],
    { domain: t('math.paletteDomain.basic.gamma'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.gamma }),
  item('polygamma', 'functions', t('math.palette.polygamma.label'), 'polygamma', String.raw`\operatorname{polygamma}\left(#0,#?\right)`, ['polygamma'], t('math.palette.polygamma.meaning'), [],
    { domain: t('math.paletteDomain.basic.polygamma'), argumentTypes: ['natural', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.gamma }),
  item('erf', 'functions', t('math.palette.erf.label'), 'erf', String.raw`\operatorname{erf}\left(#0\right)`, ['erf'], t('math.palette.erf.meaning'), [],
    { domain: t('math.paletteDomain.basic.erf'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.errorFunction }),
  item('erfc', 'functions', t('math.palette.erfc.label'), 'erfc', String.raw`\operatorname{erfc}\left(#0\right)`, ['erfc'], t('math.palette.erfc.meaning'), [],
    { domain: t('math.paletteDomain.basic.erfc'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.errorFunction }),
  item('legendre', 'functions', t('math.palette.legendre.label'), 'legendre', String.raw`\operatorname{legendre}\left(#0,#?\right)`, ['legendre'], t('math.palette.legendre.meaning'), [],
    { domain: t('math.paletteDomain.basic.legendre'), argumentTypes: ['natural', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.legendre }),
  item('integer-quotient', 'basic', t('math.palette.integer-quotient.label'), 'q', String.raw`\operatorname{integerquotient}\left(#0,#?\right)`, ['integer-quotient'], t('math.palette.integer-quotient.meaning'), [],
    { domain: t('math.paletteDomain.basic.integer-quotient'), argumentTypes: ['integer', 'integer'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('integer-remainder', 'basic', t('math.palette.integer-remainder.label'), 'r', String.raw`\operatorname{integerremainder}\left(#0,#?\right)`, ['integer-remainder'], t('math.palette.integer-remainder.meaning'), [],
    { domain: t('math.paletteDomain.basic.integer-remainder'), argumentTypes: ['integer', 'integer'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('next-prime', 'basic', t('math.palette.next-prime.label'), 'next prime', String.raw`\operatorname{nextprime}\left(#0\right)`, ['next-prime'], t('math.palette.next-prime.meaning'), [],
    { domain: t('math.paletteDomain.basic.next-prime'), argumentTypes: ['integer'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('prime-factors', 'basic', t('math.palette.prime-factors.label'), 'n=∏pᵏ', String.raw`\operatorname{primefactors}\left(#0\right)`, ['prime-factors'], t('math.palette.prime-factors.meaning'), [],
    { domain: t('math.paletteDomain.basic.prime-factors'), argumentTypes: ['natural'], resultType: 'matrix', method: 'native', functionUse: false, help: HELP.integers }),
  item('divisors', 'basic', t('math.palette.divisors.label'), 'd|n', String.raw`\operatorname{divisors}\left(#0\right)`, ['divisors'], t('math.palette.divisors.meaning'), [],
    { domain: t('math.paletteDomain.basic.divisors'), argumentTypes: ['natural'], resultType: 'vector', method: 'native', functionUse: false, help: HELP.integers }),
  item('euler-totient', 'basic', t('math.palette.euler-totient.label'), 'φ(n)', String.raw`\operatorname{eulertotient}\left(#0\right)`, ['euler-totient'], t('math.palette.euler-totient.meaning'), [],
    { domain: t('math.paletteDomain.basic.euler-totient'), argumentTypes: ['natural'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('reciprocal', 'basic', t('math.palette.reciprocal.label'), '1/x', String.raw`\operatorname{reciprocal}\left(#0\right)`, ['reciprocal'], t('math.palette.reciprocal.meaning'), [t('math.palette.reciprocal.keyword0'), t('math.palette.reciprocal.keyword1')],
    { domain: t('math.paletteDomain.basic.reciprocal'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('double-factorial', 'basic', t('math.palette.double-factorial.label'), 'n!!', String.raw`{#0}!!`, ['double-factorial'], t('math.palette.double-factorial.meaning'), [],
    { domain: t('math.paletteDomain.basic.double-factorial'), argumentTypes: ['integer'], resultType: 'real', method: 'native', functionUse: false, help: HELP.paletteArguments }),
  item('permutations', 'basic', t('math.palette.permutations.label'), 'nPr', String.raw`\operatorname{permutations}\left(#0,#?\right)`, ['permutations'], t('math.palette.permutations.meaning'), [t('math.palette.permutations.keyword0'), t('math.palette.permutations.keyword1')],
    { domain: t('math.paletteDomain.basic.permutations'), argumentTypes: ['natural', 'natural'], resultType: 'real', method: 'native', functionUse: false, help: HELP.paletteArguments }),
  item('clamp', 'basic', t('math.palette.clamp.label'), 'clamp', String.raw`\operatorname{clamp}\left(#0,#?,#?\right)`, ['clamp'], t('math.palette.clamp.meaning'), [],
    { domain: t('math.paletteDomain.basic.clamp'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arccot', 'functions', t('math.palette.arccot.label'), 'arccot', String.raw`\operatorname{arccot}\left(#0\right)`, ['arccot'], t('math.palette.arccot.meaning'), [t('math.palette.arccot.keyword0'), t('math.palette.arccot.keyword1')],
    { domain: t('math.paletteDomain.basic.arccot'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arcsec', 'functions', t('math.palette.arcsec.label'), 'arcsec', String.raw`\operatorname{arcsec}\left(#0\right)`, ['arcsec'], t('math.palette.arcsec.meaning'), [t('math.palette.arcsec.keyword0'), t('math.palette.arcsec.keyword1')],
    { domain: t('math.paletteDomain.basic.arcsec'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arccsc', 'functions', t('math.palette.arccsc.label'), 'arccsc', String.raw`\operatorname{arccsc}\left(#0\right)`, ['arccsc'], t('math.palette.arccsc.meaning'), [t('math.palette.arccsc.keyword0'), t('math.palette.arccsc.keyword1')],
    { domain: t('math.paletteDomain.basic.arccsc'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('atan2', 'functions', t('math.palette.atan2.label'), 'atan2(y,x)', String.raw`\operatorname{arctan2}\left(#0,#?\right)`, ['arctan-two'], t('math.palette.atan2.meaning'), [t('math.palette.atan2.keyword0'), t('math.palette.atan2.keyword1'), t('math.palette.atan2.keyword2')],
    { domain: t('math.paletteDomain.basic.atan2'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.paletteArguments }),
  item('coth', 'functions', t('math.palette.coth.label'), 'coth', String.raw`\operatorname{coth}\left(#0\right)`, ['coth'], t('math.palette.coth.meaning'), [],
    { domain: t('math.paletteDomain.basic.coth'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('sech', 'functions', t('math.palette.sech.label'), 'sech', String.raw`\operatorname{sech}\left(#0\right)`, ['sech'], t('math.palette.sech.meaning'), [],
    { domain: t('math.paletteDomain.basic.sech'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('csch', 'functions', t('math.palette.csch.label'), 'csch', String.raw`\operatorname{csch}\left(#0\right)`, ['csch'], t('math.palette.csch.meaning'), [],
    { domain: t('math.paletteDomain.basic.csch'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arcoth', 'functions', t('math.palette.arcoth.label'), 'acoth', String.raw`\operatorname{arcoth}\left(#0\right)`, ['arcoth'], t('math.palette.arcoth.meaning'), [t('math.palette.arcoth.keyword0')],
    { domain: t('math.paletteDomain.basic.arcoth'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arsech', 'functions', t('math.palette.arsech.label'), 'asech', String.raw`\operatorname{arsech}\left(#0\right)`, ['arsech'], t('math.palette.arsech.meaning'), [t('math.palette.arsech.keyword0')],
    { domain: t('math.paletteDomain.basic.arsech'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arcsch', 'functions', t('math.palette.arcsch.label'), 'acsch', String.raw`\operatorname{arcsch}\left(#0\right)`, ['arcsch'], t('math.palette.arcsch.meaning'), [t('math.palette.arcsch.keyword0')],
    { domain: t('math.paletteDomain.basic.arcsch'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('fraction', 'basic', t('math.palette.fraction.label'), 'a/b', String.raw`\frac{#0}{#?}`, ['divide'], t('math.palette.fraction.meaning'), [t('math.palette.fraction.keyword0'), t('math.palette.fraction.keyword1')],
    { domain: t('math.paletteDomain.basic.fraction'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('power', 'basic', t('math.palette.power.label'), 'xⁿ', String.raw`{#0}^{#?}`, ['power'], t('math.palette.power.meaning'), [t('math.palette.power.keyword0'), t('math.palette.power.keyword1')],
    { domain: t('math.paletteDomain.basic.power'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('square-root', 'basic', t('math.palette.square-root.label'), '√', String.raw`\sqrt{#0}`, ['sqrt'], t('math.palette.square-root.meaning'), [t('math.palette.square-root.keyword0'), t('math.palette.square-root.keyword1')],
    { domain: t('math.paletteDomain.basic.square-root'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('nth-root', 'basic', t('math.palette.nth-root.label'), 'ⁿ√', String.raw`\sqrt[#?]{#0}`, ['root'], t('math.palette.nth-root.meaning'), [t('math.palette.nth-root.keyword0'), t('math.palette.nth-root.keyword1')],
    { domain: t('math.paletteDomain.basic.nth-root'), argumentTypes: ['real', 'natural'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('factorial', 'basic', t('math.palette.factorial.label'), 'n!', String.raw`{#0}!`, ['factorial'], t('math.palette.factorial.meaning'), [t('math.palette.factorial.keyword0')],
    { domain: t('math.paletteDomain.basic.factorial'), argumentTypes: ['natural'], resultType: 'real', method: 'native', functionUse: false, help: HELP.inputUnits }),
  // MC-02d (統括 09:28): |x| now also reaches vector length, set cardinality and square-matrix candidates
  // (absoluteValueCandidates.ts). argumentTypes widened to 'complex' (real still matches via sameKind's real⊂complex
  // rule; the existing example stays a real number). 'complex' is the closest single declared type this catalog's
  // one-type-per-slot MathPaletteArgumentType can express; vector/set/matrix acceptance has no matching slot type
  // without either a union type or dedicated examples, so it is not encoded here (see final report).
  item('absolute', 'basic', t('math.palette.absolute.label'), '|x|', String.raw`\left|#0\right|`, ['absolute'], t('math.palette.absolute.meaning'), [t('math.palette.absolute.keyword0'), t('math.palette.absolute.keyword1')],
    { domain: t('math.paletteDomain.basic.absolute'), argumentTypes: ['complex'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('sin', 'functions', t('math.palette.sin.label'), 'sin', String.raw`\sin\left(#0\right)`, ['sin'], t('math.palette.sin.meaning'), [t('math.palette.sin.keyword0')],
    { domain: t('math.paletteDomain.basic.sin'), argumentTypes: ['angle'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('cos', 'functions', t('math.palette.cos.label'), 'cos', String.raw`\cos\left(#0\right)`, ['cos'], t('math.palette.cos.meaning'), [t('math.palette.cos.keyword0')],
    { domain: t('math.paletteDomain.basic.cos'), argumentTypes: ['angle'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('tan', 'functions', t('math.palette.tan.label'), 'tan', String.raw`\tan\left(#0\right)`, ['tan'], t('math.palette.tan.meaning'), [t('math.palette.tan.keyword0')],
    { domain: t('math.paletteDomain.basic.tan'), argumentTypes: ['angle'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('arcsin', 'functions', t('math.palette.arcsin.label'), 'arcsin', String.raw`\arcsin\left(#0\right)`, ['arcsin'], t('math.palette.arcsin.meaning'), [t('math.palette.arcsin.keyword0'), t('math.palette.arcsin.keyword1')],
    { domain: t('math.paletteDomain.basic.arcsin'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.inputUnits }),
  item('log-natural', 'functions', t('math.palette.log-natural.label'), 'ln', String.raw`\ln\left(#0\right)`, ['natural-log'], t('math.palette.log-natural.meaning'), [t('math.palette.log-natural.keyword0'), t('math.palette.log-natural.keyword1')],
    { domain: t('math.paletteDomain.basic.log-natural'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('log-ten', 'functions', t('math.palette.log-ten.label'), 'log₁₀', String.raw`\log_{10}\left(#0\right)`, ['log-base'], t('math.palette.log-ten.meaning'), [t('math.palette.log-ten.keyword0'), t('math.palette.log-ten.keyword1')],
    { domain: t('math.paletteDomain.basic.log-ten'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('log-base', 'functions', t('math.palette.log-base.label'), 'logₐ', String.raw`\log_{#?}\left(#0\right)`, ['log-base'], t('math.palette.log-base.meaning'), [t('math.palette.log-base.keyword0'), t('math.palette.log-base.keyword1')],
    { domain: t('math.paletteDomain.basic.log-base'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('sinh', 'functions', t('math.palette.sinh.label'), 'sinh', String.raw`\sinh\left(#0\right)`, ['sinh'], t('math.palette.sinh.meaning'), [t('math.palette.sinh.keyword0')],
    { domain: t('math.paletteDomain.basic.sinh'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('real-part', 'complex', t('math.palette.real-part.label'), 'Re', String.raw`\operatorname{Re}\left(#0\right)`, ['real-part'], t('math.palette.real-part.meaning'), [t('math.palette.real-part.keyword0'), t('math.palette.real-part.keyword1')],
    { domain: t('math.paletteDomain.basic.real-part'), argumentTypes: ['complex'], resultType: 'real', method: 'native', functionUse: false, help: HELP.complex }),
  item('imaginary-part', 'complex', t('math.palette.imaginary-part.label'), 'Im', String.raw`\operatorname{Im}\left(#0\right)`, ['imaginary-part'], t('math.palette.imaginary-part.meaning'), [t('math.palette.imaginary-part.keyword0'), t('math.palette.imaginary-part.keyword1')],
    { domain: t('math.paletteDomain.basic.imaginary-part'), argumentTypes: ['complex'], resultType: 'real', method: 'native', functionUse: false, help: HELP.complex }),
  item('conjugate', 'complex', t('math.palette.conjugate.label'), 'z̄', String.raw`\overline{#0}`, ['conjugate'], t('math.palette.conjugate.meaning'), [t('math.palette.conjugate.keyword0'), t('math.palette.conjugate.keyword1')],
    { domain: t('math.paletteDomain.basic.conjugate'), argumentTypes: ['complex'], resultType: 'complex', method: 'native', functionUse: false, help: HELP.complex }),
  item('pi', 'symbols', t('math.palette.pi.label'), 'π', String.raw`\pi`, [], t('math.palette.pi.meaning'), [t('math.palette.pi.keyword0'), t('math.palette.pi.keyword1')],
    { domain: t('math.paletteDomain.basic.pi'), argumentTypes: [], resultType: 'real', method: 'native', functionUse: true, help: HELP.symbols }),
  item('imaginary-unit', 'symbols', t('math.palette.imaginary-unit.label'), 'ⅈ', String.raw`\mathrm{i}`, [], t('math.palette.imaginary-unit.meaning'), [t('math.palette.imaginary-unit.keyword0'), t('math.palette.imaginary-unit.keyword1')],
    { domain: t('math.paletteDomain.basic.imaginary-unit'), argumentTypes: [], resultType: 'complex', method: 'native', functionUse: false, help: HELP.symbols }),
  // MC-02a: 初等・整数・複素の追加27件（arccos〜cis の24件と、下書きだったRe・Im・共役の実例化）。
  item('arccos', 'functions', t('math.palette.arccos.label'), 'arccos', String.raw`\operatorname{arccos}\left(#0\right)`, ['arccos'], t('math.palette.arccos.meaning'), [t('math.palette.arccos.keyword0'), t('math.palette.arccos.keyword1'), t('math.palette.arccos.keyword2')],
    { domain: t('math.paletteDomain.basic.arccos'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arctan', 'functions', t('math.palette.arctan.label'), 'arctan', String.raw`\operatorname{arctan}\left(#0\right)`, ['arctan'], t('math.palette.arctan.meaning'), [t('math.palette.arctan.keyword0'), t('math.palette.arctan.keyword1'), t('math.palette.arctan.keyword2')],
    { domain: t('math.paletteDomain.basic.arctan'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('cot', 'functions', t('math.palette.cot.label'), 'cot', String.raw`\operatorname{cot}\left(#0\right)`, ['cot'], t('math.palette.cot.meaning'), [t('math.palette.cot.keyword0')],
    { domain: t('math.paletteDomain.basic.cot'), argumentTypes: ['angle'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('sec', 'functions', t('math.palette.sec.label'), 'sec', String.raw`\operatorname{sec}\left(#0\right)`, ['sec'], t('math.palette.sec.meaning'), [t('math.palette.sec.keyword0')],
    { domain: t('math.paletteDomain.basic.sec'), argumentTypes: ['angle'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('csc', 'functions', t('math.palette.csc.label'), 'csc', String.raw`\operatorname{csc}\left(#0\right)`, ['csc'], t('math.palette.csc.meaning'), [t('math.palette.csc.keyword0')],
    { domain: t('math.paletteDomain.basic.csc'), argumentTypes: ['angle'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('cosh', 'functions', t('math.palette.cosh.label'), 'cosh', String.raw`\operatorname{cosh}\left(#0\right)`, ['cosh'], t('math.palette.cosh.meaning'), [t('math.palette.cosh.keyword0')],
    { domain: t('math.paletteDomain.basic.cosh'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('tanh', 'functions', t('math.palette.tanh.label'), 'tanh', String.raw`\operatorname{tanh}\left(#0\right)`, ['tanh'], t('math.palette.tanh.meaning'), [t('math.palette.tanh.keyword0')],
    { domain: t('math.paletteDomain.basic.tanh'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arsinh', 'functions', t('math.palette.arsinh.label'), 'asinh', String.raw`\operatorname{arsinh}\left(#0\right)`, ['arsinh'], t('math.palette.arsinh.meaning'), [t('math.palette.arsinh.keyword0')],
    { domain: t('math.paletteDomain.basic.arsinh'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('arcosh', 'functions', t('math.palette.arcosh.label'), 'acosh', String.raw`\operatorname{arcosh}\left(#0\right)`, ['arcosh'], t('math.palette.arcosh.meaning'), [t('math.palette.arcosh.keyword0')],
    { domain: t('math.paletteDomain.basic.arcosh'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('artanh', 'functions', t('math.palette.artanh.label'), 'atanh', String.raw`\operatorname{artanh}\left(#0\right)`, ['artanh'], t('math.palette.artanh.meaning'), [t('math.palette.artanh.keyword0')],
    { domain: t('math.paletteDomain.basic.artanh'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('exponential', 'functions', t('math.palette.exponential.label'), 'exp', String.raw`\operatorname{exp}\left(#0\right)`, ['exponential'], t('math.palette.exponential.meaning'), [t('math.palette.exponential.keyword0')],
    { domain: t('math.paletteDomain.basic.exponential'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('log-two', 'functions', t('math.palette.log-two.label'), 'log₂', String.raw`\log_{2}\left(#0\right)`, ['log-base'], t('math.palette.log-two.meaning'), [t('math.palette.log-two.keyword0'), t('math.palette.log-two.keyword1')],
    { domain: t('math.paletteDomain.basic.log-two'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('floor', 'basic', t('math.palette.floor.label'), '⌊x⌋', String.raw`\operatorname{floor}\left(#0\right)`, ['floor'], t('math.palette.floor.meaning'), [t('math.palette.floor.keyword0'), t('math.palette.floor.keyword1')],
    { domain: t('math.paletteDomain.basic.floor'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('ceiling', 'basic', t('math.palette.ceiling.label'), '⌈x⌉', String.raw`\operatorname{ceil}\left(#0\right)`, ['ceiling'], t('math.palette.ceiling.meaning'), [t('math.palette.ceiling.keyword0'), t('math.palette.ceiling.keyword1')],
    { domain: t('math.paletteDomain.basic.ceiling'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('round', 'basic', t('math.palette.round.label'), 'round', String.raw`\operatorname{round}\left(#0\right)`, ['round'], t('math.palette.round.meaning'), [t('math.palette.round.keyword0'), t('math.palette.round.keyword1')],
    { domain: t('math.paletteDomain.basic.round'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.paletteArguments }),
  item('sign', 'basic', t('math.palette.sign.label'), 'sgn', String.raw`\operatorname{sign}\left(#0\right)`, ['sign'], t('math.palette.sign.meaning'), [t('math.palette.sign.keyword0')],
    { domain: t('math.paletteDomain.basic.sign'), argumentTypes: ['real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('minimum', 'basic', t('math.palette.minimum.label'), 'min', String.raw`\operatorname{min}\left(#0,#?\right)`, ['minimum'], t('math.palette.minimum.meaning'), [t('math.palette.minimum.keyword0')],
    { domain: t('math.paletteDomain.basic.minimum'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('maximum', 'basic', t('math.palette.maximum.label'), 'max', String.raw`\operatorname{max}\left(#0,#?\right)`, ['maximum'], t('math.palette.maximum.meaning'), [t('math.palette.maximum.keyword0')],
    { domain: t('math.paletteDomain.basic.maximum'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('binomial', 'basic', t('math.palette.binomial.label'), 'nCk', String.raw`\operatorname{binomial}\left(#0,#?\right)`, ['binomial'], t('math.palette.binomial.meaning'), [t('math.palette.binomial.keyword0'), t('math.palette.binomial.keyword1')],
    { domain: t('math.paletteDomain.basic.binomial'), argumentTypes: ['natural', 'natural'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('gcd', 'basic', t('math.palette.gcd.label'), 'gcd', String.raw`\operatorname{gcd}\left(#0,#?\right)`, ['gcd'], t('math.palette.gcd.meaning'), [t('math.palette.gcd.keyword0')],
    { domain: t('math.paletteDomain.basic.gcd'), argumentTypes: ['integer', 'integer'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('lcm', 'basic', t('math.palette.lcm.label'), 'lcm', String.raw`\operatorname{lcm}\left(#0,#?\right)`, ['lcm'], t('math.palette.lcm.meaning'), [t('math.palette.lcm.keyword0')],
    { domain: t('math.paletteDomain.basic.lcm'), argumentTypes: ['integer', 'integer'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('modulo', 'basic', t('math.palette.modulo.label'), 'mod', String.raw`\operatorname{mod}\left(#0,#?\right)`, ['modulo'], t('math.palette.modulo.meaning'), [t('math.palette.modulo.keyword0'), t('math.palette.modulo.keyword1')],
    { domain: t('math.paletteDomain.basic.modulo'), argumentTypes: ['integer', 'integer'], resultType: 'real', method: 'native', functionUse: false, help: HELP.integers }),
  item('argument', 'complex', t('math.palette.argument.label'), 'arg', String.raw`\operatorname{arg}\left(#0\right)`, ['argument'], t('math.palette.argument.meaning'), [t('math.palette.argument.keyword0'), t('math.palette.argument.keyword1')],
    { domain: t('math.paletteDomain.basic.argument'), argumentTypes: ['complex'], resultType: 'real', method: 'native', functionUse: false, help: HELP.complex }),
  item('cis', 'complex', t('math.palette.cis.label'), 'cis', String.raw`\operatorname{cis}\left(#0\right)`, ['cis'], t('math.palette.cis.meaning'), [t('math.palette.cis.keyword0'), t('math.palette.cis.keyword1')],
    { domain: t('math.paletteDomain.basic.cis'), argumentTypes: ['angle'], resultType: 'complex', method: 'native', functionUse: false, help: HELP.complex }),
  // MC-02d (MC-04 gap): hard-to-type constant e, matching pi/imaginary-unit's own symbol entries.
  // ∞ (\infty) was tried and dropped: a bare ∞ evaluates to {status:'invalid',reason:'non-finite'}, not a
  // 'value'-status result (confirmed by the real unit run), so it has no standalone value this catalog can publish;
  // see the final report.
  item('e', 'symbols', t('math.palette.e.label'), 'e', String.raw`\exponentialE`, [], t('math.palette.e.meaning'), [t('math.palette.e.keyword0')],
    { domain: t('math.paletteDomain.basic.e'), argumentTypes: [], resultType: 'real', method: 'native', functionUse: true, help: HELP.symbols }),
  // MC-02e (MC-11): ±・∓ produce status:'multiple' candidates, never a single status:'value' (plusMinus.ts).
  // Not usable inside function plotting until a sign is chosen (confirmed by plusMinus.test.ts).
  item('plus-minus', 'basic', t('math.palette.plus-minus.label'), '±', String.raw`#0\pm#?`, ['plus-minus'], t('math.palette.plus-minus.meaning'), [t('math.palette.plus-minus.keyword0')],
    { domain: t('math.paletteDomain.basic.plus-minus'), argumentTypes: ['real', 'real'], resultType: 'candidates', method: 'native', functionUse: false, help: HELP.plusMinus }),
  item('minus-plus', 'basic', t('math.palette.minus-plus.label'), '∓', String.raw`#0\mp#?`, ['minus-plus'], t('math.palette.minus-plus.meaning'), [t('math.palette.minus-plus.keyword0')],
    { domain: t('math.paletteDomain.basic.minus-plus'), argumentTypes: ['real', 'real'], resultType: 'candidates', method: 'native', functionUse: false, help: HELP.plusMinus }),
];
