import { t } from '../i18n/t.js';
import { mathPaletteItem as item, type MathPaletteCatalogItem } from './mathPaletteGroups.js';

/**
 * 数学の目録の分野別ファイル: 集合・論理・確率統計・方程式と変換。
 * 分野（group）が sets-logic・statistics・equations の項目を置く。文言は i18n/ja/mathPaletteSetsLogic.json、
 * 公開パレットの実例は mathPaletteSetsLogicExamples.ts にある（実例と受入IDが揃った項目だけを公開する）。
 * 各項目は名前・記号・ひな形・必要な演算・意味・検索語と、引数型・結果型・計算方式・関数作図での利用・
 * 説明の節（mathPaletteGroups.ts の MathPaletteFields）を持つ。欄の正しさは mathPaletteExamples.test.ts が実計算で照合する。
 */
/** 説明「構造化した数式と係数を入力する」の見出し（この分野の項目が参照する節）。 */
const HELP = {
  mappings: t('math.paletteHelp.setsLogic.mappings'),
  setBounds: t('math.paletteHelp.setsLogic.setBounds'),
  ode: t('math.paletteHelp.setsLogic.ode'),
  numericRoots: t('math.paletteHelp.setsLogic.numericRoots'),
  systems: t('math.paletteHelp.setsLogic.systems'),
  equations: t('math.paletteHelp.setsLogic.equations'),
  transforms: t('math.paletteHelp.setsLogic.transforms'),
  randomVariables: t('math.paletteHelp.setsLogic.randomVariables'),
  chiSquareTF: t('math.paletteHelp.setsLogic.chiSquareTF'),
  gammaBeta: t('math.paletteHelp.setsLogic.gammaBeta'),
  normal: t('math.paletteHelp.setsLogic.normal'),
  probabilityTables: t('math.paletteHelp.setsLogic.probabilityTables'),
  uniformExponentialPoisson: t('math.paletteHelp.setsLogic.uniformExponentialPoisson'),
  minimumCounts: t('math.paletteHelp.setsLogic.minimumCounts'),
  binomial: t('math.paletteHelp.setsLogic.binomial'),
  statistics: t('math.paletteHelp.setsLogic.statistics'),
  integers: t('math.paletteHelp.setsLogic.integers'),
  paletteArguments: t('math.paletteHelp.setsLogic.paletteArguments'),
  quantifiers: t('math.paletteHelp.setsLogic.quantifiers'),
} as const;

export const MATH_PALETTE_SETS_LOGIC: readonly MathPaletteCatalogItem[] = [
  item('mapping', 'sets-logic', t('math.palette.mapping.label'), '↦', String.raw`\operatorname{mapping}\left(#0,#?,#?,#?\right)`, ['mapping', 'lambda'], t('math.palette.mapping.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.mapping'), argumentTypes: ['expression', 'variable', 'set', 'set'], resultType: 'function', method: 'exact-runtime', functionUse: false, help: HELP.mappings }),
  item('mapping-value', 'sets-logic', t('math.palette.mapping-value.label'), 'mapat', String.raw`\operatorname{mapat}\left(#0,#?\right)`, ['mapping-value'], t('math.palette.mapping-value.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.mapping-value'), argumentTypes: ['function', 'real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.mappings }),
  item('mapping-compose', 'sets-logic', t('math.palette.mapping-compose.label'), '∘', String.raw`\operatorname{composemaps}\left(#0,#?\right)`, ['mapping-compose'], t('math.palette.mapping-compose.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.mapping-compose'), argumentTypes: ['function', 'function'], resultType: 'function', method: 'exact-runtime', functionUse: false, help: HELP.mappings }),
  item('mapping-inverse', 'sets-logic', t('math.palette.mapping-inverse.label'), 'inversemap', String.raw`\operatorname{inversemap}\left(#0\right)`, ['mapping-inverse'], t('math.palette.mapping-inverse.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.mapping-inverse'), argumentTypes: ['function'], resultType: 'function', method: 'exact-runtime', functionUse: false, help: HELP.mappings }),
  item('mapping-image', 'sets-logic', t('math.palette.mapping-image.label'), 'mapimage', String.raw`\operatorname{mapimage}\left(#0,#?\right)`, ['mapping-image'], t('math.palette.mapping-image.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.mapping-image'), argumentTypes: ['function', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.mappings }),
  item('mapping-preimage', 'sets-logic', t('math.palette.mapping-preimage.label'), 'mappreimage', String.raw`\operatorname{mappreimage}\left(#0,#?\right)`, ['mapping-preimage'], t('math.palette.mapping-preimage.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.mapping-preimage'), argumentTypes: ['function', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.mappings }),
  item('set-supremum', 'sets-logic', t('math.palette.set-supremum.label'), 'sup', String.raw`\operatorname{sup}\left(#0\right)`, ['set-supremum'], t('math.palette.set-supremum.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.set-supremum'), argumentTypes: ['set'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('set-infimum', 'sets-logic', t('math.palette.set-infimum.label'), 'inf', String.raw`\operatorname{inf}\left(#0\right)`, ['set-infimum'], t('math.palette.set-infimum.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.set-infimum'), argumentTypes: ['set'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('set-maximum', 'sets-logic', t('math.palette.set-maximum.label'), 'setmax', String.raw`\operatorname{setmax}\left(#0\right)`, ['set-maximum'], t('math.palette.set-maximum.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.set-maximum'), argumentTypes: ['set'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('set-minimum', 'sets-logic', t('math.palette.set-minimum.label'), 'setmin', String.raw`\operatorname{setmin}\left(#0\right)`, ['set-minimum'], t('math.palette.set-minimum.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.set-minimum'), argumentTypes: ['set'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('solve-ode', 'equations', t('math.palette.solve-ode.label'), 'odesolve', String.raw`\operatorname{odesolve}\left(#0,#?,#?,#?\right)`, ['solve-ode', 'lambda'], t('math.palette.solve-ode.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.solve-ode'), argumentTypes: ['equation-list', 'variable', 'variable-list', 'list'], resultType: 'ode-solutions', method: 'exact-runtime', functionUse: false, help: HELP.ode }),
  item('ode-value', 'equations', t('math.palette.ode-value.label'), 'odeat', String.raw`\operatorname{odeat}\left(#0,#?,#?,#?\right)`, ['ode-value'], t('math.palette.ode-value.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.ode-value'), argumentTypes: ['ode-solutions', 'natural', 'list', 'real'], resultType: 'vector', method: 'exact-runtime', functionUse: false, help: HELP.ode }),
  item('numerical-roots', 'equations', t('math.palette.numerical-roots.label'), 'numericroots', String.raw`\operatorname{numericroots}\left(#0,#?,#?,#?,#?\right)`, ['numerical-roots', 'lambda'], t('math.palette.numerical-roots.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.numerical-roots'), argumentTypes: ['expression', 'variable', 'real', 'real', 'real'], resultType: 'root-intervals', method: 'native', functionUse: false, help: HELP.numericRoots }),
  item('root-interval', 'equations', t('math.palette.root-interval.label'), 'rootinterval', String.raw`\operatorname{rootinterval}\left(#0,#?\right)`, ['root-interval'], t('math.palette.root-interval.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.root-interval'), argumentTypes: ['root-intervals', 'natural'], resultType: 'vector', method: 'native', functionUse: false, help: HELP.numericRoots }),
  item('solve-system', 'equations', t('math.palette.solve-system.label'), 'solvesystem', String.raw`\operatorname{solvesystem}\left(#0,#?,#?\right)`, ['solve-system', 'lambda'], t('math.palette.solve-system.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.solve-system'), argumentTypes: ['equation-list', 'variable-list', 'set'], resultType: 'equation-system', method: 'exact-runtime', functionUse: false, help: HELP.systems }),
  item('system-solution', 'equations', t('math.palette.system-solution.label'), 'systemsolution', String.raw`\operatorname{systemsolution}\left(#0,#?,#?\right)`, ['system-solution'], t('math.palette.system-solution.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.system-solution'), argumentTypes: ['equation-system', 'natural', 'list'], resultType: 'vector', method: 'exact-runtime', functionUse: false, help: HELP.systems }),
  item('solve-equation', 'equations', t('math.palette.solve-equation.label'), 'solve', String.raw`\operatorname{solve}\left(#0,#?,#?\right)`, ['solve-equation', 'lambda'], t('math.palette.solve-equation.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.solve-equation'), argumentTypes: ['condition', 'variable', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.equations }),
  item('polynomial-roots', 'equations', t('math.palette.polynomial-roots.label'), 'polynomialroots', String.raw`\operatorname{polynomialroots}\left(#0,#?,#?\right)`, ['polynomial-roots', 'lambda'], t('math.palette.polynomial-roots.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.polynomial-roots'), argumentTypes: ['expression', 'variable', 'set'], resultType: 'matrix', method: 'exact-runtime', functionUse: false, help: HELP.equations }),
  item('solution-value', 'equations', t('math.palette.solution-value.label'), 'solution', String.raw`\operatorname{solution}\left(#0,#?\right)`, ['solution-value'], t('math.palette.solution-value.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.solution-value'), argumentTypes: ['set', 'natural'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.equations }),
  item('fourier-transform', 'equations', t('math.palette.fourier-transform.label'), 'fourier', String.raw`\operatorname{fourier}\left(#0,#?,#?\right)`, ['fourier-transform', 'lambda'], t('math.palette.fourier-transform.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.fourier-transform'), argumentTypes: ['expression', 'variable', 'variable'], resultType: 'transform', method: 'exact-runtime', functionUse: false, help: HELP.transforms }),
  item('inverse-fourier-transform', 'equations', t('math.palette.inverse-fourier-transform.label'), 'inversefourier', String.raw`\operatorname{inversefourier}\left(#0,#?,#?\right)`, ['inverse-fourier-transform', 'lambda'], t('math.palette.inverse-fourier-transform.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.inverse-fourier-transform'), argumentTypes: ['expression', 'variable', 'variable'], resultType: 'transform', method: 'exact-runtime', functionUse: false, help: HELP.transforms }),
  item('laplace-transform', 'equations', t('math.palette.laplace-transform.label'), 'laplace', String.raw`\operatorname{laplace}\left(#0,#?,#?\right)`, ['laplace-transform', 'lambda'], t('math.palette.laplace-transform.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.laplace-transform'), argumentTypes: ['expression', 'variable', 'variable'], resultType: 'transform', method: 'exact-runtime', functionUse: false, help: HELP.transforms }),
  item('inverse-laplace-transform', 'equations', t('math.palette.inverse-laplace-transform.label'), 'inverselaplace', String.raw`\operatorname{inverselaplace}\left(#0,#?,#?\right)`, ['inverse-laplace-transform', 'lambda'], t('math.palette.inverse-laplace-transform.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.inverse-laplace-transform'), argumentTypes: ['expression', 'variable', 'variable'], resultType: 'transform', method: 'exact-runtime', functionUse: false, help: HELP.transforms }),
  item('z-transform', 'equations', t('math.palette.z-transform.label'), 'ztransform', String.raw`\operatorname{ztransform}\left(#0,#?,#?\right)`, ['z-transform', 'lambda'], t('math.palette.z-transform.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.z-transform'), argumentTypes: ['expression', 'variable', 'variable'], resultType: 'transform', method: 'exact-runtime', functionUse: false, help: HELP.transforms }),
  item('transform-value', 'equations', t('math.palette.transform-value.label'), 'transformat', String.raw`\operatorname{transformat}\left(#0,#?\right)`, ['transform-value'], t('math.palette.transform-value.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.transform-value'), argumentTypes: ['transform', 'real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.transforms }),
  item('event-probability', 'statistics', t('math.palette.event-probability.label'), 'probability', String.raw`\operatorname{probability}\left(#0,#?,#?\right)`, ['event-probability'], t('math.palette.event-probability.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.event-probability'), argumentTypes: ['condition', 'variable-list', 'distribution'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('given-probability', 'statistics', t('math.palette.given-probability.label'), 'givenprobability', String.raw`\operatorname{givenprobability}\left(#0,#?,#?,#?\right)`, ['given-probability'], t('math.palette.given-probability.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.given-probability'), argumentTypes: ['condition', 'condition', 'variable-list', 'distribution'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('random-expectation', 'statistics', t('math.palette.random-expectation.label'), 'randomexpectation', String.raw`\operatorname{randomexpectation}\left(#0,#?,#?\right)`, ['random-expectation'], t('math.palette.random-expectation.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.random-expectation'), argumentTypes: ['expression', 'variable-list', 'distribution'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('random-variance', 'statistics', t('math.palette.random-variance.label'), 'randomvariance', String.raw`\operatorname{randomvariance}\left(#0,#?,#?\right)`, ['random-variance'], t('math.palette.random-variance.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.random-variance'), argumentTypes: ['expression', 'variable-list', 'distribution'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('random-covariance', 'statistics', t('math.palette.random-covariance.label'), 'randomcovariance', String.raw`\operatorname{randomcovariance}\left(#0,#?,#?,#?\right)`, ['random-covariance'], t('math.palette.random-covariance.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.random-covariance'), argumentTypes: ['expression', 'expression', 'variable-list', 'distribution'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('random-correlation', 'statistics', t('math.palette.random-correlation.label'), 'randomcorrelation', String.raw`\operatorname{randomcorrelation}\left(#0,#?,#?,#?\right)`, ['random-correlation'], t('math.palette.random-correlation.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.random-correlation'), argumentTypes: ['expression', 'expression', 'variable-list', 'distribution'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('independent-events', 'statistics', t('math.palette.independent-events.label'), 'independentevents', String.raw`\operatorname{independentevents}\left(#0,#?,#?,#?\right)`, ['independent-events'], t('math.palette.independent-events.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.independent-events'), argumentTypes: ['condition', 'condition', 'variable-list', 'distribution'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('independent-variables', 'statistics', t('math.palette.independent-variables.label'), 'independentvariables', String.raw`\operatorname{independentvariables}\left(#0,#?,#?,#?\right)`, ['independent-variables'], t('math.palette.independent-variables.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.independent-variables'), argumentTypes: ['expression', 'expression', 'variable-list', 'distribution'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('chi-square-pdf', 'statistics', t('math.palette.chi-square-pdf.label'), 'chisquarepdf', String.raw`\operatorname{chisquarepdf}\left(#0,#?\right)`, ['chi-square-pdf'], t('math.palette.chi-square-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.chi-square-pdf'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('chi-square-cdf', 'statistics', t('math.palette.chi-square-cdf.label'), 'chisquarecdf', String.raw`\operatorname{chisquarecdf}\left(#0,#?\right)`, ['chi-square-cdf'], t('math.palette.chi-square-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.chi-square-cdf'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('chi-square-quantile', 'statistics', t('math.palette.chi-square-quantile.label'), 'chisquarequantile', String.raw`\operatorname{chisquarequantile}\left(#0,#?\right)`, ['chi-square-quantile'], t('math.palette.chi-square-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.chi-square-quantile'), argumentTypes: ['real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('t-pdf', 'statistics', t('math.palette.t-pdf.label'), 'tpdf', String.raw`\operatorname{tpdf}\left(#0,#?\right)`, ['t-pdf'], t('math.palette.t-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.t-pdf'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('t-cdf', 'statistics', t('math.palette.t-cdf.label'), 'tcdf', String.raw`\operatorname{tcdf}\left(#0,#?\right)`, ['t-cdf'], t('math.palette.t-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.t-cdf'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('t-quantile', 'statistics', t('math.palette.t-quantile.label'), 'tquantile', String.raw`\operatorname{tquantile}\left(#0,#?\right)`, ['t-quantile'], t('math.palette.t-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.t-quantile'), argumentTypes: ['real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('f-pdf', 'statistics', t('math.palette.f-pdf.label'), 'fpdf', String.raw`\operatorname{fpdf}\left(#0,#?,#?\right)`, ['f-pdf'], t('math.palette.f-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.f-pdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('f-cdf', 'statistics', t('math.palette.f-cdf.label'), 'fcdf', String.raw`\operatorname{fcdf}\left(#0,#?,#?\right)`, ['f-cdf'], t('math.palette.f-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.f-cdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('f-quantile', 'statistics', t('math.palette.f-quantile.label'), 'fquantile', String.raw`\operatorname{fquantile}\left(#0,#?,#?\right)`, ['f-quantile'], t('math.palette.f-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.f-quantile'), argumentTypes: ['real', 'real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.chiSquareTF }),
  item('gamma-pdf', 'statistics', t('math.palette.gamma-pdf.label'), 'gammapdf', String.raw`\operatorname{gammapdf}\left(#0,#?,#?\right)`, ['gamma-pdf'], t('math.palette.gamma-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.gamma-pdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.gammaBeta }),
  item('gamma-cdf', 'statistics', t('math.palette.gamma-cdf.label'), 'gammacdf', String.raw`\operatorname{gammacdf}\left(#0,#?,#?\right)`, ['gamma-cdf'], t('math.palette.gamma-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.gamma-cdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.gammaBeta }),
  item('gamma-quantile', 'statistics', t('math.palette.gamma-quantile.label'), 'gammaquantile', String.raw`\operatorname{gammaquantile}\left(#0,#?,#?\right)`, ['gamma-quantile'], t('math.palette.gamma-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.gamma-quantile'), argumentTypes: ['real', 'real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.gammaBeta }),
  item('beta-pdf', 'statistics', t('math.palette.beta-pdf.label'), 'betapdf', String.raw`\operatorname{betapdf}\left(#0,#?,#?\right)`, ['beta-pdf'], t('math.palette.beta-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.beta-pdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.gammaBeta }),
  item('beta-cdf', 'statistics', t('math.palette.beta-cdf.label'), 'betacdf', String.raw`\operatorname{betacdf}\left(#0,#?,#?\right)`, ['beta-cdf'], t('math.palette.beta-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.beta-cdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.gammaBeta }),
  item('beta-quantile', 'statistics', t('math.palette.beta-quantile.label'), 'betaquantile', String.raw`\operatorname{betaquantile}\left(#0,#?,#?\right)`, ['beta-quantile'], t('math.palette.beta-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.beta-quantile'), argumentTypes: ['real', 'real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.gammaBeta }),
  item('normal-pdf', 'statistics', t('math.palette.normal-pdf.label'), 'normalpdf', String.raw`\operatorname{normalpdf}\left(#0,#?,#?\right)`, ['normal-pdf'], t('math.palette.normal-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.normal-pdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.normal }),
  item('normal-cdf', 'statistics', t('math.palette.normal-cdf.label'), 'normalcdf', String.raw`\operatorname{normalcdf}\left(#0,#?,#?\right)`, ['normal-cdf'], t('math.palette.normal-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.normal-cdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.normal }),
  item('normal-quantile', 'statistics', t('math.palette.normal-quantile.label'), 'normalquantile', String.raw`\operatorname{normalquantile}\left(#0,#?,#?\right)`, ['normal-quantile'], t('math.palette.normal-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.normal-quantile'), argumentTypes: ['real', 'real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.normal }),
  item('expectation', 'statistics', t('math.palette.expectation.label'), 'expectation', String.raw`\operatorname{expectation}\left(#0,#?\right)`, ['expectation'], t('math.palette.expectation.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.expectation'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.probabilityTables }),
  item('probability-variance', 'statistics', t('math.palette.probability-variance.label'), 'probabilityvariance', String.raw`\operatorname{probabilityvariance}\left(#0,#?\right)`, ['probability-variance'], t('math.palette.probability-variance.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.probability-variance'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.probabilityTables }),
  item('conditional-probability', 'statistics', t('math.palette.conditional-probability.label'), 'conditionalprobability', String.raw`\operatorname{conditionalprobability}\left(#0,#?\right)`, ['conditional-probability'], t('math.palette.conditional-probability.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.conditional-probability'), argumentTypes: ['probability', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.probabilityTables }),
  item('uniform-pdf', 'statistics', t('math.palette.uniform-pdf.label'), 'uniformpdf', String.raw`\operatorname{uniformpdf}\left(#0,#?,#?\right)`, ['uniform-pdf'], t('math.palette.uniform-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.uniform-pdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('uniform-cdf', 'statistics', t('math.palette.uniform-cdf.label'), 'uniformcdf', String.raw`\operatorname{uniformcdf}\left(#0,#?,#?\right)`, ['uniform-cdf'], t('math.palette.uniform-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.uniform-cdf'), argumentTypes: ['real', 'real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('uniform-quantile', 'statistics', t('math.palette.uniform-quantile.label'), 'uniformquantile', String.raw`\operatorname{uniformquantile}\left(#0,#?,#?\right)`, ['uniform-quantile'], t('math.palette.uniform-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.uniform-quantile'), argumentTypes: ['real', 'real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('exponential-pdf', 'statistics', t('math.palette.exponential-pdf.label'), 'exponentialpdf', String.raw`\operatorname{exponentialpdf}\left(#0,#?\right)`, ['exponential-pdf'], t('math.palette.exponential-pdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.exponential-pdf'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('exponential-cdf', 'statistics', t('math.palette.exponential-cdf.label'), 'exponentialcdf', String.raw`\operatorname{exponentialcdf}\left(#0,#?\right)`, ['exponential-cdf'], t('math.palette.exponential-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.exponential-cdf'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('exponential-quantile', 'statistics', t('math.palette.exponential-quantile.label'), 'exponentialquantile', String.raw`\operatorname{exponentialquantile}\left(#0,#?\right)`, ['exponential-quantile'], t('math.palette.exponential-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.exponential-quantile'), argumentTypes: ['real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('binomial-quantile', 'statistics', t('math.palette.binomial-quantile.label'), 'binomialquantile', String.raw`\operatorname{binomialquantile}\left(#0,#?,#?\right)`, ['binomial-quantile'], t('math.palette.binomial-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.binomial-quantile'), argumentTypes: ['natural', 'probability', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.minimumCounts }),
  item('poisson-quantile', 'statistics', t('math.palette.poisson-quantile.label'), 'poissonquantile', String.raw`\operatorname{poissonquantile}\left(#0,#?\right)`, ['poisson-quantile'], t('math.palette.poisson-quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.poisson-quantile'), argumentTypes: ['real', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.minimumCounts }),
  item('poisson-pmf', 'statistics', t('math.palette.poisson-pmf.label'), 'poissonpmf', String.raw`\operatorname{poissonpmf}\left(#0,#?\right)`, ['poisson-pmf'], t('math.palette.poisson-pmf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.poisson-pmf'), argumentTypes: ['real', 'natural'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('poisson-cdf', 'statistics', t('math.palette.poisson-cdf.label'), 'poissoncdf', String.raw`\operatorname{poissoncdf}\left(#0,#?\right)`, ['poisson-cdf'], t('math.palette.poisson-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.poisson-cdf'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.uniformExponentialPoisson }),
  item('divides', 'sets-logic', t('math.palette.divides.label'), 'a|b', String.raw`\operatorname{divides}\left(#0,#?\right)`, ['divides'], t('math.palette.divides.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.divides'), argumentTypes: ['integer', 'integer'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.integers }),
  item('congruent-modulo', 'sets-logic', t('math.palette.congruent-modulo.label'), 'a≡b (mod m)', String.raw`\operatorname{congruentmodulo}\left(#0,#?,#?\right)`, ['congruent-modulo'], t('math.palette.congruent-modulo.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.congruent-modulo'), argumentTypes: ['integer', 'integer', 'integer'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.integers }),
  item('is-prime', 'sets-logic', t('math.palette.is-prime.label'), 'prime?', String.raw`\operatorname{isprime}\left(#0\right)`, ['is-prime'], t('math.palette.is-prime.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.is-prime'), argumentTypes: ['integer'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.integers }),
  item('binomial-pmf', 'statistics', t('math.palette.binomial-pmf.label'), 'P(X=k)', String.raw`\operatorname{binomialpmf}\left(#0,#?,#?\right)`, ['binomial-pmf'], t('math.palette.binomial-pmf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.binomial-pmf'), argumentTypes: ['natural', 'probability', 'natural'], resultType: 'real', method: 'native', functionUse: false, help: HELP.binomial }),
  item('binomial-cdf', 'statistics', t('math.palette.binomial-cdf.label'), 'P(X≤x)', String.raw`\operatorname{binomialcdf}\left(#0,#?,#?\right)`, ['binomial-cdf'], t('math.palette.binomial-cdf.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.binomial-cdf'), argumentTypes: ['natural', 'probability', 'real'], resultType: 'real', method: 'native', functionUse: false, help: HELP.binomial }),
  item('mean', 'statistics', t('math.palette.mean.label'), 'mean', String.raw`\operatorname{mean}\left(#0\right)`, ['mean'], t('math.palette.mean.meaning'), [t('math.palette.mean.keyword0'), t('math.palette.mean.keyword1')],
    { domain: t('math.paletteDomain.setsLogic.mean'), argumentTypes: ['vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('median', 'statistics', t('math.palette.median.label'), 'median', String.raw`\operatorname{median}\left(#0\right)`, ['median'], t('math.palette.median.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.median'), argumentTypes: ['vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('modes', 'statistics', t('math.palette.modes.label'), 'modes', String.raw`\operatorname{modes}\left(#0\right)`, ['modes'], t('math.palette.modes.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.modes'), argumentTypes: ['vector'], resultType: 'vector', method: 'native', functionUse: false, help: HELP.statistics }),
  item('quantile', 'statistics', t('math.palette.quantile.label'), 'quantile', String.raw`\operatorname{quantile}\left(#0,#?\right)`, ['quantile'], t('math.palette.quantile.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.quantile'), argumentTypes: ['vector', 'probability'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('population-variance', 'statistics', t('math.palette.population-variance.label'), 'σ²', String.raw`\operatorname{populationvariance}\left(#0\right)`, ['population-variance'], t('math.palette.population-variance.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.population-variance'), argumentTypes: ['vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('sample-variance', 'statistics', t('math.palette.sample-variance.label'), 's²', String.raw`\operatorname{samplevariance}\left(#0\right)`, ['sample-variance'], t('math.palette.sample-variance.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.sample-variance'), argumentTypes: ['vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('population-standard-deviation', 'statistics', t('math.palette.population-standard-deviation.label'), 'σ', String.raw`\operatorname{populationstandarddeviation}\left(#0\right)`, ['population-standard-deviation'], t('math.palette.population-standard-deviation.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.population-standard-deviation'), argumentTypes: ['vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('sample-standard-deviation', 'statistics', t('math.palette.sample-standard-deviation.label'), 's', String.raw`\operatorname{samplestandarddeviation}\left(#0\right)`, ['sample-standard-deviation'], t('math.palette.sample-standard-deviation.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.sample-standard-deviation'), argumentTypes: ['vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('population-covariance', 'statistics', t('math.palette.population-covariance.label'), 'covₙ', String.raw`\operatorname{populationcovariance}\left(#0,#?\right)`, ['population-covariance'], t('math.palette.population-covariance.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.population-covariance'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('sample-covariance', 'statistics', t('math.palette.sample-covariance.label'), 'covₙ₋₁', String.raw`\operatorname{samplecovariance}\left(#0,#?\right)`, ['sample-covariance'], t('math.palette.sample-covariance.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.sample-covariance'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('correlation', 'statistics', t('math.palette.correlation.label'), 'r', String.raw`\operatorname{correlation}\left(#0,#?\right)`, ['correlation'], t('math.palette.correlation.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.correlation'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('regression-slope', 'statistics', t('math.palette.regression-slope.label'), 'a', String.raw`\operatorname{regressionslope}\left(#0,#?\right)`, ['regression-slope'], t('math.palette.regression-slope.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.regression-slope'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('regression-intercept', 'statistics', t('math.palette.regression-intercept.label'), 'b', String.raw`\operatorname{regressionintercept}\left(#0,#?\right)`, ['regression-intercept'], t('math.palette.regression-intercept.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.regression-intercept'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('r-squared', 'statistics', t('math.palette.r-squared.label'), 'R²', String.raw`\operatorname{rsquared}\left(#0,#?\right)`, ['r-squared'], t('math.palette.r-squared.meaning'), [],
    { domain: t('math.paletteDomain.setsLogic.r-squared'), argumentTypes: ['vector', 'vector'], resultType: 'real', method: 'native', functionUse: false, help: HELP.statistics }),
  item('intersection', 'sets-logic', t('math.palette.intersection.label'), '∩', String.raw`#0\cap #?`, ['intersection'], t('math.palette.intersection.meaning'), [t('math.palette.intersection.keyword0'), t('math.palette.intersection.keyword1')],
    // set-minus/union/intersection route through containsSetCalculation into the exact runtime (setBounds.ts, mathBackendResult.ts); the
    // native scalar box never reduces a Union/Intersection node to a value. Corrected from the MC-03 draft's 'native' when adding the example.
    { domain: t('math.paletteDomain.setsLogic.intersection'), argumentTypes: ['set', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('union', 'sets-logic', t('math.palette.union.label'), '∪', String.raw`#0\cup #?`, ['union'], t('math.palette.union.meaning'), [t('math.palette.union.keyword0'), t('math.palette.union.keyword1')],
    { domain: t('math.paletteDomain.setsLogic.union'), argumentTypes: ['set', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('cases', 'sets-logic', t('math.palette.cases.label'), 'cases', String.raw`\begin{cases}#?&#?\\#?&#?\end{cases}`, ['which'], t('math.palette.cases.meaning'), [t('math.palette.cases.keyword0'), t('math.palette.cases.keyword1')],
    // functionUse: 実計算で確認(mathPaletteExamples.test.ts)した結果true。条件がT等の作図変数に依存しない場合はpruneMathPiecewise.ts等で
    // 選んだ枝だけに整理されてから関数作図の式へ渡るため使える。MC-03の下書きの暫定値falseを実例追加時に実測へ合わせて修正。
    { domain: t('math.paletteDomain.setsLogic.cases'), argumentTypes: ['expression', 'condition', 'expression', 'condition'], resultType: 'real', method: 'native', functionUse: true, help: HELP.paletteArguments }),
  item('equal', 'equations', t('math.palette.equal.label'), '=', String.raw`#0=#?`, ['equal'], t('math.palette.equal.meaning'), [t('math.palette.equal.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.equal'), argumentTypes: ['expression', 'expression'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  // 24-08・25-11・26-09（math-add-coverage.md §7.2 MC-02c）: 比較・論理・集合・分布宣言の追加。
  // 比較・論理はnativeMathBackend.tsのbooleanOperationで、集合はcas_sets.py（exact-runtime）とmathBackendResult.tsの定数一覧で実装済み。
  item('not-equal', 'sets-logic', t('math.palette.not-equal.label'), '≠', String.raw`#0\neq #?`, ['not-equal'], t('math.palette.not-equal.meaning'), [t('math.palette.not-equal.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.not-equal'), argumentTypes: ['expression', 'expression'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('less', 'sets-logic', t('math.palette.less.label'), '<', String.raw`#0<#?`, ['less'], t('math.palette.less.meaning'), [t('math.palette.less.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.less'), argumentTypes: ['expression', 'expression'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('less-equal', 'sets-logic', t('math.palette.less-equal.label'), '≤', String.raw`#0\leq #?`, ['less-equal'], t('math.palette.less-equal.meaning'), [t('math.palette.less-equal.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.less-equal'), argumentTypes: ['expression', 'expression'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('greater', 'sets-logic', t('math.palette.greater.label'), '>', String.raw`#0>#?`, ['greater'], t('math.palette.greater.meaning'), [t('math.palette.greater.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.greater'), argumentTypes: ['expression', 'expression'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('greater-equal', 'sets-logic', t('math.palette.greater-equal.label'), '≥', String.raw`#0\geq #?`, ['greater-equal'], t('math.palette.greater-equal.meaning'), [t('math.palette.greater-equal.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.greater-equal'), argumentTypes: ['expression', 'expression'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('and', 'sets-logic', t('math.palette.and.label'), '∧', String.raw`#0\land #?`, ['and'], t('math.palette.and.meaning'), [t('math.palette.and.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.and'), argumentTypes: ['boolean', 'boolean'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('or', 'sets-logic', t('math.palette.or.label'), '∨', String.raw`#0\lor #?`, ['or'], t('math.palette.or.meaning'), [t('math.palette.or.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.or'), argumentTypes: ['boolean', 'boolean'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('not', 'sets-logic', t('math.palette.not.label'), '¬', String.raw`\neg #0`, ['not'], t('math.palette.not.meaning'), [t('math.palette.not.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.not'), argumentTypes: ['boolean'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('implies', 'sets-logic', t('math.palette.implies.label'), '⇒', String.raw`#0\implies #?`, ['implies'], t('math.palette.implies.meaning'), [t('math.palette.implies.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.implies'), argumentTypes: ['boolean', 'boolean'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('equivalent', 'sets-logic', t('math.palette.equivalent.label'), '⇔', String.raw`#0\iff #?`, ['equivalent'], t('math.palette.equivalent.meaning'), [t('math.palette.equivalent.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.equivalent'), argumentTypes: ['boolean', 'boolean'], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('empty-set', 'sets-logic', t('math.palette.empty-set.label'), '∅', String.raw`\emptyset`, [], t('math.palette.empty-set.meaning'), [t('math.palette.empty-set.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.empty-set'), argumentTypes: [], resultType: 'set', method: 'native', functionUse: false, help: HELP.setBounds }),
  item('natural-numbers', 'sets-logic', t('math.palette.natural-numbers.label'), 'ℕ', String.raw`\mathbb{N}`, [], t('math.palette.natural-numbers.meaning'), [t('math.palette.natural-numbers.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.natural-numbers'), argumentTypes: [], resultType: 'set', method: 'native', functionUse: false, help: HELP.setBounds }),
  item('integer-numbers', 'sets-logic', t('math.palette.integer-numbers.label'), 'ℤ', String.raw`\mathbb{Z}`, [], t('math.palette.integer-numbers.meaning'), [t('math.palette.integer-numbers.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.integer-numbers'), argumentTypes: [], resultType: 'set', method: 'native', functionUse: false, help: HELP.setBounds }),
  item('rational-numbers', 'sets-logic', t('math.palette.rational-numbers.label'), 'ℚ', String.raw`\mathbb{Q}`, [], t('math.palette.rational-numbers.meaning'), [t('math.palette.rational-numbers.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.rational-numbers'), argumentTypes: [], resultType: 'set', method: 'native', functionUse: false, help: HELP.setBounds }),
  item('real-numbers', 'sets-logic', t('math.palette.real-numbers.label'), 'ℝ', String.raw`\mathbb{R}`, [], t('math.palette.real-numbers.meaning'), [t('math.palette.real-numbers.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.real-numbers'), argumentTypes: [], resultType: 'set', method: 'native', functionUse: false, help: HELP.setBounds }),
  item('complex-numbers', 'sets-logic', t('math.palette.complex-numbers.label'), 'ℂ', String.raw`\mathbb{C}`, [], t('math.palette.complex-numbers.meaning'), [t('math.palette.complex-numbers.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.complex-numbers'), argumentTypes: [], resultType: 'set', method: 'native', functionUse: false, help: HELP.setBounds }),
  item('element', 'sets-logic', t('math.palette.element.label'), '∈', String.raw`#0\in #?`, ['element'], t('math.palette.element.meaning'), [t('math.palette.element.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.element'), argumentTypes: ['real', 'set'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('set-minus', 'sets-logic', t('math.palette.set-minus.label'), '∖', String.raw`#0\setminus #?`, ['set-minus'], t('math.palette.set-minus.meaning'), [t('math.palette.set-minus.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.set-minus'), argumentTypes: ['set', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('normal-distribution', 'statistics', t('math.palette.normal-distribution.label'), 'Normal(μ,σ)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{normaldistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'normal-distribution'],
    t('math.palette.normal-distribution.meaning'), [t('math.palette.normal-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.normal-distribution'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('uniform-distribution', 'statistics', t('math.palette.uniform-distribution.label'), 'Uniform(a,b)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{uniformdistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'uniform-distribution'],
    t('math.palette.uniform-distribution.meaning'), [t('math.palette.uniform-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.uniform-distribution'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('exponential-distribution', 'statistics', t('math.palette.exponential-distribution.label'), 'Exp(rate)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{exponentialdistribution}\left(#0\right)\right)`, ['random-expectation', 'exponential-distribution'],
    t('math.palette.exponential-distribution.meaning'), [t('math.palette.exponential-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.exponential-distribution'), argumentTypes: ['real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('gamma-distribution', 'statistics', t('math.palette.gamma-distribution.label'), 'Gamma(k,θ)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{gammadistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'gamma-distribution'],
    t('math.palette.gamma-distribution.meaning'), [t('math.palette.gamma-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.gamma-distribution'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('beta-distribution', 'statistics', t('math.palette.beta-distribution.label'), 'Beta(a,b)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{betadistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'beta-distribution'],
    t('math.palette.beta-distribution.meaning'), [t('math.palette.beta-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.beta-distribution'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('chisquare-distribution', 'statistics', t('math.palette.chisquare-distribution.label'), 'χ²(df)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{chisquaredistribution}\left(#0\right)\right)`, ['random-expectation', 'chisquare-distribution'],
    t('math.palette.chisquare-distribution.meaning'), [t('math.palette.chisquare-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.chisquare-distribution'), argumentTypes: ['real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('t-distribution', 'statistics', t('math.palette.t-distribution.label'), 't(df)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{tdistribution}\left(#0\right)\right)`, ['random-expectation', 't-distribution'],
    t('math.palette.t-distribution.meaning'), [t('math.palette.t-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.t-distribution'), argumentTypes: ['real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('f-distribution', 'statistics', t('math.palette.f-distribution.label'), 'F(d1,d2)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{fdistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'f-distribution'],
    t('math.palette.f-distribution.meaning'), [t('math.palette.f-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.f-distribution'), argumentTypes: ['real', 'real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('binomial-distribution', 'statistics', t('math.palette.binomial-distribution.label'), 'Binomial(n,p)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{binomialdistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'binomial-distribution'],
    t('math.palette.binomial-distribution.meaning'), [t('math.palette.binomial-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.binomial-distribution'), argumentTypes: ['natural', 'probability'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('poisson-distribution', 'statistics', t('math.palette.poisson-distribution.label'), 'Poisson(λ)',
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{poissondistribution}\left(#0\right)\right)`, ['random-expectation', 'poisson-distribution'],
    t('math.palette.poisson-distribution.meaning'), [t('math.palette.poisson-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.poisson-distribution'), argumentTypes: ['real'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('finite-distribution', 'statistics', t('math.palette.finite-distribution.label'), t('math.palette.finite-distribution.symbol'),
    String.raw`\operatorname{randomexpectation}\left(x,[x],\operatorname{finitedistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'finite-distribution'],
    t('math.palette.finite-distribution.meaning'), [t('math.palette.finite-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.finite-distribution'), argumentTypes: ['list', 'list'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('joint-finite-distribution', 'statistics', t('math.palette.joint-finite-distribution.label'), t('math.palette.joint-finite-distribution.symbol'),
    String.raw`\operatorname{randomexpectation}\left(x+y,[x,y],\operatorname{jointfinitedistribution}\left(#0,#?\right)\right)`, ['random-expectation', 'joint-finite-distribution'],
    t('math.palette.joint-finite-distribution.meaning'), [t('math.palette.joint-finite-distribution.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.joint-finite-distribution'), argumentTypes: ['list', 'list'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('independent-distributions', 'statistics', t('math.palette.independent-distributions.label'), t('math.palette.independent-distributions.symbol'),
    String.raw`\operatorname{randomexpectation}\left(x+y,[x,y],\operatorname{independentdistributions}\left(#0\right)\right)`, ['random-expectation', 'independent-distributions'],
    t('math.palette.independent-distributions.meaning'), [t('math.palette.independent-distributions.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.independent-distributions'), argumentTypes: ['list'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.randomVariables }),
  item('partial-equations', 'equations', t('math.palette.partial-equations.label'), 'PDE',
    String.raw`\operatorname{pde}\left(#0,#?,#?,#?\right)`, ['partial-equations'],
    t('math.palette.partial-equations.meaning'), [t('math.palette.partial-equations.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.partial-equations'), argumentTypes: ['equation-list', 'variable-list', 'variable-list', 'list'], resultType: 'symbolic',
      method: 'exact-runtime', functionUse: false, help: t('math.paletteHelp.setsLogic.partialEquations') }),
  // MC-02d (MC-23): set relations, sharing element/set-minus/union/intersection's exact-runtime set engine.
  item('not-element', 'sets-logic', t('math.palette.not-element.label'), '∉', String.raw`#0\notin #?`, ['not-element'], t('math.palette.not-element.meaning'), [t('math.palette.not-element.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.not-element'), argumentTypes: ['real', 'set'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('subset', 'sets-logic', t('math.palette.subset.label'), '⊂', String.raw`#0\subset #?`, ['subset'], t('math.palette.subset.meaning'), [t('math.palette.subset.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.subset'), argumentTypes: ['set', 'set'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('subset-equal', 'sets-logic', t('math.palette.subset-equal.label'), '⊆', String.raw`#0\subseteq #?`, ['subset-equal'], t('math.palette.subset-equal.meaning'), [t('math.palette.subset-equal.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.subset-equal'), argumentTypes: ['set', 'set'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('superset', 'sets-logic', t('math.palette.superset.label'), '⊃', String.raw`#0\supset #?`, ['superset'], t('math.palette.superset.meaning'), [t('math.palette.superset.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.superset'), argumentTypes: ['set', 'set'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('superset-equal', 'sets-logic', t('math.palette.superset-equal.label'), '⊇', String.raw`#0\supseteq #?`, ['superset-equal'], t('math.palette.superset-equal.meaning'), [t('math.palette.superset-equal.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.superset-equal'), argumentTypes: ['set', 'set'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('complement', 'sets-logic', t('math.palette.complement.label'), '∁', String.raw`\operatorname{complement}\left(#0,#?\right)`, ['complement'], t('math.palette.complement.meaning'), [t('math.palette.complement.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.complement'), argumentTypes: ['set', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  item('cartesian-product', 'sets-logic', t('math.palette.cartesian-product.label'), 'A×B', String.raw`\operatorname{cartesianproduct}\left(#0,#?\right)`, ['cartesian-product'], t('math.palette.cartesian-product.meaning'), [t('math.palette.cartesian-product.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.cartesian-product'), argumentTypes: ['set', 'set'], resultType: 'set', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  // MC-02d (MC-24): explicit absolute tolerance equality, sharing the finite quantifiers' exact-runtime module.
  item('approximately-equal', 'sets-logic', t('math.palette.approximately-equal.label'), '≈', String.raw`\operatorname{approxequal}\left(#0,#?,#?\right)`, ['approximately-equal'], t('math.palette.approximately-equal.meaning'), [t('math.palette.approximately-equal.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.approximately-equal'), argumentTypes: ['real', 'real', 'real'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.equations }),
  // MC-02d (MC-12): finite set cardinality (also reachable through |x|; see mathPaletteBasic.ts's absolute entry).
  item('cardinality', 'sets-logic', t('math.palette.cardinality.label'), 'n(A)', String.raw`\operatorname{cardinality}\left(#0\right)`, ['cardinality'], t('math.palette.cardinality.meaning'), [t('math.palette.cardinality.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.cardinality'), argumentTypes: ['set'], resultType: 'real', method: 'exact-runtime', functionUse: false, help: HELP.setBounds }),
  // MC-02d (MC-04 gap): boolean literal constants, matching true/false already reachable inside conditions.
  item('true', 'sets-logic', t('math.palette.true.label'), '⊤', String.raw`\top`, [], t('math.palette.true.meaning'), [t('math.palette.true.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.true'), argumentTypes: [], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  item('false', 'sets-logic', t('math.palette.false.label'), '⊥', String.raw`\bot`, [], t('math.palette.false.meaning'), [t('math.palette.false.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.false'), argumentTypes: [], resultType: 'boolean', method: 'native', functionUse: false, help: HELP.equations }),
  // MC-02e (MC-24): finite quantifiers, sharing approximately-equal's exact-runtime module (cas_logic_extended.py).
  // Structural (LaTeX) input required a mathLatexFunctions.ts fix (\operatorname{forall}/{exists} did not bind
  // the variable and set with Element like mathTextSyntax.ts does; MC-02d's final report §4-2).
  item('for-all', 'sets-logic', t('math.palette.for-all.label'), '∀', String.raw`\operatorname{forall}\left(#?,#?,#?\right)`, ['for-all'], t('math.palette.for-all.meaning'), [t('math.palette.for-all.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.for-all'), argumentTypes: ['variable', 'set', 'condition'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.quantifiers }),
  item('exists', 'sets-logic', t('math.palette.exists.label'), '∃', String.raw`\operatorname{exists}\left(#?,#?,#?\right)`, ['exists'], t('math.palette.exists.meaning'), [t('math.palette.exists.keyword0')],
    { domain: t('math.paletteDomain.setsLogic.exists'), argumentTypes: ['variable', 'set', 'condition'], resultType: 'boolean', method: 'exact-runtime', functionUse: false, help: HELP.quantifiers }),
];
