import { MATH_PALETTE_DRAFT } from './mathPalette.js';

/** Shared runnable examples: the browser palette and its real-engine acceptance use exactly the same templates. */
export const MATH_PALETTE_EXAMPLES: readonly {
  readonly id: string; readonly selection: string; readonly slots: readonly string[];
  readonly expected: number | 'complex' | 'matrix' | 'vector' | 'boolean' | 'series' | 'transform' | 'fourier-series' | 'set' | 'interval' | 'equation-system' | 'root-intervals' | 'ode-solutions'; readonly exact?: boolean;
}[] = [
  { id: 'set-supremum', selection: String.raw`\operatorname{interval}(\operatorname{open}(0),\operatorname{open}(1))`, slots: [], expected: 1, exact: true },
  { id: 'set-infimum', selection: String.raw`\operatorname{interval}(\operatorname{open}(0),\operatorname{open}(1))`, slots: [], expected: 0, exact: true },
  { id: 'set-maximum', selection: String.raw`\operatorname{set}(1,3,2)`, slots: [], expected: 3, exact: true },
  { id: 'set-minimum', selection: String.raw`\operatorname{set}(1,3,2)`, slots: [], expected: 1, exact: true },
  { id: 'solve-ode', selection: '[\\operatorname{diff}(y,x)=2]', slots: ['x', '[y]', '[[y,0,3]]'], expected: 'ode-solutions', exact: true },
  { id: 'ode-value', selection: '\\operatorname{odesolve}([\\operatorname{diff}(y,x)=2],x,[y],[[y,0,3]])', slots: ['1', '[]', '4'], expected: 'vector', exact: true },
  { id: 'numerical-roots', selection: 'x^2-2', slots: ['x', '-2', '2', '0.000001'], expected: 'root-intervals' },
  { id: 'root-interval', selection: '\\operatorname{numericroots}(x^2-2,x,0,2,0.000001)', slots: ['1'], expected: 'vector' },
  { id: 'solve-system', selection: '[x+y=2,x-y=0]', slots: ['[x,y]', '\\mathbb{R}'], expected: 'equation-system', exact: true },
  { id: 'system-solution', selection: '\\operatorname{solvesystem}([x+y=2],[x,y],\\mathbb{R})', slots: ['1', '[3]'], expected: 'vector', exact: true },
  { id: 'solve-equation', selection: 'x^2=1', slots: ['x', String.raw`\mathbb{R}`], expected: 'set', exact: true },
  { id: 'polynomial-roots', selection: '(x-1)^2*(x+2)', slots: ['x', String.raw`\mathbb{C}`], expected: 'matrix', exact: true },
  { id: 'solution-value', selection: String.raw`\operatorname{solve}\left(x^2=4,x,\mathbb{R}\right)`, slots: ['2'], expected: 2, exact: true },
  { id: 'fourier-series', selection: 'x', slots: ['x', '-\\pi', '\\pi', '2'], expected: 'fourier-series', exact: true },
  { id: 'fourier-value', selection: String.raw`\operatorname{fourierseries}\left(x,x,-\pi,\pi,2\right)`, slots: ['\\pi/2'], expected: 2, exact: true },
  { id: 'fourier-cosine', selection: String.raw`\operatorname{fourierseries}\left(x,x,-\pi,\pi,2\right)`, slots: ['1'], expected: 0, exact: true },
  { id: 'fourier-sine', selection: String.raw`\operatorname{fourierseries}\left(x,x,-\pi,\pi,2\right)`, slots: ['2'], expected: -1, exact: true },
  { id: "fourier-transform", selection: String.raw`\exp\left(-x^2\right)`, slots: ["x", "k"], expected: 'transform', exact: true },
  { id: "inverse-fourier-transform", selection: String.raw`\exp\left(-\pi x^2\right)`, slots: ["x", "t"], expected: 'transform', exact: true },
  { id: "laplace-transform", selection: String.raw`\exp\left(-x\right)`, slots: ["x", "s"], expected: 'transform', exact: true },
  { id: "inverse-laplace-transform", selection: "1/(x+1)", slots: ["x", "t"], expected: 'transform', exact: true },
  { id: "z-transform", selection: "(1/2)^n", slots: ["n", "z"], expected: 'transform', exact: true },
  { id: "transform-value", selection: String.raw`\operatorname{laplace}\left(\exp\left(-x\right),x,s\right)`, slots: ["1"], expected: 0.5, exact: true },
  { id: 'dft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'idft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'fft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'ifft', selection: '[1,2,3,4]', slots: [], expected: 'vector', exact: true },
  { id: 'zeta', selection: '2', slots: [], expected: Math.PI**2/6 },
  { id: 'zetaderivative', selection: '1', slots: ['2'], expected: Number('-0.9375482543158437537') },
  { id: 'elliptick', selection: '0', slots: [], expected: Math.PI/2 },
  { id: 'elliptice', selection: '1', slots: [], expected: 1 },
  { id: 'ellipticf', selection: '90', slots: ["0"], expected: Math.PI/2 },
  { id: 'ellipticeinc', selection: '90', slots: ["1"], expected: 1 },
  { id: 'ellipticpi', selection: '0', slots: ["0"], expected: Math.PI/2 },
  { id: 'ellipticpiinc', selection: '0', slots: ["90", "0"], expected: Math.PI/2 },
  { id: 'airyai', selection: '1', slots: [], expected: Number('0.13529241631288141') },
  { id: 'airybi', selection: '1', slots: [], expected: Number('1.2074235949528713') },
  { id: 'airyaiprime', selection: '1', slots: [], expected: Number('-0.1591474412967932') },
  { id: 'airybiprime', selection: '1', slots: [], expected: Number('0.9324359333927756') },
  { id: 'lambertw', selection: '0', slots: ['1'], expected: Number('0.5671432904097838') },
  { id: 'besselj', selection: '0', slots: ['1'], expected: 0.7651976865579666 },
  { id: 'bessely', selection: '0', slots: ['1'], expected: 0.08825696421567696 },
  { id: 'besseli', selection: '0', slots: ['1'], expected: Number('1.2660658777520083') },
  { id: 'besselk', selection: '0', slots: ['1'], expected: Number('0.42102443824070833') },
  { id: 'beta', selection: '2', slots: ['3'], expected: 1/12 },
  { id: 'gamma', selection: '5', slots: [], expected: 24 },
  { id: 'polygamma', selection: '1', slots: ['1'], expected: 1.6449340668482264 },
  { id: 'erf', selection: '1', slots: [], expected: 0.8427007929497149 },
  { id: 'erfc', selection: '1', slots: [], expected: 0.15729920705028513 },
  { id: 'legendre', selection: '4', slots: ['0'], expected: 0.375 },
  { id: 'series-coefficient', selection: String.raw`\operatorname{taylor}\left(x^3,x,2,4\right)`, slots: ['1'], expected: 12, exact: true },
  { id: 'taylor', selection: 'x^3', slots: ['x', '1', '3'], expected: 'series', exact: true },
  { id: 'maclaurin', selection: '1/(1-x)', slots: ['x', '4'], expected: 'series', exact: true },
  {"id": "sequence-value", "selection": "n^2", "slots": ["n", "5"], "expected": 25, "exact": true},
  {"id": "difference-at", "selection": "n^2", "slots": ["n", "4", "1", "2"], "expected": 20, "exact": true},
  {"id": "recurrence-value", "selection": "a+b", "slots": ["[n,a,b]", "0", "[0,1]", "10"], "expected": 55, "exact": true},
  {"id": "event-probability", "selection": "x>0", "slots": ["[x]", "\\operatorname{normaldistribution}(0,1)"], "expected": 0.5, "exact": true},
  {"id": "given-probability", "selection": "x>2", "slots": ["x>1", "[x]", "\\operatorname{uniformdistribution}(0,4)"], "expected": 0.6666666666666666, "exact": true},
  {"id": "random-expectation", "selection": "x", "slots": ["[x]", "\\operatorname{normaldistribution}(3,2)"], "expected": 3, "exact": true},
  {"id": "random-variance", "selection": "x", "slots": ["[x]", "\\operatorname{normaldistribution}(3,2)"], "expected": 4, "exact": true},
  {"id": "random-covariance", "selection": "x", "slots": ["2*x", "[x]", "\\operatorname{normaldistribution}(1,3)"], "expected": 18, "exact": true},
  {"id": "random-correlation", "selection": "x", "slots": ["-2*x", "[x]", "\\operatorname{uniformdistribution}(-1,1)"], "expected": -1, "exact": true},
  {"id": "independent-events", "selection": "x>1", "slots": ["x<3", "[x]", "\\operatorname{uniformdistribution}(0,4)"], "expected": "boolean", "exact": true},
  {"id": "independent-variables", "selection": "x", "slots": ["y", "[x,y]", "\\operatorname{independentdistributions}([\\operatorname{normaldistribution}(0,1),\\operatorname{normaldistribution}(0,1)])"], "expected": "boolean", "exact": true},

  {"id": "chi-square-pdf", "selection": "2", "slots": ["2"], "expected": 0.18393972058572117},
  {"id": "chi-square-cdf", "selection": "2", "slots": ["2"], "expected": 0.6321205588285577},
  {"id": "chi-square-quantile", "selection": "2", "slots": ["1/2"], "expected": 1.3862943611198906},
  {"id": "t-pdf", "selection": "1", "slots": ["0"], "expected": 0.3183098861837907},
  {"id": "t-cdf", "selection": "1", "slots": ["1"], "expected": 0.75},
  {"id": "t-quantile", "selection": "1", "slots": ["3/4"], "expected": 1},
  {"id": "f-pdf", "selection": "2", "slots": ["2", "1"], "expected": 0.25},
  {"id": "f-cdf", "selection": "2", "slots": ["2", "1"], "expected": 0.5},
  {"id": "f-quantile", "selection": "2", "slots": ["2", "3/4"], "expected": 3},
  {"id": "gamma-pdf", "selection": "2", "slots": ["1", "1"], "expected": 0.36787944117144233},
  {"id": "gamma-cdf", "selection": "2", "slots": ["1", "1"], "expected": 0.26424111765711533},
  {"id": "gamma-quantile", "selection": "1", "slots": ["2", "0.5"], "expected": 1.3862943611198906},
  {"id": "beta-pdf", "selection": "2", "slots": ["2", "0.5"], "expected": 1.5},
  {"id": "beta-cdf", "selection": "2", "slots": ["3", "0.5"], "expected": 0.6875},
  {"id": "beta-quantile", "selection": "2", "slots": ["2", "0.5"], "expected": 0.5},
  {"id": "normal-pdf", "selection": "0", "slots": ["1", "0"], "expected": 0.3989422804014327},
  {"id": "normal-cdf", "selection": "0", "slots": ["1", "0"], "expected": 0.5},
  {"id": "normal-quantile", "selection": "3", "slots": ["2", "1/2"], "expected": 3},
  {"id": "expectation", "selection": "[0,4]", "slots": ["[1/4,3/4]"], "expected": 3},
  {"id": "probability-variance", "selection": "[0,4]", "slots": ["[1/4,3/4]"], "expected": 3},
  {"id": "conditional-probability", "selection": "1/4", "slots": ["1/2"], "expected": 0.5},
  {"id": "uniform-pdf", "selection": "2", "slots": ["6", "3"], "expected": 0.25},
  {"id": "uniform-cdf", "selection": "2", "slots": ["6", "3"], "expected": 0.25},
  {"id": "uniform-quantile", "selection": "2", "slots": ["6", "1/4"], "expected": 3},
  {"id": "exponential-pdf", "selection": "2", "slots": ["1"], "expected": 0.2706705664732254},
  {"id": "exponential-cdf", "selection": "2", "slots": ["1"], "expected": 0.8646647167633873},
  {"id": "exponential-quantile", "selection": "2", "slots": ["3/4"], "expected": 0.6931471805599453},
  {id:'binomial-quantile',selection:'4',slots:['1/2','11/16'],expected:2},
  {id:'poisson-quantile',selection:'2',slots:['3/4'],expected:3},
  {"id": "poisson-pmf", "selection": "2", "slots": ["3"], "expected": 0.1804470443154836},
  {"id": "poisson-cdf", "selection": "2", "slots": ["2"], "expected": 0.6766764161830635},
  {"id": "svd-u", "selection": "[[3,0],[4,0]]", "slots": [], "expected": "matrix"},
  {"id": "svd-s", "selection": "[[3,0],[4,0]]", "slots": [], "expected": "matrix"},
  {"id": "svd-v", "selection": "[[3,0],[4,0]]", "slots": [], "expected": "matrix"},
  {"id": "eigenspace", "selection": "[[2,1],[0,2]]", "slots": ["2"], "expected": "matrix"},
  {"id": "tensor-product", "selection": "[1,2]", "slots": ["[3,4]"], "expected": "matrix"},
  {"id": "hadamard-product", "selection": "[[1,2],[3,4]]", "slots": ["[[2,3],[4,5]]"], "expected": "matrix"},
  {"id": "tensor-contract", "selection": "[[1,2],[3,4]]", "slots": ["1", "2"], "expected": 5},
  {"id": "tensor-permute", "selection": "[[1,2,3],[4,5,6]]", "slots": ["[2,1]"], "expected": "matrix"},
  {"id": "tensor-shape", "selection": "[[1,2,3],[4,5,6]]", "slots": [], "expected": "vector"},
  {"id": "tensor-element", "selection": "[[[1,2],[3,4]],[[5,6],[7,8]]]", "slots": ["[2,1,2]"], "expected": 6},
  {"id": "kronecker-delta", "selection": "2", "slots": ["2"], "expected": 1},
  {"id": "levi-civita", "selection": "[2,3,1]", "slots": [], "expected": 1},
  {"id": "integer-quotient", "selection": "-7", "slots": ["3"], "expected": -3},
  {"id": "integer-remainder", "selection": "-7", "slots": ["-3"], "expected": 2},
  {"id": "divides", "selection": "4", "slots": ["20"], "expected": "boolean"},
  {"id": "congruent-modulo", "selection": "-1", "slots": ["5", "3"], "expected": "boolean"},
  {"id": "is-prime", "selection": "13", "slots": [], "expected": "boolean"},
  {"id": "next-prime", "selection": "97", "slots": [], "expected": 101},
  {"id": "prime-factors", "selection": "360", "slots": [], "expected": "matrix"},
  {"id": "divisors", "selection": "36", "slots": [], "expected": "vector"},
  {"id": "euler-totient", "selection": "36", "slots": [], "expected": 12},
  { id: 'binomial-pmf', selection: '4', slots: ['1/2', '2'], expected: 0.375 },
  { id: 'binomial-cdf', selection: '4', slots: ['1/2', '2'], expected: 0.6875 },
  { id: 'singular-values', selection: '[[3,0],[0,4]]', slots: [], expected: 'vector' },
  { id: 'eigenvalues', selection: '[[2,1],[1,2]]', slots: [], expected: 'vector' },
  { id: 'row-reduce', selection: '[[1,2,3],[2,4,6]]', slots: [], expected: 'matrix' },
  { id: 'qr-q', selection: '[[3,0],[4,5]]', slots: [], expected: 'matrix' },
  { id: 'qr-r', selection: '[[3,0],[4,5]]', slots: [], expected: 'matrix' },
  { id: 'lu-p', selection: '[[0,2],[3,4]]', slots: [], expected: 'matrix' },
  { id: 'lu-l', selection: '[[1,1,1],[2,2,3],[4,5,6]]', slots: [], expected: 'matrix' },
  { id: 'lu-u', selection: '[[1,1,1],[2,2,3],[4,5,6]]', slots: [], expected: 'matrix' },
  { id: 'characteristic-coefficients', selection: '[[1,2],[3,4]]', slots: [], expected: 'vector' },
  { id: 'null-space', selection: '[[1,2,3],[2,4,6]]', slots: [], expected: 'matrix' },
  { id: 'column-space', selection: '[[1,2,3],[2,4,6]]', slots: [], expected: 'matrix' },
  { id: 'row-space', selection: '[[1,2,3],[2,4,6]]', slots: [], expected: 'matrix' },
  { id: 'linear-solve', selection: '[[2,1],[1,-1]]', slots: ['[5,1]'], expected: 'vector' },
  { id: 'linear-solution-space', selection: '[[1,2,3],[2,4,6]]', slots: ['[4,8]'], expected: 'matrix' },
  {"id": "mean", "selection": "[1,2,6]", "slots": [], "expected": 3},
  {"id": "median", "selection": "[9,1,3,5]", "slots": [], "expected": 4},
  {"id": "modes", "selection": "[1,1,2,2,3]", "slots": [], "expected": "vector"},
  {"id": "quantile", "selection": "[0,10,20,30]", "slots": ["0.25"], "expected": 7.5},
  {"id": "population-variance", "selection": "[1,2,3]", "slots": [], "expected": 0.6666666666666666},
  {"id": "sample-variance", "selection": "[1,2,3]", "slots": [], "expected": 1},
  {"id": "population-standard-deviation", "selection": "[1,3]", "slots": [], "expected": 1},
  {"id": "sample-standard-deviation", "selection": "[1,3]", "slots": [], "expected": 1.4142135623730951},
  {"id": "population-covariance", "selection": "[1,2,3]", "slots": ["[2,4,6]"], "expected": 1.3333333333333333},
  {"id": "sample-covariance", "selection": "[1,2,3]", "slots": ["[2,4,6]"], "expected": 2},
  {"id": "correlation", "selection": "[1,2,3]", "slots": ["[6,4,2]"], "expected": -1},
  {"id": "regression-slope", "selection": "[1,2,3]", "slots": ["[3,5,7]"], "expected": 2},
  {"id": "regression-intercept", "selection": "[1,2,3]", "slots": ["[3,5,7]"], "expected": 1},
  {"id": "r-squared", "selection": "[1,2,3]", "slots": ["[3,5,7]"], "expected": 1},
  { id: 'reciprocal', selection: '4', slots: [], expected: 0.25 },
  { id: 'double-factorial', selection: '5', slots: [], expected: 15 },
  { id: 'permutations', selection: '5', slots: ['3'], expected: 60 },
  { id: 'clamp', selection: '8', slots: ['1', '5'], expected: 5 },
  { id: 'arccot', selection: '-1', slots: [], expected: 135 },
  { id: 'arcsec', selection: '2', slots: [], expected: 60 },
  { id: 'arccsc', selection: '2', slots: [], expected: 30 },
  { id: 'atan2', selection: '1', slots: ['-1'], expected: 135 },
  { id: 'coth', selection: String.raw`\ln(3)`, slots: [], expected: 1.25 },
  { id: 'sech', selection: '0', slots: [], expected: 1 },
  { id: 'csch', selection: String.raw`\ln(3)`, slots: [], expected: 0.75 },
  { id: 'arcoth', selection: '2', slots: [], expected: Math.log(3)/2 },
  { id: 'arsech', selection: '1', slots: [], expected: 0 },
  { id: 'arcsch', selection: '1', slots: [], expected: Math.log(1+Math.sqrt(2)) },
  { id: 'component', selection: String.raw`\begin{pmatrix}1&2\\3&4\end{pmatrix}`, slots: ['2', '1'], expected: 3 },
  { id: 'fraction', selection: '3', slots: ['2'], expected: 1.5 },
  { id: 'power', selection: '2', slots: ['3'], expected: 8 },
  { id: 'square-root', selection: '9', slots: [], expected: 3 },
  { id: 'nth-root', selection: '8', slots: ['3'], expected: 2 },
  { id: 'factorial', selection: '5', slots: [], expected: 120 },
  { id: 'absolute', selection: '-3', slots: [], expected: 3 },
  { id: 'sin', selection: '30', slots: [], expected: 0.5 },
  { id: 'cos', selection: '60', slots: [], expected: 0.5 },
  { id: 'tan', selection: '45', slots: [], expected: 1 },
  { id: 'arcsin', selection: '0.5', slots: [], expected: 30 },
  { id: 'log-natural', selection: '\\exponentialE', slots: [], expected: 1 },
  { id: 'log-ten', selection: '100', slots: [], expected: 2 },
  { id: 'log-base', selection: '8', slots: ['2'], expected: 3 },
  { id: 'sinh', selection: '0', slots: [], expected: 0 },
  { id: 'sum', selection: 'i^2', slots: ['3'], expected: 14 },
  { id: 'product', selection: 'i', slots: ['4'], expected: 24 },
  { id: 'integral', selection: 'x^2', slots: ['0', '3'], expected: 9 },
  { id: 'matrix', selection: '', slots: ['1', '2', '3', '4'], expected: 'matrix' },
  { id: 'pi', selection: '', slots: [], expected: Math.PI },
  { id: 'imaginary-unit', selection: '', slots: [], expected: 'complex' },
];

export const MATH_INPUT_PALETTE = MATH_PALETTE_EXAMPLES.map(example => {
  const item = MATH_PALETTE_DRAFT.find(item => item.id === example.id);
  if (item === undefined) throw new Error(`Missing math palette template: ${example.id}`);
  return { ...item, acceptanceIds: [`mathPaletteExamples:${example.id}`] };
});

export function mathPaletteExampleSource(example: typeof MATH_PALETTE_EXAMPLES[number]): string {
  const item = MATH_INPUT_PALETTE.find(item => item.id === example.id);
  if (item === undefined) throw new Error(`Missing math palette example: ${example.id}`);
  let slot = 0;
  const source = item.template.replaceAll('#0', example.selection).replace(/#\?/gu, () => {
    const value = example.slots[slot++];
    if (value === undefined) throw new Error(`Missing math palette argument: ${example.id}`);
    return value;
  });
  if (slot !== example.slots.length) throw new Error(`Unused math palette argument: ${example.id}`);
  return source;
}
