import { t } from '../i18n/t.js';
/** The future palette/help catalogue starts from the same entries; activation requires acceptance IDs. */
export type MathPaletteGroup = 'basic' | 'functions' | 'calculus' | 'linear-algebra' | 'complex'
  | 'series' | 'statistics' | 'sets-logic' | 'equations' | 'symbols';
export interface MathPaletteItem {
  readonly id: string;
  readonly group: MathPaletteGroup;
  readonly label: string;
  readonly symbol: string;
  readonly template: string;
  readonly keywords: readonly string[];
  readonly requiredOperations: readonly string[];
  readonly acceptanceIds: readonly string[];
  readonly meaning: string;
}

function item(id: string, group: MathPaletteGroup, label: string, symbol: string, template: string,
  operations: readonly string[], meaning: string, keywords: readonly string[] = []): MathPaletteItem {
  // Empty acceptanceIds intentionally prevents a draft entry from claiming tested availability.
  return { id, group, label, symbol, template, requiredOperations: operations, acceptanceIds: [], meaning, keywords };
}
export const MATH_PALETTE_DRAFT: readonly MathPaletteItem[] = [
  item('set-supremum', 'sets-logic', t('math.palette.set-supremum.label'), 'sup', String.raw`\operatorname{sup}\left(#0\right)`, ['set-supremum'], t('math.palette.set-supremum.meaning')),
  item('set-infimum', 'sets-logic', t('math.palette.set-infimum.label'), 'inf', String.raw`\operatorname{inf}\left(#0\right)`, ['set-infimum'], t('math.palette.set-infimum.meaning')),
  item('set-maximum', 'sets-logic', t('math.palette.set-maximum.label'), 'setmax', String.raw`\operatorname{setmax}\left(#0\right)`, ['set-maximum'], t('math.palette.set-maximum.meaning')),
  item('set-minimum', 'sets-logic', t('math.palette.set-minimum.label'), 'setmin', String.raw`\operatorname{setmin}\left(#0\right)`, ['set-minimum'], t('math.palette.set-minimum.meaning')),
  item('solve-ode', 'equations', t('math.palette.solve-ode.label'), 'odesolve', String.raw`\operatorname{odesolve}\left(#0,#?,#?,#?\right)`, ['solve-ode', 'lambda'], t('math.palette.solve-ode.meaning')),
  item('ode-value', 'equations', t('math.palette.ode-value.label'), 'odeat', String.raw`\operatorname{odeat}\left(#0,#?,#?,#?\right)`, ['ode-value'], t('math.palette.ode-value.meaning')),
  item('numerical-roots', 'equations', t('math.palette.numerical-roots.label'), 'numericroots', String.raw`\operatorname{numericroots}\left(#0,#?,#?,#?,#?\right)`, ['numerical-roots', 'lambda'], t('math.palette.numerical-roots.meaning')),
  item('root-interval', 'equations', t('math.palette.root-interval.label'), 'rootinterval', String.raw`\operatorname{rootinterval}\left(#0,#?\right)`, ['root-interval'], t('math.palette.root-interval.meaning')),
  item('solve-system', 'equations', t('math.palette.solve-system.label'), 'solvesystem', String.raw`\operatorname{solvesystem}\left(#0,#?,#?\right)`, ['solve-system', 'lambda'], t('math.palette.solve-system.meaning')),
  item('system-solution', 'equations', t('math.palette.system-solution.label'), 'systemsolution', String.raw`\operatorname{systemsolution}\left(#0,#?,#?\right)`, ['system-solution'], t('math.palette.system-solution.meaning')),
  item('solve-equation', 'equations', t('math.palette.solve-equation.label'), 'solve', String.raw`\operatorname{solve}\left(#0,#?,#?\right)`, ['solve-equation', 'lambda'], t('math.palette.solve-equation.meaning')),
  item('polynomial-roots', 'equations', t('math.palette.polynomial-roots.label'), 'polynomialroots', String.raw`\operatorname{polynomialroots}\left(#0,#?,#?\right)`, ['polynomial-roots', 'lambda'], t('math.palette.polynomial-roots.meaning')),
  item('solution-value', 'equations', t('math.palette.solution-value.label'), 'solution', String.raw`\operatorname{solution}\left(#0,#?\right)`, ['solution-value'], t('math.palette.solution-value.meaning')),
  item('fourier-series', 'series', t('math.palette.fourier-series.label'), 'fourierseries', String.raw`\operatorname{fourierseries}\left(#0,#?,#?,#?,#?\right)`, ["fourier-series", "lambda"], t('math.palette.fourier-series.meaning')),
  item('fourier-value', 'series', t('math.palette.fourier-value.label'), 'fourierat', String.raw`\operatorname{fourierat}\left(#0,#?\right)`, ["fourier-value"], t('math.palette.fourier-value.meaning')),
  item('fourier-cosine', 'series', t('math.palette.fourier-cosine.label'), 'fouriercos', String.raw`\operatorname{fouriercos}\left(#0,#?\right)`, ["fourier-cosine"], t('math.palette.fourier-cosine.meaning')),
  item('fourier-sine', 'series', t('math.palette.fourier-sine.label'), 'fouriersin', String.raw`\operatorname{fouriersin}\left(#0,#?\right)`, ["fourier-sine"], t('math.palette.fourier-sine.meaning')),
  item('fourier-transform', 'equations', t('math.palette.fourier-transform.label'), 'fourier', String.raw`\operatorname{fourier}\left(#0,#?,#?\right)`, ['fourier-transform', 'lambda'], t('math.palette.fourier-transform.meaning')),
  item('inverse-fourier-transform', 'equations', t('math.palette.inverse-fourier-transform.label'), 'inversefourier', String.raw`\operatorname{inversefourier}\left(#0,#?,#?\right)`, ['inverse-fourier-transform', 'lambda'], t('math.palette.inverse-fourier-transform.meaning')),
  item('laplace-transform', 'equations', t('math.palette.laplace-transform.label'), 'laplace', String.raw`\operatorname{laplace}\left(#0,#?,#?\right)`, ['laplace-transform', 'lambda'], t('math.palette.laplace-transform.meaning')),
  item('inverse-laplace-transform', 'equations', t('math.palette.inverse-laplace-transform.label'), 'inverselaplace', String.raw`\operatorname{inverselaplace}\left(#0,#?,#?\right)`, ['inverse-laplace-transform', 'lambda'], t('math.palette.inverse-laplace-transform.meaning')),
  item('z-transform', 'equations', t('math.palette.z-transform.label'), 'ztransform', String.raw`\operatorname{ztransform}\left(#0,#?,#?\right)`, ['z-transform', 'lambda'], t('math.palette.z-transform.meaning')),
  item('transform-value', 'equations', t('math.palette.transform-value.label'), 'transformat', String.raw`\operatorname{transformat}\left(#0,#?\right)`, ['transform-value'], t('math.palette.transform-value.meaning')),
  item('dft', 'functions', t('math.palette.dft.label'), 'DFT', String.raw`\operatorname{dft}\left(#0\right)`, ['dft'], t('math.palette.dft.meaning')),
  item('idft', 'functions', t('math.palette.idft.label'), 'IDFT', String.raw`\operatorname{idft}\left(#0\right)`, ['idft'], t('math.palette.idft.meaning')),
  item('fft', 'functions', t('math.palette.fft.label'), 'FFT', String.raw`\operatorname{fft}\left(#0\right)`, ['fft'], t('math.palette.fft.meaning')),
  item('ifft', 'functions', t('math.palette.ifft.label'), 'IFFT', String.raw`\operatorname{ifft}\left(#0\right)`, ['ifft'], t('math.palette.ifft.meaning')),
  item('zeta', 'functions', t('math.palette.zeta.label'), 'ζ', String.raw`\operatorname{zeta}\left(#0\right)`, ['zeta'], t('math.palette.zeta.meaning')),
  item('zetaderivative', 'functions', t('math.palette.zetaderivative.label'), 'ζ⁽ⁿ⁾', String.raw`\operatorname{zetaderivative}\left(#0,#?\right)`, ['zetaderivative'], t('math.palette.zetaderivative.meaning')),
  item('elliptick', 'functions', t('math.palette.elliptick.label'), 'K', String.raw`\operatorname{elliptick}\left(#0\right)`, ['elliptick'], t('math.palette.elliptick.meaning')),
  item('elliptice', 'functions', t('math.palette.elliptice.label'), 'E', String.raw`\operatorname{elliptice}\left(#0\right)`, ['elliptice'], t('math.palette.elliptice.meaning')),
  item('ellipticf', 'functions', t('math.palette.ellipticf.label'), 'F', String.raw`\operatorname{ellipticf}\left(#0,#?\right)`, ['ellipticf'], t('math.palette.ellipticf.meaning')),
  item('ellipticeinc', 'functions', t('math.palette.ellipticeinc.label'), 'Einc', String.raw`\operatorname{ellipticeinc}\left(#0,#?\right)`, ['ellipticeinc'], t('math.palette.ellipticeinc.meaning')),
  item('ellipticpi', 'functions', t('math.palette.ellipticpi.label'), 'Pi', String.raw`\operatorname{ellipticpi}\left(#0,#?\right)`, ['ellipticpi'], t('math.palette.ellipticpi.meaning')),
  item('ellipticpiinc', 'functions', t('math.palette.ellipticpiinc.label'), 'Piinc', String.raw`\operatorname{ellipticpiinc}\left(#0,#?,#?\right)`, ['ellipticpiinc'], t('math.palette.ellipticpiinc.meaning')),
  item('airyai', 'functions', t('math.palette.airyai.label'), 'Airy Ai', String.raw`\operatorname{airyai}\left(#0\right)`, ['airyai'], t('math.palette.airyai.meaning')),
  item('airybi', 'functions', t('math.palette.airybi.label'), 'Airy Bi', String.raw`\operatorname{airybi}\left(#0\right)`, ['airybi'], t('math.palette.airybi.meaning')),
  item('airyaiprime', 'functions', t('math.palette.airyaiprime.label'), 'Airy Ai′', String.raw`\operatorname{airyaiprime}\left(#0\right)`, ['airyaiprime'], t('math.palette.airyaiprime.meaning')),
  item('airybiprime', 'functions', t('math.palette.airybiprime.label'), 'Airy Bi′', String.raw`\operatorname{airybiprime}\left(#0\right)`, ['airybiprime'], t('math.palette.airybiprime.meaning')),
  item('lambertw', 'functions', t('math.palette.lambertw.label'), 'Lambert W', String.raw`\operatorname{lambertw}\left(#0,#?\right)`, ['lambertw'], t('math.palette.lambertw.meaning')),
  item('besselj', 'functions', t('math.palette.besselj.label'), 'Bessel J', String.raw`\operatorname{besselj}\left(#0,#?\right)`, ['besselj'], t('math.palette.besselj.meaning')),
  item('bessely', 'functions', t('math.palette.bessely.label'), 'Bessel Y', String.raw`\operatorname{bessely}\left(#0,#?\right)`, ['bessely'], t('math.palette.bessely.meaning')),
  item('besseli', 'functions', t('math.palette.besseli.label'), 'Bessel I', String.raw`\operatorname{besseli}\left(#0,#?\right)`, ['besseli'], t('math.palette.besseli.meaning')),
  item('besselk', 'functions', t('math.palette.besselk.label'), 'Bessel K', String.raw`\operatorname{besselk}\left(#0,#?\right)`, ['besselk'], t('math.palette.besselk.meaning')),
  item('beta', 'functions', t('math.palette.beta.label'), 'Beta', String.raw`\operatorname{beta}\left(#0,#?\right)`, ['beta'], t('math.palette.beta.meaning')),
  item('gamma', 'functions', t('math.palette.gamma.label'), 'Gamma', String.raw`\operatorname{gamma}\left(#0\right)`, ['gamma'], t('math.palette.gamma.meaning')),
  item('polygamma', 'functions', t('math.palette.polygamma.label'), 'polygamma', String.raw`\operatorname{polygamma}\left(#0,#?\right)`, ['polygamma'], t('math.palette.polygamma.meaning')),
  item('erf', 'functions', t('math.palette.erf.label'), 'erf', String.raw`\operatorname{erf}\left(#0\right)`, ['erf'], t('math.palette.erf.meaning')),
  item('erfc', 'functions', t('math.palette.erfc.label'), 'erfc', String.raw`\operatorname{erfc}\left(#0\right)`, ['erfc'], t('math.palette.erfc.meaning')),
  item('legendre', 'functions', t('math.palette.legendre.label'), 'legendre', String.raw`\operatorname{legendre}\left(#0,#?\right)`, ['legendre'], t('math.palette.legendre.meaning')),
  item('series-coefficient', 'series', t('math.palette.series-coefficient.label'), 'seriescoefficient', String.raw`\operatorname{seriescoefficient}\left(#0,#?\right)`, ['series-coefficient'], t('math.palette.series-coefficient.meaning')),
  item('taylor', 'series', t('math.palette.taylor.label'), 'taylor', String.raw`\operatorname{taylor}\left(#0,#?,#?,#?\right)`, ['taylor'], t('math.palette.taylor.meaning')),
  item('maclaurin', 'series', t('math.palette.maclaurin.label'), 'maclaurin', String.raw`\operatorname{maclaurin}\left(#0,#?,#?\right)`, ['maclaurin'], t('math.palette.maclaurin.meaning')),
  item('sequence-value', 'series', t('math.palette.sequence-value.label'), 'sequencevalue', String.raw`\operatorname{sequencevalue}\left(#0,#?,#?\right)`, ['sequence-value'], t('math.palette.sequence-value.meaning')),
  item('difference-at', 'series', t('math.palette.difference-at.label'), 'differenceat', String.raw`\operatorname{differenceat}\left(#0,#?,#?,#?,#?\right)`, ['difference-at'], t('math.palette.difference-at.meaning')),
  item('recurrence-value', 'series', t('math.palette.recurrence-value.label'), 'recurrencevalue', String.raw`\operatorname{recurrencevalue}\left(#0,#?,#?,#?,#?\right)`, ['recurrence-value'], t('math.palette.recurrence-value.meaning')),
  item('event-probability', 'statistics', t('math.palette.event-probability.label'), 'probability', String.raw`\operatorname{probability}\left(#0,#?,#?\right)`, ['event-probability'], t('math.palette.event-probability.meaning')),
  item('given-probability', 'statistics', t('math.palette.given-probability.label'), 'givenprobability', String.raw`\operatorname{givenprobability}\left(#0,#?,#?,#?\right)`, ['given-probability'], t('math.palette.given-probability.meaning')),
  item('random-expectation', 'statistics', t('math.palette.random-expectation.label'), 'randomexpectation', String.raw`\operatorname{randomexpectation}\left(#0,#?,#?\right)`, ['random-expectation'], t('math.palette.random-expectation.meaning')),
  item('random-variance', 'statistics', t('math.palette.random-variance.label'), 'randomvariance', String.raw`\operatorname{randomvariance}\left(#0,#?,#?\right)`, ['random-variance'], t('math.palette.random-variance.meaning')),
  item('random-covariance', 'statistics', t('math.palette.random-covariance.label'), 'randomcovariance', String.raw`\operatorname{randomcovariance}\left(#0,#?,#?,#?\right)`, ['random-covariance'], t('math.palette.random-covariance.meaning')),
  item('random-correlation', 'statistics', t('math.palette.random-correlation.label'), 'randomcorrelation', String.raw`\operatorname{randomcorrelation}\left(#0,#?,#?,#?\right)`, ['random-correlation'], t('math.palette.random-correlation.meaning')),
  item('independent-events', 'statistics', t('math.palette.independent-events.label'), 'independentevents', String.raw`\operatorname{independentevents}\left(#0,#?,#?,#?\right)`, ['independent-events'], t('math.palette.independent-events.meaning')),
  item('independent-variables', 'statistics', t('math.palette.independent-variables.label'), 'independentvariables', String.raw`\operatorname{independentvariables}\left(#0,#?,#?,#?\right)`, ['independent-variables'], t('math.palette.independent-variables.meaning')),
  item('chi-square-pdf', 'statistics', t('math.palette.chi-square-pdf.label'), 'chisquarepdf', String.raw`\operatorname{chisquarepdf}\left(#0,#?\right)`, ['chi-square-pdf'], t('math.palette.chi-square-pdf.meaning')),
  item('chi-square-cdf', 'statistics', t('math.palette.chi-square-cdf.label'), 'chisquarecdf', String.raw`\operatorname{chisquarecdf}\left(#0,#?\right)`, ['chi-square-cdf'], t('math.palette.chi-square-cdf.meaning')),
  item('chi-square-quantile', 'statistics', t('math.palette.chi-square-quantile.label'), 'chisquarequantile', String.raw`\operatorname{chisquarequantile}\left(#0,#?\right)`, ['chi-square-quantile'], t('math.palette.chi-square-quantile.meaning')),
  item('t-pdf', 'statistics', t('math.palette.t-pdf.label'), 'tpdf', String.raw`\operatorname{tpdf}\left(#0,#?\right)`, ['t-pdf'], t('math.palette.t-pdf.meaning')),
  item('t-cdf', 'statistics', t('math.palette.t-cdf.label'), 'tcdf', String.raw`\operatorname{tcdf}\left(#0,#?\right)`, ['t-cdf'], t('math.palette.t-cdf.meaning')),
  item('t-quantile', 'statistics', t('math.palette.t-quantile.label'), 'tquantile', String.raw`\operatorname{tquantile}\left(#0,#?\right)`, ['t-quantile'], t('math.palette.t-quantile.meaning')),
  item('f-pdf', 'statistics', t('math.palette.f-pdf.label'), 'fpdf', String.raw`\operatorname{fpdf}\left(#0,#?,#?\right)`, ['f-pdf'], t('math.palette.f-pdf.meaning')),
  item('f-cdf', 'statistics', t('math.palette.f-cdf.label'), 'fcdf', String.raw`\operatorname{fcdf}\left(#0,#?,#?\right)`, ['f-cdf'], t('math.palette.f-cdf.meaning')),
  item('f-quantile', 'statistics', t('math.palette.f-quantile.label'), 'fquantile', String.raw`\operatorname{fquantile}\left(#0,#?,#?\right)`, ['f-quantile'], t('math.palette.f-quantile.meaning')),
  item('gamma-pdf', 'statistics', t('math.palette.gamma-pdf.label'), 'gammapdf', String.raw`\operatorname{gammapdf}\left(#0,#?,#?\right)`, ['gamma-pdf'], t('math.palette.gamma-pdf.meaning')),
  item('gamma-cdf', 'statistics', t('math.palette.gamma-cdf.label'), 'gammacdf', String.raw`\operatorname{gammacdf}\left(#0,#?,#?\right)`, ['gamma-cdf'], t('math.palette.gamma-cdf.meaning')),
  item('gamma-quantile', 'statistics', t('math.palette.gamma-quantile.label'), 'gammaquantile', String.raw`\operatorname{gammaquantile}\left(#0,#?,#?\right)`, ['gamma-quantile'], t('math.palette.gamma-quantile.meaning')),
  item('beta-pdf', 'statistics', t('math.palette.beta-pdf.label'), 'betapdf', String.raw`\operatorname{betapdf}\left(#0,#?,#?\right)`, ['beta-pdf'], t('math.palette.beta-pdf.meaning')),
  item('beta-cdf', 'statistics', t('math.palette.beta-cdf.label'), 'betacdf', String.raw`\operatorname{betacdf}\left(#0,#?,#?\right)`, ['beta-cdf'], t('math.palette.beta-cdf.meaning')),
  item('beta-quantile', 'statistics', t('math.palette.beta-quantile.label'), 'betaquantile', String.raw`\operatorname{betaquantile}\left(#0,#?,#?\right)`, ['beta-quantile'], t('math.palette.beta-quantile.meaning')),
  item('normal-pdf', 'statistics', t('math.palette.normal-pdf.label'), 'normalpdf', String.raw`\operatorname{normalpdf}\left(#0,#?,#?\right)`, ['normal-pdf'], t('math.palette.normal-pdf.meaning')),
  item('normal-cdf', 'statistics', t('math.palette.normal-cdf.label'), 'normalcdf', String.raw`\operatorname{normalcdf}\left(#0,#?,#?\right)`, ['normal-cdf'], t('math.palette.normal-cdf.meaning')),
  item('normal-quantile', 'statistics', t('math.palette.normal-quantile.label'), 'normalquantile', String.raw`\operatorname{normalquantile}\left(#0,#?,#?\right)`, ['normal-quantile'], t('math.palette.normal-quantile.meaning')),
  item('expectation', 'statistics', t('math.palette.expectation.label'), 'expectation', String.raw`\operatorname{expectation}\left(#0,#?\right)`, ['expectation'], t('math.palette.expectation.meaning')),
  item('probability-variance', 'statistics', t('math.palette.probability-variance.label'), 'probabilityvariance', String.raw`\operatorname{probabilityvariance}\left(#0,#?\right)`, ['probability-variance'], t('math.palette.probability-variance.meaning')),
  item('conditional-probability', 'statistics', t('math.palette.conditional-probability.label'), 'conditionalprobability', String.raw`\operatorname{conditionalprobability}\left(#0,#?\right)`, ['conditional-probability'], t('math.palette.conditional-probability.meaning')),
  item('uniform-pdf', 'statistics', t('math.palette.uniform-pdf.label'), 'uniformpdf', String.raw`\operatorname{uniformpdf}\left(#0,#?,#?\right)`, ['uniform-pdf'], t('math.palette.uniform-pdf.meaning')),
  item('uniform-cdf', 'statistics', t('math.palette.uniform-cdf.label'), 'uniformcdf', String.raw`\operatorname{uniformcdf}\left(#0,#?,#?\right)`, ['uniform-cdf'], t('math.palette.uniform-cdf.meaning')),
  item('uniform-quantile', 'statistics', t('math.palette.uniform-quantile.label'), 'uniformquantile', String.raw`\operatorname{uniformquantile}\left(#0,#?,#?\right)`, ['uniform-quantile'], t('math.palette.uniform-quantile.meaning')),
  item('exponential-pdf', 'statistics', t('math.palette.exponential-pdf.label'), 'exponentialpdf', String.raw`\operatorname{exponentialpdf}\left(#0,#?\right)`, ['exponential-pdf'], t('math.palette.exponential-pdf.meaning')),
  item('exponential-cdf', 'statistics', t('math.palette.exponential-cdf.label'), 'exponentialcdf', String.raw`\operatorname{exponentialcdf}\left(#0,#?\right)`, ['exponential-cdf'], t('math.palette.exponential-cdf.meaning')),
  item('exponential-quantile', 'statistics', t('math.palette.exponential-quantile.label'), 'exponentialquantile', String.raw`\operatorname{exponentialquantile}\left(#0,#?\right)`, ['exponential-quantile'], t('math.palette.exponential-quantile.meaning')),
  item('binomial-quantile', 'statistics', t('math.palette.binomial-quantile.label'), 'binomialquantile', String.raw`\operatorname{binomialquantile}\left(#0,#?,#?\right)`, ['binomial-quantile'], t('math.palette.binomial-quantile.meaning')),
  item('poisson-quantile', 'statistics', t('math.palette.poisson-quantile.label'), 'poissonquantile', String.raw`\operatorname{poissonquantile}\left(#0,#?\right)`, ['poisson-quantile'], t('math.palette.poisson-quantile.meaning')),
  item('poisson-pmf', 'statistics', t('math.palette.poisson-pmf.label'), 'poissonpmf', String.raw`\operatorname{poissonpmf}\left(#0,#?\right)`, ['poisson-pmf'], t('math.palette.poisson-pmf.meaning')),
  item('poisson-cdf', 'statistics', t('math.palette.poisson-cdf.label'), 'poissoncdf', String.raw`\operatorname{poissoncdf}\left(#0,#?\right)`, ['poisson-cdf'], t('math.palette.poisson-cdf.meaning')),
  item('svd-u', 'linear-algebra', t('math.palette.svd-u.label'), 'U', String.raw`\operatorname{svdu}\left(#0\right)`, ['svd-u'], t('math.palette.svd-u.meaning')),
  item('svd-s', 'linear-algebra', t('math.palette.svd-s.label'), 'Σ', String.raw`\operatorname{svds}\left(#0\right)`, ['svd-s'], t('math.palette.svd-s.meaning')),
  item('svd-v', 'linear-algebra', t('math.palette.svd-v.label'), 'V', String.raw`\operatorname{svdv}\left(#0\right)`, ['svd-v'], t('math.palette.svd-v.meaning')),
  item('eigenspace', 'linear-algebra', t('math.palette.eigenspace.label'), 'ker(A−λI)', String.raw`\operatorname{eigenspace}\left(#0,#?\right)`, ['eigenspace'], t('math.palette.eigenspace.meaning')),
  item('tensor-product', 'linear-algebra', t('math.palette.tensor-product.label'), 'A⊗B', String.raw`\operatorname{tensorproduct}\left(#0,#?\right)`, ['tensor-product'], t('math.palette.tensor-product.meaning')),
  item('hadamard-product', 'linear-algebra', t('math.palette.hadamard-product.label'), 'A⊙B', String.raw`\operatorname{hadamardproduct}\left(#0,#?\right)`, ['hadamard-product'], t('math.palette.hadamard-product.meaning')),
  item('tensor-contract', 'linear-algebra', t('math.palette.tensor-contract.label'), 'ΣTᵢᵢ', String.raw`\operatorname{tensorcontract}\left(#0,#?,#?\right)`, ['tensor-contract'], t('math.palette.tensor-contract.meaning')),
  item('tensor-permute', 'linear-algebra', t('math.palette.tensor-permute.label'), 'Tσ', String.raw`\operatorname{tensorpermute}\left(#0,#?\right)`, ['tensor-permute'], t('math.palette.tensor-permute.meaning')),
  item('tensor-shape', 'linear-algebra', t('math.palette.tensor-shape.label'), 'shape(T)', String.raw`\operatorname{tensorshape}\left(#0\right)`, ['tensor-shape'], t('math.palette.tensor-shape.meaning')),
  item('tensor-element', 'linear-algebra', t('math.palette.tensor-element.label'), 'Tᵢⱼₖ', String.raw`\operatorname{tensorelement}\left(#0,#?\right)`, ['tensor-element'], t('math.palette.tensor-element.meaning')),
  item('kronecker-delta', 'linear-algebra', t('math.palette.kronecker-delta.label'), 'δᵢⱼ', String.raw`\operatorname{kroneckerdelta}\left(#0,#?\right)`, ['kronecker-delta'], t('math.palette.kronecker-delta.meaning')),
  item('levi-civita', 'linear-algebra', t('math.palette.levi-civita.label'), 'εᵢⱼₖ', String.raw`\operatorname{levicivita}\left(#0\right)`, ['levi-civita'], t('math.palette.levi-civita.meaning')),
  item('integer-quotient', 'basic', t('math.palette.integer-quotient.label'), 'q', String.raw`\operatorname{integerquotient}\left(#0,#?\right)`, ['integer-quotient'], t('math.palette.integer-quotient.meaning')),
  item('integer-remainder', 'basic', t('math.palette.integer-remainder.label'), 'r', String.raw`\operatorname{integerremainder}\left(#0,#?\right)`, ['integer-remainder'], t('math.palette.integer-remainder.meaning')),
  item('divides', 'sets-logic', t('math.palette.divides.label'), 'a|b', String.raw`\operatorname{divides}\left(#0,#?\right)`, ['divides'], t('math.palette.divides.meaning')),
  item('congruent-modulo', 'sets-logic', t('math.palette.congruent-modulo.label'), 'a≡b (mod m)', String.raw`\operatorname{congruentmodulo}\left(#0,#?,#?\right)`, ['congruent-modulo'], t('math.palette.congruent-modulo.meaning')),
  item('is-prime', 'sets-logic', t('math.palette.is-prime.label'), 'prime?', String.raw`\operatorname{isprime}\left(#0\right)`, ['is-prime'], t('math.palette.is-prime.meaning')),
  item('next-prime', 'basic', t('math.palette.next-prime.label'), 'next prime', String.raw`\operatorname{nextprime}\left(#0\right)`, ['next-prime'], t('math.palette.next-prime.meaning')),
  item('prime-factors', 'basic', t('math.palette.prime-factors.label'), 'n=∏pᵏ', String.raw`\operatorname{primefactors}\left(#0\right)`, ['prime-factors'], t('math.palette.prime-factors.meaning')),
  item('divisors', 'basic', t('math.palette.divisors.label'), 'd|n', String.raw`\operatorname{divisors}\left(#0\right)`, ['divisors'], t('math.palette.divisors.meaning')),
  item('euler-totient', 'basic', t('math.palette.euler-totient.label'), 'φ(n)', String.raw`\operatorname{eulertotient}\left(#0\right)`, ['euler-totient'], t('math.palette.euler-totient.meaning')),
  item('singular-values', 'linear-algebra', t('math.palette.singular-values.label'), 'σ', String.raw`\operatorname{singularvalues}\left(#0\right)`, ['singular-values'], t('math.palette.singular-values.meaning')),
  item('eigenvalues', 'linear-algebra', t('math.palette.eigenvalues.label'), 'λ', String.raw`\operatorname{eigenvalues}\left(#0\right)`, ['eigenvalues'], t('math.palette.eigenvalues.meaning')),
  item('row-reduce', 'linear-algebra', t('math.palette.row-reduce.label'), 'rref', String.raw`\operatorname{rowreduce}\left(#0\right)`, ['row-reduce'], t('math.palette.row-reduce.meaning')),
  item('qr-q', 'linear-algebra', t('math.palette.qr-q.label'), 'Q', String.raw`\operatorname{qrq}\left(#0\right)`, ['qr-q'], t('math.palette.qr-q.meaning')),
  item('qr-r', 'linear-algebra', t('math.palette.qr-r.label'), 'R', String.raw`\operatorname{qrr}\left(#0\right)`, ['qr-r'], t('math.palette.qr-r.meaning')),
  item('lu-p', 'linear-algebra', t('math.palette.lu-p.label'), 'P', String.raw`\operatorname{lup}\left(#0\right)`, ['lu-p'], t('math.palette.lu-p.meaning')),
  item('lu-l', 'linear-algebra', t('math.palette.lu-l.label'), 'L', String.raw`\operatorname{lul}\left(#0\right)`, ['lu-l'], t('math.palette.lu-l.meaning')),
  item('lu-u', 'linear-algebra', t('math.palette.lu-u.label'), 'U', String.raw`\operatorname{luu}\left(#0\right)`, ['lu-u'], t('math.palette.lu-u.meaning')),
  item('characteristic-coefficients', 'linear-algebra', t('math.palette.characteristic-coefficients.label'), 'det(tI−A)', String.raw`\operatorname{characteristiccoefficients}\left(#0\right)`, ['characteristic-coefficients'], t('math.palette.characteristic-coefficients.meaning')),
  item('null-space', 'linear-algebra', t('math.palette.null-space.label'), 'ker A', String.raw`\operatorname{nullspace}\left(#0\right)`, ['null-space'], t('math.palette.null-space.meaning')),
  item('column-space', 'linear-algebra', t('math.palette.column-space.label'), 'col A', String.raw`\operatorname{columnspace}\left(#0\right)`, ['column-space'], t('math.palette.column-space.meaning')),
  item('row-space', 'linear-algebra', t('math.palette.row-space.label'), 'row A', String.raw`\operatorname{rowspace}\left(#0\right)`, ['row-space'], t('math.palette.row-space.meaning')),
  item('linear-solve', 'linear-algebra', t('math.palette.linear-solve.label'), 'Ax=b', String.raw`\operatorname{linearsolve}\left(#0,#?\right)`, ['linear-solve'], t('math.palette.linear-solve.meaning')),
  item('linear-solution-space', 'linear-algebra', t('math.palette.linear-solution-space.label'), 'x₀+Σtᵢvᵢ', String.raw`\operatorname{linearsolutionspace}\left(#0,#?\right)`, ['linear-solution-space'], t('math.palette.linear-solution-space.meaning')),
  item('reciprocal', 'basic', t('math.palette.reciprocal.label'), '1/x', String.raw`\operatorname{reciprocal}\left(#0\right)`, ['reciprocal'], t('math.palette.reciprocal.meaning'), [t('math.palette.reciprocal.keyword0'), t('math.palette.reciprocal.keyword1')]),
  item('double-factorial', 'basic', t('math.palette.double-factorial.label'), 'n!!', String.raw`{#0}!!`, ['double-factorial'], t('math.palette.double-factorial.meaning')),
  item('permutations', 'basic', t('math.palette.permutations.label'), 'nPr', String.raw`\operatorname{permutations}\left(#0,#?\right)`, ['permutations'], t('math.palette.permutations.meaning'), [t('math.palette.permutations.keyword0'), t('math.palette.permutations.keyword1')]),
  item('clamp', 'basic', t('math.palette.clamp.label'), 'clamp', String.raw`\operatorname{clamp}\left(#0,#?,#?\right)`, ['clamp'], t('math.palette.clamp.meaning')),
  item('arccot', 'functions', t('math.palette.arccot.label'), 'arccot', String.raw`\operatorname{arccot}\left(#0\right)`, ['arccot'], t('math.palette.arccot.meaning'), [t('math.palette.arccot.keyword0'), t('math.palette.arccot.keyword1')]),
  item('arcsec', 'functions', t('math.palette.arcsec.label'), 'arcsec', String.raw`\operatorname{arcsec}\left(#0\right)`, ['arcsec'], t('math.palette.arcsec.meaning'), [t('math.palette.arcsec.keyword0'), t('math.palette.arcsec.keyword1')]),
  item('arccsc', 'functions', t('math.palette.arccsc.label'), 'arccsc', String.raw`\operatorname{arccsc}\left(#0\right)`, ['arccsc'], t('math.palette.arccsc.meaning'), [t('math.palette.arccsc.keyword0'), t('math.palette.arccsc.keyword1')]),
  item('atan2', 'functions', t('math.palette.atan2.label'), 'atan2(y,x)', String.raw`\operatorname{arctan2}\left(#0,#?\right)`, ['arctan-two'], t('math.palette.atan2.meaning'), [t('math.palette.atan2.keyword0'), t('math.palette.atan2.keyword1'), t('math.palette.atan2.keyword2')]),
  item('coth', 'functions', t('math.palette.coth.label'), 'coth', String.raw`\operatorname{coth}\left(#0\right)`, ['coth'], t('math.palette.coth.meaning')),
  item('sech', 'functions', t('math.palette.sech.label'), 'sech', String.raw`\operatorname{sech}\left(#0\right)`, ['sech'], t('math.palette.sech.meaning')),
  item('csch', 'functions', t('math.palette.csch.label'), 'csch', String.raw`\operatorname{csch}\left(#0\right)`, ['csch'], t('math.palette.csch.meaning')),
  item('arcoth', 'functions', t('math.palette.arcoth.label'), 'acoth', String.raw`\operatorname{arcoth}\left(#0\right)`, ['arcoth'], t('math.palette.arcoth.meaning'), [t('math.palette.arcoth.keyword0')]),
  item('arsech', 'functions', t('math.palette.arsech.label'), 'asech', String.raw`\operatorname{arsech}\left(#0\right)`, ['arsech'], t('math.palette.arsech.meaning'), [t('math.palette.arsech.keyword0')]),
  item('arcsch', 'functions', t('math.palette.arcsch.label'), 'acsch', String.raw`\operatorname{arcsch}\left(#0\right)`, ['arcsch'], t('math.palette.arcsch.meaning'), [t('math.palette.arcsch.keyword0')]),
  item('component', 'linear-algebra', t('math.palette.component.label'), 'Aᵢⱼ', String.raw`\operatorname{component}\left(#0,#?,#?\right)`, ['component'], t('math.palette.component.meaning'), [t('math.palette.component.keyword0'), t('math.palette.component.keyword1'), t('math.palette.component.keyword2'), t('math.palette.component.keyword3')]),
  item('fraction', 'basic', t('math.palette.fraction.label'), 'a/b', String.raw`\frac{#0}{#?}`, ['divide'], t('math.palette.fraction.meaning'), [t('math.palette.fraction.keyword0'), t('math.palette.fraction.keyword1')]),
  item('power', 'basic', t('math.palette.power.label'), 'xⁿ', String.raw`{#0}^{#?}`, ['power'], t('math.palette.power.meaning'), [t('math.palette.power.keyword0'), t('math.palette.power.keyword1')]),
  item('square-root', 'basic', t('math.palette.square-root.label'), '√', String.raw`\sqrt{#0}`, ['sqrt'], t('math.palette.square-root.meaning'), [t('math.palette.square-root.keyword0'), t('math.palette.square-root.keyword1')]),
  item('nth-root', 'basic', t('math.palette.nth-root.label'), 'ⁿ√', String.raw`\sqrt[#?]{#0}`, ['root'], t('math.palette.nth-root.meaning'), [t('math.palette.nth-root.keyword0'), t('math.palette.nth-root.keyword1')]),
  item('factorial', 'basic', t('math.palette.factorial.label'), 'n!', String.raw`{#0}!`, ['factorial'], t('math.palette.factorial.meaning'), [t('math.palette.factorial.keyword0')]),
  item('absolute', 'basic', t('math.palette.absolute.label'), '|x|', String.raw`\left|#0\right|`, ['absolute'], t('math.palette.absolute.meaning'), [t('math.palette.absolute.keyword0'), t('math.palette.absolute.keyword1')]),
  item('sin', 'functions', t('math.palette.sin.label'), 'sin', String.raw`\sin\left(#0\right)`, ['sin'], t('math.palette.sin.meaning'), [t('math.palette.sin.keyword0')]),
  item('cos', 'functions', t('math.palette.cos.label'), 'cos', String.raw`\cos\left(#0\right)`, ['cos'], t('math.palette.cos.meaning'), [t('math.palette.cos.keyword0')]),
  item('tan', 'functions', t('math.palette.tan.label'), 'tan', String.raw`\tan\left(#0\right)`, ['tan'], t('math.palette.tan.meaning'), [t('math.palette.tan.keyword0')]),
  item('arcsin', 'functions', t('math.palette.arcsin.label'), 'arcsin', String.raw`\arcsin\left(#0\right)`, ['arcsin'], t('math.palette.arcsin.meaning'), [t('math.palette.arcsin.keyword0'), t('math.palette.arcsin.keyword1')]),
  item('log-natural', 'functions', t('math.palette.log-natural.label'), 'ln', String.raw`\ln\left(#0\right)`, ['natural-log'], t('math.palette.log-natural.meaning'), [t('math.palette.log-natural.keyword0'), t('math.palette.log-natural.keyword1')]),
  item('log-ten', 'functions', t('math.palette.log-ten.label'), 'log₁₀', String.raw`\log_{10}\left(#0\right)`, ['log-ten'], t('math.palette.log-ten.meaning'), [t('math.palette.log-ten.keyword0'), t('math.palette.log-ten.keyword1')]),
  item('log-base', 'functions', t('math.palette.log-base.label'), 'logₐ', String.raw`\log_{#?}\left(#0\right)`, ['log-base'], t('math.palette.log-base.meaning'), [t('math.palette.log-base.keyword0'), t('math.palette.log-base.keyword1')]),
  item('sinh', 'functions', t('math.palette.sinh.label'), 'sinh', String.raw`\sinh\left(#0\right)`, ['sinh'], t('math.palette.sinh.meaning'), [t('math.palette.sinh.keyword0')]),
  item('sum', 'series', t('math.palette.sum.label'), 'Σ', String.raw`\sum_{i=1}^{#?}{#0}`, ['sum'], t('math.palette.sum.meaning'), [t('math.palette.sum.keyword0'), t('math.palette.sum.keyword1')]),
  item('product', 'series', t('math.palette.product.label'), '∏', String.raw`\prod_{i=1}^{#?}{#0}`, ['product'], t('math.palette.product.meaning'), [t('math.palette.product.keyword0')]),
  item('integral', 'calculus', t('math.palette.integral.label'), '∫', String.raw`\int_{#?}^{#?}{#0}\,\mathrm{d}x`, ['integrate'], t('math.palette.integral.meaning'), [t('math.palette.integral.keyword0'), t('math.palette.integral.keyword1')]),
  item('derivative', 'calculus', t('math.palette.derivative.label'), 'd/dx', String.raw`\frac{\mathrm{d}}{\mathrm{d}#?}{#0}`, ['differentiate'], t('math.palette.derivative.meaning'), [t('math.palette.derivative.keyword0'), t('math.palette.derivative.keyword1')]),
  item('partial', 'calculus', t('math.palette.partial.label'), '∂/∂x', String.raw`\frac{\partial}{\partial #?}{#0}`, ['differentiate'], t('math.palette.partial.meaning'), [t('math.palette.partial.keyword0')]),
  item('limit', 'calculus', t('math.palette.limit.label'), 'lim', String.raw`\lim_{x\to #?}{#0}`, ['limit'], t('math.palette.limit.meaning'), [t('math.palette.limit.keyword0')]),
  item('matrix', 'linear-algebra', t('math.palette.matrix.label'), '[A]', String.raw`\begin{pmatrix}#?&#?\\#?&#?\end{pmatrix}`, ['matrix', 'list'], t('math.palette.matrix.meaning'), [t('math.palette.matrix.keyword0'), t('math.palette.matrix.keyword1')]),
  item('determinant', 'linear-algebra', t('math.palette.determinant.label'), 'det', String.raw`\det\left(#0\right)`, ['determinant'], t('math.palette.determinant.meaning'), [t('math.palette.determinant.keyword0')]),
  item('dot', 'linear-algebra', t('math.palette.dot.label'), 'a·b', String.raw`#0\cdot #?`, ['dot'], t('math.palette.dot.meaning'), [t('math.palette.dot.keyword0')]),
  item('cross', 'linear-algebra', t('math.palette.cross.label'), 'a×b', String.raw`#0\times #?`, ['cross'], t('math.palette.cross.meaning'), [t('math.palette.cross.keyword0')]),
  item('real-part', 'complex', t('math.palette.real-part.label'), 'Re', String.raw`\operatorname{Re}\left(#0\right)`, ['real-part'], t('math.palette.real-part.meaning'), [t('math.palette.real-part.keyword0'), t('math.palette.real-part.keyword1')]),
  item('imaginary-part', 'complex', t('math.palette.imaginary-part.label'), 'Im', String.raw`\operatorname{Im}\left(#0\right)`, ['imaginary-part'], t('math.palette.imaginary-part.meaning'), [t('math.palette.imaginary-part.keyword0'), t('math.palette.imaginary-part.keyword1')]),
  item('conjugate', 'complex', t('math.palette.conjugate.label'), 'z̄', String.raw`\overline{#0}`, ['conjugate'], t('math.palette.conjugate.meaning'), [t('math.palette.conjugate.keyword0'), t('math.palette.conjugate.keyword1')]),
  item('binomial-pmf', 'statistics', t('math.palette.binomial-pmf.label'), 'P(X=k)', String.raw`\operatorname{binomialpmf}\left(#0,#?,#?\right)`, ['binomial-pmf'], t('math.palette.binomial-pmf.meaning')),
  item('binomial-cdf', 'statistics', t('math.palette.binomial-cdf.label'), 'P(X≤x)', String.raw`\operatorname{binomialcdf}\left(#0,#?,#?\right)`, ['binomial-cdf'], t('math.palette.binomial-cdf.meaning')),
  item('mean', 'statistics', t('math.palette.mean.label'), 'mean', String.raw`\operatorname{mean}\left(#0\right)`, ['mean'], t('math.palette.mean.meaning'), [t('math.palette.mean.keyword0'), t('math.palette.mean.keyword1')]),
  item('median', 'statistics', t('math.palette.median.label'), 'median', String.raw`\operatorname{median}\left(#0\right)`, ['median'], t('math.palette.median.meaning')),
  item('modes', 'statistics', t('math.palette.modes.label'), 'modes', String.raw`\operatorname{modes}\left(#0\right)`, ['modes'], t('math.palette.modes.meaning')),
  item('quantile', 'statistics', t('math.palette.quantile.label'), 'quantile', String.raw`\operatorname{quantile}\left(#0,#?\right)`, ['quantile'], t('math.palette.quantile.meaning')),
  item('population-variance', 'statistics', t('math.palette.population-variance.label'), 'σ²', String.raw`\operatorname{populationvariance}\left(#0\right)`, ['population-variance'], t('math.palette.population-variance.meaning')),
  item('sample-variance', 'statistics', t('math.palette.sample-variance.label'), 's²', String.raw`\operatorname{samplevariance}\left(#0\right)`, ['sample-variance'], t('math.palette.sample-variance.meaning')),
  item('population-standard-deviation', 'statistics', t('math.palette.population-standard-deviation.label'), 'σ', String.raw`\operatorname{populationstandarddeviation}\left(#0\right)`, ['population-standard-deviation'], t('math.palette.population-standard-deviation.meaning')),
  item('sample-standard-deviation', 'statistics', t('math.palette.sample-standard-deviation.label'), 's', String.raw`\operatorname{samplestandarddeviation}\left(#0\right)`, ['sample-standard-deviation'], t('math.palette.sample-standard-deviation.meaning')),
  item('population-covariance', 'statistics', t('math.palette.population-covariance.label'), 'covₙ', String.raw`\operatorname{populationcovariance}\left(#0,#?\right)`, ['population-covariance'], t('math.palette.population-covariance.meaning')),
  item('sample-covariance', 'statistics', t('math.palette.sample-covariance.label'), 'covₙ₋₁', String.raw`\operatorname{samplecovariance}\left(#0,#?\right)`, ['sample-covariance'], t('math.palette.sample-covariance.meaning')),
  item('correlation', 'statistics', t('math.palette.correlation.label'), 'r', String.raw`\operatorname{correlation}\left(#0,#?\right)`, ['correlation'], t('math.palette.correlation.meaning')),
  item('regression-slope', 'statistics', t('math.palette.regression-slope.label'), 'a', String.raw`\operatorname{regressionslope}\left(#0,#?\right)`, ['regression-slope'], t('math.palette.regression-slope.meaning')),
  item('regression-intercept', 'statistics', t('math.palette.regression-intercept.label'), 'b', String.raw`\operatorname{regressionintercept}\left(#0,#?\right)`, ['regression-intercept'], t('math.palette.regression-intercept.meaning')),
  item('r-squared', 'statistics', t('math.palette.r-squared.label'), 'R²', String.raw`\operatorname{rsquared}\left(#0,#?\right)`, ['r-squared'], t('math.palette.r-squared.meaning')),
  item('intersection', 'sets-logic', t('math.palette.intersection.label'), '∩', String.raw`#0\cap #?`, ['intersection'], t('math.palette.intersection.meaning'), [t('math.palette.intersection.keyword0'), t('math.palette.intersection.keyword1')]),
  item('union', 'sets-logic', t('math.palette.union.label'), '∪', String.raw`#0\cup #?`, ['union'], t('math.palette.union.meaning'), [t('math.palette.union.keyword0'), t('math.palette.union.keyword1')]),
  item('cases', 'sets-logic', t('math.palette.cases.label'), 'cases', String.raw`\begin{cases}#?&#?\\#?&#?\end{cases}`, ['which'], t('math.palette.cases.meaning'), [t('math.palette.cases.keyword0'), t('math.palette.cases.keyword1')]),
  item('equal', 'equations', t('math.palette.equal.label'), '=', String.raw`#0=#?`, ['equal'], t('math.palette.equal.meaning'), [t('math.palette.equal.keyword0')]),
  item('pi', 'symbols', t('math.palette.pi.label'), 'π', String.raw`\pi`, [], t('math.palette.pi.meaning'), [t('math.palette.pi.keyword0'), t('math.palette.pi.keyword1')]),
  item('imaginary-unit', 'symbols', t('math.palette.imaginary-unit.label'), 'ⅈ', String.raw`\mathrm{i}`, [], t('math.palette.imaginary-unit.meaning'), [t('math.palette.imaginary-unit.keyword0'), t('math.palette.imaginary-unit.keyword1')]),
];

export function searchMathPalette(query: string, entries: readonly MathPaletteItem[]): readonly MathPaletteItem[] {
  const terms = query.normalize('NFKC').toLocaleLowerCase('ja').trim().split(/\s+/u).filter(Boolean);
  return entries.filter(entry => {
    const content = [entry.label, entry.symbol, entry.id, entry.meaning, ...entry.keywords].join(' ').normalize('NFKC').toLocaleLowerCase('ja');
    return terms.every(term => content.includes(term));
  });
}

export function mathPaletteAvailability(entry: MathPaletteItem, verifiedOperations: ReadonlySet<string>,
  passedAcceptanceIds: ReadonlySet<string>): boolean {
  return entry.acceptanceIds.length > 0 && entry.acceptanceIds.every(id => passedAcceptanceIds.has(id))
    && entry.requiredOperations.every(id => verifiedOperations.has(id));
}
